### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by judokan9** [Seitanas/kvm-vdi#1]
Hello,

i woul like to use Kvm-Vdi but i dont know how to install it. Im on ubutnu 16.04 and i have installed apache2, php7.0, apache-php7.0, mariadb, apache-mysql. I get the login screen but when i type in a username and password nothing happens and im on a white page. It would be nice when you can create a short installation/requirement guide. 

Thanks

![pob1](https://cloud.githubusercontent.com/assets/18271781/15078179/40469b12-13b2-11e6-9e94-9b40f9b5face.jpg)
![pob2](https://cloud.githubusercontent.com/assets/18271781/15078181/430540a6-13b2-11e6-958d-a859c6463109.jpg)

**Comment by Seitanas** [comment]
Hello,
yes installation scripts of a dashboard and documentation are on the way and will be produced in near future.
Meanwhile, please clone sql/vdi.sql database scheme again. I've added default user "admin" with password "password". Please import it into your database. Hope will help.

**Comment by Seitanas** [comment]
Also, I see you are using php 7. Could you please paste php error log?

**Comment by Seitanas** [comment]
Problems with php7 are fixed. Moved system from mysql to mysqli functions. Dashboard will be automatically installed on first visit.

**Comment by ahmedgc01** [comment]
Can any body help me . I have installed kvm-vdi dashboard on ubuntu 16. I got dashboard on web page but when i enter user name admin and password "password" it say wrong . thank if you solve this problem .

**Comment by Max-bazinga** [comment]
please check your db table users. This is the result of mine.
MariaDB [vdi]> select * from  users;
+----+----------+---------------+-----------------+---------------------+-------------------------------------------+
| id | username | password      | ip              | lastlogin           | config                                    |
+----+----------+---------------+-----------------+---------------------+-------------------------------------------+
|  1 | admin    | SeONYJNly1OC6 | 192.168.130.113 | 2018-06-22 01:00:48 | a:1:{s:16:"table_section-14";s:4:"show";} |
+----+----------+---------------+-----------------+---------------------+-------------------------------------------+
1 row in set (0.00 sec)
