### ISSUE TITLE
Editing hypervisor config and thinclient vdi script is not in readme

### ISSUE THREAD

**Issue by jphein** [Seitanas/kvm-vdi#10]
I had to edit on hpervisor 
/usr/local/VDI/config
and on thin client
/usr/local/bin/vdi
In order for them to talk to the dashboard.

**Comment by jphein** [comment]
I also had to edit /usr/local/bin/vdi
To look for remote-viewer in /usr/bin instead.

Replaced
`os.system("startx /usr/local/bin/remote-viewer --kiosk-quit=on-disconnect  --kiosk spice://" +tmp[0] + ":" + tmp[1] + "  ")`
With
`os.system("startx /usr/bin/remote-viewer --kiosk-quit=on-disconnect  --kiosk spice://" +tmp[0] + ":" + tmp[1] + "  ")`

**Comment by Seitanas** [comment]
Yes, thank you. It seems this i have overlooked those paths, since I was using a self-compiled virt-viewer in our installment.

**Comment by jphein** [comment]
Awesome!
