### ISSUE TITLE
Create VM's Menu on Dashboard does not define the VM in the hypervisor anymore

### ISSUE THREAD

**Issue by norwalk350** [Seitanas/kvm-vdi#101]
Hi Tadas,

   We've used your system since November of 2016. Over the early months of 2017 we've customized some of the php, and I think we may have broken the KVM-VDI interface's ability to "virsh define" a domain from the create_vms.php (or whatever else may be involved.)  

1. The qcow2 is created
2. The window is stuck at "creating vm please wait"
3. If we create an XML for that qcow2 and point it to the initial (if it's a VDI qcow2) or the source (if it's an initial), manually copy from the source to the qcow2 and then define the XML, the VM will appear in the dashboard. From there we can click on the VM and tell it what type of machine, hypervisor etc and it will nest beneath the initial (if it's a VDI we're creating).
4. From there we have control, via the dashboard, over the VM and it works - it's just the xml and defining actions your interface provides that we've obviously broken somewhere down the line.

Given that, and short of cloning your Git (this is a production box unfortunately) would you be willing to take a look at some of our php files or offer some assistance? Thanks in advance for anything you would do to help.

**Comment by Seitanas** [comment]
Hello,
lets just try basic steps before we dig into the code.
First of all, please enable debug mode `$write_debug_log=true;` at this point each reply from hypervisor will be logged. You will be able to see all steps of VM creation in your web server's error log. Also, you should see all the calls from dashboard to your hypervisor in your /var/log/auth.log (if using debian-based OS).
So, just enable debugging, create machine and paste your webserver's error log, and also auth log to see, what happens.
