### ISSUE TITLE
SPICE password 

### ISSUE THREAD

**Issue by nmitchell1185** [Seitanas/kvm-vdi#102]
Is there a way to dictate what password is used for the SPICE connection? Or possibly a way to prevent the use of a password altogether?

**Comment by Seitanas** [comment]
SPICE password is generated randomly on each VM startup:
https://github.com/Seitanas/kvm-vdi/blob/c9da3c02a1717e3cb5aa5af990ef84714872c31c/KVM/hypervisors/vdi-wrapper#L15
Currently KVM-VDI does not support password-less sessions for security reasons.

**Comment by nmitchell1185** [comment]
I tried replacing that line with 'password,' however, it keeps generating a random password. 
I am attempting to get it so I can script out the thin client connecting to the VM. The easiest way to do that is by using a preset password vice a randomly generated one.

**Comment by Seitanas** [comment]
It should not generate random if you will put `spice_password='password'` instead of code above.
Also, you should be able to get password from database if needed.  After VM is up, its SPICE password is stored in `vms.spice_password` table entry.
