### ISSUE TITLE
client unable to connect to graphic server

### ISSUE THREAD

**Issue by aslefnad** [Seitanas/kvm-vdi#104]
i hope you can help me. when i try to connect to a vdi using the kvm-vdi-client i always get the error "unable to connect to graphic server /tmp/[cryptic config file]" when i take a look inside that config file i see that localhost is set as a host.
But in the kvm-vdi-client config i did set the right server address.
is there something i can do?

thanks for your help

**Comment by Seitanas** [comment]
Hello,
problem is with wrong SPICE address setting in your hypervisor config.
Go to your Dashboard>System>Modify hypervisors. Set correct SPICE IP address

**Comment by aslefnad** [comment]
thanks so much. that solved it
