### ISSUE TITLE
Can dashboard and Hypervisor be installed in same server?

### ISSUE THREAD

**Issue by raharida** [Seitanas/kvm-vdi#106]
HI

I am trying to setup kvm-vdi . I have setup Dashboard application and trying to setup a Hypervisor. Is it fine if both the system are on the same Machine? Because I am facing the following 

I have set up Hypervisor based on the wiki and ran the following command as mentioned

ssh -i /var/hyper_keys/id_rsa VDI@ip_address
I ran the above command as root
The connection was successful and terminal connectted as VDI user

But from the dashboard application when i am trying to add a hypervisor I am receiving Got error: BAD_SSH_ADDRESS . I am receiving the error from https://github.com/Seitanas/kvm-vdi/blob/c9da3c02a1717e3cb5aa5af990ef84714872c31c/inc/infrastructure/KVM/UpdateHypervisors.php#L34.

**Comment by Seitanas** [comment]
Hello,
yes, dashboard can be installed on  hypervisor server.
Try using 127.0.0.1 as hypervisor address when adding a new hypervisor.
Also please check your webserver error log files.

**Comment by raharida** [comment]
@Seitanas I get the following warning in the error log

 [Tue Nov 07 13:28:23.843085 2017] [:error] [pid 1754] [client 192.168.16.142:52825] PHP Warning:  ssh2_connect(): Unable to connect to 127.0.0.1 on port 22 in /var/www/html/kvm-vdi/inc/modules/KVM/functions.php on line 15, referer: http://192.168.19.52/kvm-vdi/dashboard.php

**Comment by Seitanas** [comment]
Is ssh server running? `telnet localhost 22`

**Comment by raharida** [comment]
Yes I am able to connect using telnet localhost 22

> Trying ::1...
> Connected to localhost.
> Escape character is '^]'.
> SSH-2.0-OpenSSH_7.4

**Comment by Seitanas** [comment]
That is ipv6 connection. Try `telnet 127.0.0.1 22`

**Comment by raharida** [comment]
It is getting connected as well

> telnet 127.0.0.1 22
> Trying 127.0.0.1...
> Connected to 127.0.0.1.
> Escape character is '^]'.
> SSH-2.0-OpenSSH_7.4

**Comment by Seitanas** [comment]
Did you try to connect from web-server user, not root?
Are there any errors about this in /var/log/auth.log?
What distribution is this?
Apparmor/selinux disableD?

**Comment by raharida** [comment]
Did you try to connect from web-server user, not root? - webserver is installed as root user
Are there any errors about this in /var/log/auth.log? The log file is not present
What distribution is this? - CentOS Linux release 7.4.1708
Apparmor/selinux disableD? - No selinux is disabled. I will disable it and update the result

Update: Disabled it. Still does not work.

**Comment by Seitanas** [comment]
There's something forbidding web-server to access 22 port.
If installed from packages, webserver is not ran as root user. `ps aux |grep http`

**Comment by raharida** [comment]
Thank you . I had to provide permission to hyper_keys for apache user
