### ISSUE TITLE
Question about KVM-VDI

### ISSUE THREAD

**Issue by ahmedkaballo** [Seitanas/kvm-vdi#107]
Hi 
i want to ask you regarding your kvm-vdi solution.
we tried to use  Ovirt for vdi but it's a virtualization manager and it has no connection broker features(i.e creating users, assign users to specific machine and managing connections).
my question is: does your kvm-vdi work as a connection broker ?
and the second question is: can i use RDP with kvm-vdi to connect to machines ?

**Comment by Seitanas** [comment]
Hello,
yes, KVM-VDI features a fully functional connection broker.
As for RDP - no, KVM-VDI uses SPICE protocol to connect to VMs.
