### ISSUE TITLE
Modification of wiki page for installation with OpenStack

### ISSUE THREAD

**Issue by naeemrashid** [Seitanas/kvm-vdi#108]
Please modify wiki page to include complete installation steps required for OpenStack VDI.

**Comment by Seitanas** [comment]
OpenStack module is still in development. Documentation is pending.

**Comment by ghost** [comment]
I have 3 memcache service on port 11211 running in HA environment. How to configure memcahe in an HA environment ,  under "functions/config.php".

thanks ,

**Comment by Seitanas** [comment]
Currently KVM-VDI does not support multiple memcache instances.

**Comment by ghost** [comment]
Hello Seitanas,
Thank you .

Found facebook mcrouter is an option.
https://github.com/facebook/mcrouter
