### ISSUE TITLE
Integrate to an existent KVM infrastructure

### ISSUE THREAD

**Issue by gilbertoferreira** [Seitanas/kvm-vdi#109]
Hi...

Is there a way to deploy kvm-vdi in an existent KVM infrastructure?
I have here Proxmox VE and many KVM Windows and Linux machine.
How can I integrate this two wonderful software?

Thanks

**Comment by Seitanas** [comment]
Hello, building VDI infrastructure over some kind of virtualization management is not supported. There are no tests done for KVM-VDI and Proxmox. You should use plain KVM and libvirtd.
