### ISSUE TITLE
HTML5 Viewer /tmp dependency conflict with systemd

### ISSUE THREAD

**Issue by cwriter** [Seitanas/kvm-vdi#110]
systemd marks apache2.service as PrivateTmp=true on newer debian-styled systems. This leads to it being unable to create files/directories (including /tmp/kvm-vdi) in /tmp. 
A fix could be use an own temporary directory, but I don't know if websocketify can handle different paths.

A workaround is disabling PrivateTmp for now on affected systems.
See: https://serverfault.com/a/615054

cwriter

**Comment by sskras** [comment]
Time to look for $TMPDIR and expand it if present?

**Comment by cwriter** [comment]
> Time to look for $TMPDIR and expand it if present?

Sorry, I didn't get that. Can you please elaborate?

**Comment by Seitanas** [comment]
This patch should fix the issue.
Token files will be written to:
https://github.com/Seitanas/kvm-vdi/blob/773ae56e142675cb44d7ea8d2a5591f8ec06542c/functions/config.php_kvm#L86
Afterwards you should change `--token-source` path when starting websockify.

**Comment by sskras** [comment]
@cwriter: please ignore.  It was a blind suggestion addressed mainly to the developer.  But oh well, this is PHP code and @Seitanas seems to already have a var for that matter.

Excuse me for the interruption guys:)

**Comment by cwriter** [comment]
> This patch should fix the issue.

It does 👍 

cwriter
