### ISSUE TITLE
VM with multiple disks

### ISSUE THREAD

**Issue by jromih** [Seitanas/kvm-vdi#111]
Hi,
do you have any plans to support  Source/Initial/VDI VM's with multiple disks?

Thank you,
Jernej

**Comment by Seitanas** [comment]
Hello,
no, I don't think so.
The idea of VM's being ephemeral makes no use of multiple disk drives. If you need some additional storage, perhaps you should use network FS mounts inside VMs (CIFS, NFS, etc).
