### ISSUE TITLE
not need Windows roaming profiles

### ISSUE THREAD

**Issue by Dmitry5755** [Seitanas/kvm-vdi#113]
hi
Tell me, please, should we take care of saving user profiles before updating the operating system? I realized that after the virtual machines are populated, user configurations are not saved.

**Comment by Seitanas** [comment]
Hello,
yes, in most VDI solutions VMs are ephemeral, meaning, that they are destroyed as soon as not needed.
You should use persistent storage such as CIFS/NFS to store user profiles.

**Comment by Dmitry5755** [comment]
Hi,
thanks for the answer.
From your point of view, what tool for saving profiles is better suited in this case?

**Comment by Seitanas** [comment]
Not sure about tools. Our best practice is to use remote CIFS mounts for user profiles

**Comment by Dmitry5755** [comment]
Thank's
Excuse me for unnecessary small questions, and what desktop environment debian are you installing to get an impersonal simple desktop image on a thin client?

![gui](https://user-images.githubusercontent.com/13812621/39348550-39b7cfc4-4a00-11e8-8096-e7f66b0e1d20.png)

**Comment by Seitanas** [comment]
We are using LXDE, but anything else should work fine

**Comment by Dmitry5755** [comment]
Thank you so much

**Comment by Dmitry5755** [comment]
Hi,
and I tried on diskless Intel nuc to run the client using Diskless Debian Linux booting via dhcp / pxe / nfs / tftp / aufs, but failed.
I understand that this is a whole separate topic for discussion, but I have successfully reached the boot diskless client in the command line, but then the graphical interface and startx do not start, apparently later versions of operating systems do not support the aufs. Or some problems with mounting in this file system. Huge request, please write how you are doing this in practice. Maybe there are any recommendations that have the greatest adaptive effect when implementing kvm-vdi? I'm using an article (http://debianaddict.com/2012/06/19/diskless-debian-linux-booting-via-dhcppxenfstftp/) But is it old, and for new versions of Linux is not suitable?

**Comment by Seitanas** [comment]
aufs is deprected - that is true.
you should use overlayFS (syntax is somewhat similar): https://en.wikipedia.org/wiki/OverlayFS
Or rollback to older kernel, whic is not recommended.
