### ISSUE TITLE
cache=none at cache=writeback

### ISSUE THREAD

**Issue by Dmitry5755** [Seitanas/kvm-vdi#114]
Hello,
I encountered a problem when I use SSD disks, then virtual machines are started only after the replacement in the CreateVM.php file cache=none at cache=writeback. This will not lead to any bad consequences? Maybe there are other ways to fix the problem?

**Comment by Seitanas** [comment]
You should better use ` writethrough` then, - it's the default KVM value.
Though I'm very curious, why do you fail with `none`.
Anyway, those changes should not lead to any bad consequences.

**Comment by Dmitry5755** [comment]
this may be due to the fact that, the hypervisor is deployed in a container in the environment lxd.
Containers are used privileged. And if I use two hypervisors in containers on the same host, then they do not let the virtual machines run successfully, if both are enabled..
And I still have the issue of deploying machines with the guest system Windows Server 2012r2, in the drop-down list there is no such operating system, I use the latest available, for example, win srv 2008?
And to install the drivers, I install an additional virt manager, so that I can connect the disk with the virtio. Or are there other ways? Why is windows server 2012 r2 through rdp works faster than using spices. Although there was no such problem with w7.

**Comment by Dmitry5755** [comment]
Hello,
It looks like I solved the problem mentioned earlier. Hypervisors no longer interfere with each other.
I updated the "kvm" device in LXD to have the "gif"
I'm sorry if I distracted you, thank you very much.
