### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by peuportier** [Seitanas/kvm-vdi#115]
#Dear Seitanas,

First thanks for your hard work. 

- Well i would like to know if hypervisor and also dashboard can be in same machine?

Thanks a lot. Wish you a good day

**Comment by Seitanas** [comment]
Hello, thank you!
Yes it can. Dashboard could be installed in separate virtual machine, or straight into hypervisor os.

**Comment by peuportier** [comment]
Hi Thanks man!

I will try your system this weekend and check whatever can contribute for help to your project. Cheers dude...

**Comment by ahmedgc01** [comment]
Hi guys,

I tried this project , installed kvm-vdi and dashboard . But I confused with statement "create empty database / user " in dashboard installation cited on wiki documentation . I'm on dashboard page but it does not accept credential " admin/ password". Can anybody help me . I spent 1 week but no success. Thanks. my email ahmedgc0101@gmail.com

**Comment by Seitanas** [comment]
Please do not crosspost. 
Create new thread.
`create empty database / user` means you need to create new database in mysql/maria db and also username with full rights to that database.

**Comment by Max-bazinga** [comment]
Maybe create empty database / user can be done auto in sql/vdi.sql file ?

**Comment by Seitanas** [comment]
That will mean, than sql fille will have to have root credentials
