### ISSUE TITLE
Dashboard wrong credential issue

### ISSUE THREAD

**Issue by ahmedgc01** [Seitanas/kvm-vdi#116]
Dear Seitanas , 

Thanks for reply in other post- issue, and on your advise,  I've created this post. 
Yes, I've created database like "vdi" with user "vdi" on mysql with full rights on ubuntu 16.04 for example , but I do not have any success yet . I also have changed file name from config.php_kvm to config.php at directory folder /var/www/html/kvm-vdi/functions/  and it is pretty sure I have given full right to that path directory including files , so there is not point of any permissions problems. 
I also changes settings in config.php file at functions folder with considerations 
localhost
database mysql
username " admin" (that i created on database mysql)
password "password" (that i created during user creation)
BUT no success .
Could you please help me 
Thank you very much .
Ahmad

**Comment by Max-bazinga** [comment]
Can you paste the content of the /var/log/httpd/error_log? 
You need note that the user VDI in hypervisor node must can anonymity to access to dashboard service node.

**Comment by ahmedgc01** [comment]
Hi Max-Bazinga, 

Thanks for reply 
There is no httpd at directory /var/log 
There is apache 2 error log file contains following 
[Thu Jun 21 01:54:05.979183 2018] [mpm_prefork:notice] [pid 1845] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Thu Jun 21 01:54:06.029163 2018] [core:notice] [pid 1845] AH00094: Command line: '/usr/sbin/apache2'
I wonder if you could help me . thanks.

**Comment by Seitanas** [comment]
If you created database `vdi` and username `vdi` for that database, then your config.php should have following configuration:

```
    $mysql_host='localhost';
    $mysql_db='vdi';
    $mysql_user='vdi';
    $mysql_pass='yourpassword';
```

**Comment by ahmedgc01** [comment]
yes i already created database "vdi" with user and password " vdi" and "mypassword" respectively. 
The configurations in config.php is similar to the your above ones. 
but no success. 
question is: Using username vdi in config.php file and database mysql ,  does it make sense to use the credential with user name "admin" and password" password" .Coz both are different .

**Comment by Seitanas** [comment]
I'm not really following your question.
Credentials in `config.php` are for connecting to db only.
After configuring `config.php`, you should visit kvm-vdi dashboard page, - it should install database schema and create default user `admin` with a password `password` - which you will use to login to dasboard.

**Comment by ahmedgc01** [comment]
Thanks 
The below is configuration of config.php file . I have been encountering problem of dashboard credential I'm still unable to login. can you remotely see my work by sharing desktop .that would be really great help.  

<?php
/*
KVM-VDI
Tadas Ustinavičius

Vilnius University.
Center of Information Technology Development.


Vilnius,Lithuania.
2017-03-10
*/


###################Dashboard config##########################
$serviceurl='http://localhost/kvm-vdi';
$language='en_EN';
#define salt string, which will be used to generate passwords.
$salt='SecretString';
#write debug log to web server error.log file.
$write_debug_log=false;
#Websockify server address (if using HTML5 client)
$websockets_address='192.168.0.20';
#Port of websockify server (if using HTML5 client)
$websockets_port='5959';
#If $send_email_alerts is enabled, dashboard will send alerts to
#$alert_email_to critical error will occur. Requires PEAR Mail library.
$send_email_alerts=false;
$alert_email_to='kvm-admin@domain.tld';
$alert_email_from='kvm-dashboard@domain.tld';
$smtp_server_address='smtp.server.tld';
$smtp_server_port='25';
$smtp_ssl=false;
$smtp_auth=false;
$smtp_auth_username='someuser';
$smtp_auth_password='somepass';
# If true, dashboard will substitute SPICE address
# with hypervisor address.
$use_hypervisor_address = true;
############################################################


##################VM config#################################
#Time in minutes, after which VM will return to pool if
#thin client disconnects:
$return_to_pool_after=5;
#Enable this if you want to reset VMs each time they are provided
#to client. This will not affect machines, which are taken over by
#another thin client with the same username, within time, specified
#in $return_to_pool_after.
$reset_vm=0;
############################################################


####################Active Directory/LDAP logins#############
#please specify your LDAP backend:
$LDAP_backend='activedir';
#$LDAP_backend='ldap';
#Domain part to be added to username (only for Active Directory).
$domain_name='domain.tld';
#Address of ACtive Directory/LDAP server.
$LDAP_host='192.168.0.20';
#Username and password to bind to LDAP server (not deeded by Active Directory):
$LDAP_username='uid=USERNAME,ou=bind users,dc=domain,dc=tld';
$LDAP_password='ldappassword';
#Base DN pattern:
$base_dn = 'ou=People,DC=domain,DC=tld';
#For LDAP backend you should specify base DN including username:
#$base_dn = 'uid=%username%,ou=people,dc=domain,dc=tld';

#Specify attribute in LDAP, which will be used as group provider.
#You should add values from this attribute do dasboard "AD group"
#section, to allow LDAP users to login.
$LDAP_attribute_name='objectClass';
#$group_dn is used when you need to specify different base dn
#to list domain groups. If commented out, $base_dn will be used.
#(Active Directory only).
#$group_dn='CN=Users,DC=domain,DC=tld';
############################################################



##################Hypervisor config#########################
#Folder, where sreenshots will be stored (on hypervisor side).
#This folder must exist:
$temp_folder='/tmp';
#$backend_pass must match "password" option in [server] section
#in /usr/local/VDI/config file on hypervisor side:
$backend_pass='12345';
$ssh_user='VDI';
$ssh_key_path='/var/hyper_keys/';
$hypervisor_cmdline_path='/usr/local/VDI/';
$default_bridge='br0';
$default_imagepath='/data';
#Path, where ISO install images are located (hypervisor side):
$default_iso_path='/var/lib/libvirt/images';
$libvirt_user='root'; //user, on which libvirtd daemon runs
$libvirt_group='root'; //group, on which libvirtd daemon runs
############################################################


####################Database config#########################
$mysql_host='localhost';
$mysql_db='vdi';
$mysql_user='vdi';
$mysql_pass='vdi';
############################################################

$engine='KVM';

**Comment by ahmedgc01** [comment]
####################Database config#########################
$mysql_host='localhost';
$mysql_db='vdi';
$mysql_user='vdi';
$mysql_pass='vdi';
############################################################

**Comment by ahmedgc01** [comment]
###################Dashboard config##########################
$serviceurl='http://localhost/kvm-vdi';
$language='en_EN';
#define salt string, which will be used to generate passwords.
$salt='SecretString';
#write debug log to web server error.log file.
$write_debug_log=false;
#Websockify server address (if using HTML5 client)
$websockets_address='192.168.0.20';

**Comment by Seitanas** [comment]
Check if db was populated by kvm-vdi installation:
`mysql -u vdi -p`
`use vdi;`
`select * from users;`

**Comment by ahmedgc01** [comment]
mysql> use vdi;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from users;
Empty set (0.00 sec)

**Comment by Seitanas** [comment]
Try dropping all tables from vdi database, then load to kvm-vdi dashboard page.
You should see installation page there.

**Comment by ahmedgc01** [comment]
The below is the output , shall i remove all listed tables in vdi database .?
mysql> use vdi;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> SHOW TABLES;
+---------------+
| Tables_in_vdi |
+---------------+
| ad_groups     |
| clients       |
| config        |
| hypervisors   |
| log           |
| pool          |
| poolmap       |
| poolmap_ad    |
| poolmap_vm    |
| users         |
| vms           |
+---------------+
11 rows in set (0.00 sec)

**Comment by nerijus** [comment]
Which part of "Try dropping all tables from vdi database" you didn't understand?

**Comment by ahmedgc01** [comment]
Anyhow after deleting all tables from vdi database , the webpage looks like this  
                                                      KVM-VDI Installation
                                                       Info: Populating database.
                      Incorrect datetime value: '0000-00-00 00:00:00' for column 'lastlogin' at row 1

**Comment by ahmedgc01** [comment]
But after refreshing page the same browser page, it's populating `with credential . Still no success after giving credential .

































































































`

**Comment by ahmedgc01** [comment]
Thanks everyone, 

After deleting tables from database "vdi" mysql . dashboard is populating and credential "admin" and "password" are working .
