### ISSUE TITLE
hypervisor installation 

### ISSUE THREAD

**Issue by ahmedgc01** [Seitanas/kvm-vdi#117]
Hi, 
I have couple of questions . 
First, I'm installing hypervisor but after following commands ssh keyben t rsa ,there is no /home/VDI/.ssh . It has only /home/VDI with exampls file only.
In addition, there is no hyper_keys folder at directory /var
 I wonder If you could help me. Thanks
[On dashboard server type:

su VDI
cd
ssh-keygen -t rsa

copy files from /home/VDI/.ssh to /var/hyper_keys folder]

**Comment by Seitanas** [comment]
`ls -la /home/VDI`
is there no .ssh folder there?

**Comment by ahmedgc01** [comment]
It has on command line but does not show on folder where i want to copy all files manually rather than via commands .
furthermore destination folder does not exit means /var/hyper_keys  .

**Comment by ahmedgc01** [comment]
VDI@ubuntumachine:/var$ ls -la /home/VDI
total 40
drwxrwxrwx 3 VDI  VDI  4096 Jun 23 00:46 .
drwxrwxrwx 5 root root 4096 Jun 23 00:27 ..
-rw------- 1 VDI  VDI   183 Jun 23 00:53 .bash_history
-rw-r--r-- 1 VDI  VDI   220 Sep  1  2015 .bash_logout
-rw-r--r-- 1 VDI  VDI  3771 Sep  1  2015 .bashrc
-rwxrwxrwx 1 VDI  VDI  8980 Apr 20  2016 examples.desktop
-rw-r--r-- 1 VDI  VDI   655 May 16  2017 .profile
drwx------ 2 VDI  VDI  4096 Jun 23 00:27 .ssh

**Comment by Seitanas** [comment]
`drwx------ 2 VDI VDI 4096 Jun 23 00:27 .ssh`
so it does exist.
You should read up more on Linux before trying to install KVM-VDI.

**Comment by ahmedgc01** [comment]
thanks for reply.I'm reading it thoroughly . 
my question is why i can not see all files at /home directory. I know in command line that exit. secondly 
there is no folder hyper_key at /var directory

**Comment by Seitanas** [comment]
`mkdir  /var/hyper_keys` as stated in wiki

**Comment by ahmedgc01** [comment]
thanks . In following step , shall i write name of file or just hit enter . 
  ssh-keygen -t rsa
Generating public/private rsa key pair.
Enter file in which to save the key (/home/VDI/.ssh/id_rsa):

**Comment by ahmedgc01** [comment]
thanks . In following step , shall i write name of file or just hit enter . 
  ssh-keygen -t rsa
Generating public/private rsa key pair.
Enter file in which to save the key (/home/VDI/.ssh/id_rsa):

**Comment by ahmedgc01** [comment]
Hi, 
I'm encountering problem of hypervisor , I'm unable to connect hypervisor connection via ssh . I'm wonder if somebody guide me in this regard. The following is output when i connect to hypervisor at my local host (hypervisor's address is localhost where dashboard is also configured ). Thanks. 

root@ubuntumachine:/home/VDI/.ssh# ls
authorized_keys  id_rsa  id_rsa.pub
root@ubuntumachine:/home/VDI/.ssh# ls -l
total 12
drwxr-xr-x 2 root root 4096 Jun 23 03:07 authorized_keys
-rw------- 1 VDI  VDI  1679 Jun 23 02:27 id_rsa
-rw-r--r-- 1 VDI  VDI   399 Jun 23 02:27 id_rsa.pub
root@ubuntumachine:/home/VDI/.ssh# ssh -i /var/hyper_keys/id_rsa VDI@localhost
VDI@localhost's password: 
Permission denied, please try again.
VDI@localhost's password: 
Permission denied, please try again.
VDI@localhost's password: 
Permission denied (publickey,password).
root@ubuntumachine:/home/VDI/.ssh#

**Comment by Seitanas** [comment]
Show me the output of:

- `ls -la /home/VDI/.ssh`
- `ssh -i /var/hyper_keys/id_rsa VDI@localhost; tail /var/log/auth.log`

**Comment by ahmedgc01** [comment]
i just saw , anyhow problem solved , solution of this problem in mentioned in other issue-ticket 118 

by adding VDI ALL=(ALL:ALL) NOPASSWD:ALL at path dir /etc/sudoers.d/VDI
