### ISSUE TITLE
Unable to add hypervisor , VDI can't connect to hypervisor

### ISSUE THREAD

**Issue by ahmedgc01** [Seitanas/kvm-vdi#118]
I was trying to fix this below issue but in vain . I spent many hours on it but no success.I wonder if anyone could look at the following commands and pin out the problem where it has happened . What I understand is there is some problem with the VDI user related to its permission . Although I followed all this kvm-vdi guide in hypervisor installation, read also old issue in this blog but in vain . 
Sorry if any , i have lack  of Linux knowledge .

ssh-copy-id -i /var/hyper_keys/id_rsa.pub VDI@localhost/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/var/hyper_keys/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
VDI@localhost's password: 
Permission denied, please try again.
VDI@localhost's password: 
Permission denied, please try again.
VDI@localhost's password: 
Permission denied (publickey,password).

**Comment by Seitanas** [comment]
You are not following wiki.
`copy files from /home/VDI/.ssh to /var/hyper_keys folder.`
`cp /home/VDI/.ssh/* /var/hyper_keys`

**Comment by ahmedgc01** [comment]
Thanks for reply Seitanas . I'm grateful to you. 
I read instruction very carefully mentioned on wiki , i don't know why I could not do that . below is details of commands .I know there's problem with the public key ,however i did exctly to the wiki instruciton. I wonder if you could guide me . really appreciated . 
VDI@ubuntumachine:~/.ssh$ ls
id_rsa  id_rsa.pub  known_hosts
VDI@ubuntumachine:~/.ssh$ cd /var/hyper_keys/
VDI@ubuntumachine:/var/hyper_keys$ ls
authorized_keys  known_hosts
VDI@ubuntumachine:/var/hyper_keys$ 
VDI@ubuntumachine:/var/hyper_keys$ 
VDI@ubuntumachine:/var/hyper_keys$ ssh @localhost
usage: ssh [-1246AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]
VDI@ubuntumachine:/var/hyper_keys$ ssh VDI@localhost
Permission denied (publickey).
VDI@ubuntumachine:/var/hyper_keys$

**Comment by ahmedgc01** [comment]
Issue resolved:- Instead of putting lthis entry VDI ALL=(ALL:ALL) NOPASSWD:ALL here /etc/sudoers, I putt here:- /etc/sudoers.d/VDI
:) by Imran .great job done .
