### ISSUE TITLE
NO Option of Mount CD ISO in hypervisor.

### ISSUE THREAD

**Issue by ahmedgc01** [Seitanas/kvm-vdi#120]
Hi Everyone,

I've installed recently hypervisor on dashboard(machine is Linux Ubuntu 16.04 Server) . when I try to create virtual machine on hypervisor, there is no option of Mount CD ISO . Any solution of the problem . really appreciated . 

Thanks .

**Comment by Seitanas** [comment]
Yes, there is:
https://www.youtube.com/watch?v=WjZTVhHk6ZA&t=18s

**Comment by ahmedgc01** [comment]
Thanks for reply . I checked it there is no details about this issue . 
What i did , I created folder at /data but there is no drop down list of "Mount CD ISO "from  i want to select iso image of OS that i have placed at somewhere at path /home/documents . can you guide me where is problem . I'm unable to create VM machine .

**Comment by Max-bazinga** [comment]
If you do not set the ISO path in config file, the default ISO store path is  /var/lib/libvirt/images, which is the default path of libvirt. You can put your iso image in this path, than you will see images in drop down list.

**Comment by ahmedgc01** [comment]
Thanks Max -Bazinga . 
It did work . you are great .
