### ISSUE TITLE
GLIB-GIO-CRITICAL

### ISSUE THREAD

**Issue by Dmitry5755** [Seitanas/kvm-vdi#125]
Hello,
I tried to run /usr /local/VDI-client/kvm-vdi-client on ubuntu bionic.
The virtual machine startup window appears and I do not find any external work problems on it. But the error appears on the command line:
GLIB-GIO-CRITICAL g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION ...
This is critical, given that the installation used the python-webkit package from previous versions?

**Comment by Seitanas** [comment]
If it does work, then it should be no problems.
Python is just a wrapper here, so errors must be produced by `remote-viewer`.

**Comment by Dmitry5755** [comment]
so this is a virt-viewer error?
It seems to me it is correctly established and works while I did not observe any problems.

**Comment by Seitanas** [comment]
Its probably x-window layer warning caused by remote-viewer. You should ignore this.

**Comment by Dmitry5755** [comment]
Ok, thank you very much
