### ISSUE TITLE
Questions: automatic drive share,google cloud intergeration, admin rights and load balancing 

### ISSUE THREAD

**Issue by ahmedgc01** [Seitanas/kvm-vdi#126]
Hi Everyone, 

can we automatically share drive for clients. ?
Secondly, can clients personalize their setting .?
can we integerate kvm-vdi with google cloud ?
can administrator access VDI machines?
where virtual snapshots are stored . ? Is snapshot created after client's logout ?
How we use let's say three servers for load balancing in KVM-VDI project.
Thanks.

**Comment by Seitanas** [comment]
- Drive sharing is out of scope of this project - you should decide processes, how and what to share (CIFS/NFS/Cloud storage) and implement that in your golden images (`Initial machines`). Clients will get those shares when they launch their VDI instances.
- This is also out of scope of this project. You should decide, how to configure personalization on your side (e.g. windows domain/active directory if using Windows).
- No, it is just for using KVM hypervisors. Openstack integration is coming also.
- There are multiple types of snapshots used in KVM-VDI. VM snapshots are stored in: https://github.com/Seitanas/kvm-vdi/blob/31dafea7a7e22bacf93c78f7380b334415a2a4ed/functions/config.php_kvm#L94 unless configured differently, when creating `Initial machine`/`VDI machine`. `VDI machines` also store temporary snapshots. These are deleted as soon as `VDI machine` is powered off and are defined in:
https://github.com/Seitanas/kvm-vdi/blob/a6a40b6df72cf9bf3a0d60769a0cea6cd9beed1e/KVM/hypervisors/config#L6
- Load balancing is done in `RoundRobin` style. When you add new hypervisor, it will be used in `KVM-VDI` to balance load of the first hypervisor.

**Comment by ahmedgc01** [comment]
Thanks very much for the  clarity.
