### ISSUE TITLE
kvm-vdi solution integration with google Compute Engine using Cloud Endure

### ISSUE THREAD

**Issue by ahmedgc01** [Seitanas/kvm-vdi#127]
Hi , 

sorry, I mentioned this question in previous issue and got answer. That was , It is not possible to integrate with google cloud. 
Today, I came across google website (https://cloud.google.com/compute/docs/vm-migration/using-cloud-endure) where it is possible to migrate VM ( this is server machine and has kvm-vdi solution installed) to google compute Engine for ubutnu vm  . Is there chance to deploy our Kvm-Vdi vm server on google cloud.
Thanks.

**Comment by Seitanas** [comment]
Migrating virtual machine to cloud service is not the same as having VDI solution on different cloud/virtualisation platform.
Even if you can migrate KVM VM to Google Cloud, does not mean that you can integrate KVM-VDI with Google Cloud.
