### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by wanabnux** [Seitanas/kvm-vdi#131]
Hi,

Installing on Centos 7.  Can't get Dashboard to open.  "Edit config.php to fit your needs" - this part is not so easy for someone new to linux like myself.  Can you add a sample working config.php example?  Otherwise, there are too many topics to learn to be able to correctly modify config.php file.

**Comment by Seitanas** [comment]
Hello,
config.php should be self-explanatory. Basically it should work out of the box, - you should only configure DB settings.

**Comment by wanabnux** [comment]
Thank you for the quick reply, Todas.

I have never worked with any db before.  That's why I'm having issues.  I
have nothing running except kvm-dvi.  Can you send me a sample Mariadb
setup to get the Dashboard working?  Right now, I just get blank screen
likley stuck looking for correct db info.  I can get to display info.php
from another example, so everything is installed correctly.

Also, I have changed ip address for $serviceurl='http://192.168.0.20/kvm-vdi',
$websockets_address='192.168.0.20' , $LDAP_host='192.168.0.20'.  Anything
else needs to be changed?  I already spent over a week reading php and
mariadb and getting nowhere.   Thank you very much.

Charles Lee

**Comment by wanabnux** [comment]
Hi Todas,


""

Create empty database/user on db server.

cd /var/www/html/
git clone https://github.com/Seitanas/kvm-vdi
cd kvm-vdi

""


I'm assuming the above section creates the db.  So, what do I need to do for
" you should only configure DB settings."


""
Rename functions/config.php_dist to functions/config.php Edit config.php to
fit your needs.
Go to http://yourservename/kvm-vdi

""

All I did here is change the ip addresses in the config.php.  And login
page is not coming up.

Thanks.


Charles


<clee@vvsst.com>

**Comment by wanabnux** [comment]
Got it.  Thank you a bunch.

Charles Lee
clee@vvsst.com
Dir Ph: 404.483.3698
www.vvsst.com

**Comment by wanabnux** [comment]
Hi Todas,

A basic question again.

I managed to get to Copy all files from "KVM/hypervisors/" folder --- where
do I find this folder?

I'm using single KVM hypervisor on Centos 7 & a VM on it running Ubuntu for
Dashboard.

Thank you very much for your help.

Charles Lee


<clee@vvsst.com>

**Comment by wanabnux** [comment]
Do you mean to copy entire directory/file of the hypervisor to
/usr/local/VDI folder?

**Comment by wanabnux** [comment]
I see.  these files...

/var/www/html/kvm-vdi/KVM/hypervisors/

Thanks.

**Comment by wanabnux** [comment]
Hi Todas,

This is more relevant question.

After installations of "Dashboard service" and "Hypervisor" should you be
able to see a "Target hypervisor" from the "Create virtual machine(s)" drop
down menu?  I completed the first two steps and see no hypervisor to choose
from "Target hypervisor:" drop down menu.  Do I need to complete all 5
steps before I can see hypervisor options?  Thanks.
