### ISSUE TITLE
copy-n-paste

### ISSUE THREAD

**Issue by Dmitry5755** [Seitanas/kvm-vdi#133]
Hello!
I tried to copy and paste from a guest with the windows on linux client. But I did not succeed. All that I met about this did not cause controversy with my settings. Could you tell me what might be the problem?

**Comment by Seitanas** [comment]
Hello,
even if thia should work out-of-the-box, this is not a VDI concept.
VDI client is a thin-client with a thin OS that should not be used as main desktop solution.
So this is out of the scope of this project.

**Comment by Dmitry5755** [comment]
Thanks!
