### ISSUE TITLE
AD Sync Help

### ISSUE THREAD

**Issue by timbogues** [Seitanas/kvm-vdi#138]
Just a quick question. What do I need to put for this value from my domain? I think I'm just not interpreting correctly.

#Specify attribute in LDAP, which will be used as group provider.
#You should add values from this attribute do dasboard "AD group"
#section, to allow LDAP users to login.
$LDAP_attribute_name='objectClass';

**Comment by Seitanas** [comment]
You should specify attribute, which will define VDI users eg. `adminstrator`, `power user`, self defined `foobar` etc, and include those users to this  group.

**Comment by timbogues** [comment]
This is my full AD settings I put into config.php. I'm using Active Directory. Is this correct? I'm trying to add users located throughout my domain that are a member of TestVDIUsers group that will have access to log into the VDI Client portal, and log into one of the VDI machines in a pool I grant them access to on the admin side. 

####################Active Directory/LDAP logins#############
#please specify your LDAP backend:
$LDAP_backend='activedir';
#$LDAP_backend='ldap';
#Domain part to be added to username (only for Active Directory).
$domain_name='MYDOMAIN.LOCAL';
#Address of ACtive Directory/LDAP server.
$LDAP_host='172.16.0.30';
#Username and password to bind to LDAP server (not deeded by Active Directory):
#$LDAP_username='uid=USERNAME,ou=bind users,dc=domain,dc=tld';
#$LDAP_password='ldappassword';
#Base DN pattern:
$base_dn = 'DC=MYDOMAIN,DC=LOCAL';
#For LDAP backend you should specify base DN including username:
#$base_dn = 'uid=%username%,ou=people,dc=domain,dc=tld';

#Specify attribute in LDAP, which will be used as group provider.
#You should add values from this attribute do dasboard "AD group"
#section, to allow LDAP users to login.
$LDAP_attribute_name='group';
#$group_dn is used when you need to specify different base dn
#to list domain groups. If commented out, $base_dn will be used.
#(Active Directory only).
#$group_dn='CN=Users,DC=domain,DC=tld';
############################################################

**Comment by timbogues** [comment]
This is my full AD settings I put into config.php. I'm using Active Directory. Is this correct? I'm trying to add users located throughout my domain that are a member of TestVDIUsers group that will have access to log into the VDI Client portal, and log into one of the VDI machines in a pool I grant them access to on the admin side.

####################Active Directory/LDAP logins#############
#please specify your LDAP backend:
$LDAP_backend='activedir';
#$LDAP_backend='ldap';
#Domain part to be added to username (only for Active Directory).
$domain_name='MYDOMAIN.LOCAL';
#Address of ACtive Directory/LDAP server.
$LDAP_host='172.16.0.30';
#Username and password to bind to LDAP server (not deeded by Active Directory):
#$LDAP_username='uid=USERNAME,ou=bind users,dc=domain,dc=tld';
#$LDAP_password='ldappassword';
#Base DN pattern:
$base_dn = 'DC=MYDOMAIN,DC=LOCAL';
#For LDAP backend you should specify base DN including username:
#$base_dn = 'uid=%username%,ou=people,dc=domain,dc=tld';

#Specify attribute in LDAP, which will be used as group provider.
#You should add values from this attribute do dasboard "AD group"
#section, to allow LDAP users to login.
$LDAP_attribute_name='group';
#$group_dn is used when you need to specify different base dn
#to list domain groups. If commented out, $base_dn will be used.
#(Active Directory only).
#$group_dn='CN=Users,DC=domain,DC=tld';
############################################################

**Comment by Seitanas** [comment]
Seems legit,
should work with:
`$LDAP_attribute_name='TestVDIUsers';`

**Comment by timbogues** [comment]
I did that, and it still won't let my AD user in that group log into the client area. And, I did add it in the admin dashboard under Add AD Group and added the group to a pool.

Thank you!

**Comment by Seitanas** [comment]
Then perhaps you need to use `$group_dn` pattern to get correct grouplist.

**Comment by timbogues** [comment]
$group_dn pattern is referring to the location of the AD Group I specified for $LDAP_attribute_name (which I put 'Test VDI Users' for) correct? Cause, I tried setting that too.

**Comment by timbogues** [comment]
I've tried everything, and no matter what when I try to log into the client area of KVM-VDI using the user I added to the Test VDI Users security group I get the following error:
![image](https://user-images.githubusercontent.com/10507621/47926894-375c6f00-de98-11e8-84c3-198b6b4f33a7.png)

**Comment by timbogues** [comment]
After further testing, I think the server is imply not communicating over LDAP. I may end up just spinning up a new KVM-VDI server since this initial one was for just testing it out.

Thank you for your help!

**Comment by Seitanas** [comment]
You can enable debug logging. This will provide some more information on the problem:

https://github.com/Seitanas/kvm-vdi/blob/a6a40b6df72cf9bf3a0d60769a0cea6cd9beed1e/functions/config.php_kvm#L21

**Comment by timbogues** [comment]
Is there a way to add multiple AD groups to KVM-VDI? What do I have to do specifically in the config.php file?

**Comment by Seitanas** [comment]
No, there is no.

**Comment by timbogues** [comment]
So, what if I had two pools and wanted to give different people access to one pool vs the other...would that not work?

**Comment by Seitanas** [comment]
To clarify this: there is no way to add two different search points. You will have to struct your search string to list all groups for user. After that you can add AD groups via dashboard and define vdi pools for them as you like.

**Comment by timbogues** [comment]
Haven't touched this project in a bit, but I finally got around to building a new KVM-VDI Dashboard server, entered my AD settings, and enabled logging, and this is what I'm getting. Any suggestions?

[Mon Dec 10 12:11:23.252263 2018] [:error] [pid 1366] [client 172.31.255.10:60478] PHP Warning:  ldap_search(): Search: Operations error in /var/www/html/kvm-vdi/functions/functions.php on line 193, referer$
[Mon Dec 10 12:11:23.252312 2018] [:error] [pid 1366] [client 172.31.255.10:60478] PHP Warning:  ldap_get_entries() expects parameter 2 to be resource, boolean given in /var/www/html/kvm-vdi/functions/funct$
[Mon Dec 10 12:11:23.256940 2018] [:error] [pid 1366] [client 172.31.255.10:60478] Groups for user@DOMAIN.LOCAL: , referer: http://vdi.company.com/kvm-vdi/client_index.php

**Comment by timbogues** [comment]
I figured out what the problem is. When I set the Base DN to the root of the domain (AKA DC=DOMAIN, DC=LOCAL), it won't search for some reason...only works when I include an OU. However, this is a problem because that won't cover all users that will need access. Is there any way for my Base DN to be the root of the domain and NOT have to be an OU beneath?

**Comment by timbogues** [comment]
I was able to figure it out myself by modifying your functions file to search multiple "base_dn's", so I'm all set!
