### ISSUE TITLE
VDI Client Error & HTML5 auto sizing not working

### ISSUE THREAD

**Issue by emmanualvnebu** [Seitanas/kvm-vdi#142]
Hi,

I got everything setup & working except 2.

1. VDI client doesn't go beyond pool screen.
2. HTML5 does not auto size window according to the VM resolution.

When I try to access VDI client, gives the login page. Post login it shows VM in the pool. However, when I click on the VM nothing happens. In terminal I get below message.

"Traceback (most recent call last):
  File "./kvm-vdi-client", line 198, in pool_click
    if not v.get_title():
AttributeError: 'webkit.WebView' object has no attribute 'get_title'"
![image](https://user-images.githubusercontent.com/43741760/48671158-27a48200-eb4a-11e8-975f-86947be5d460.png)
![image](https://user-images.githubusercontent.com/43741760/48671161-31c68080-eb4a-11e8-9ed5-663bd114020d.png)

When I access the VM through HTML5, it boots up. However, auto sizing is not happening.

OS - WINSERVER 2K12-R2
QXL graphics driver installed.
![image](https://user-images.githubusercontent.com/43741760/48671281-bfef3680-eb4b-11e8-83f6-3c47a7cc5a91.png)

![image](https://user-images.githubusercontent.com/43741760/48671288-e2814f80-eb4b-11e8-97c0-4c4ff3c968f1.png)

Am I missing something?

**Comment by Seitanas** [comment]
You should also install spice-client into guest machine

**Comment by emmanualvnebu** [comment]
spice-vdagent service not working due to spice-vdagent.socket is not able to start. Dependency /dev/virtio is missing.

Am I missing some module/packages?

**Comment by emmanualvnebu** [comment]
This is fixed by installing guest-agent on windows guest.

https://www.spice-space.org/download.html
