### ISSUE TITLE
VDI Agent Won't Start

### ISSUE THREAD

**Issue by timbogues** [Seitanas/kvm-vdi#144]
I followed your directions 100%, but the VDI host agent will not start. I get the following error:
● vdi-agent.service - KVM-VDI agent
   Loaded: loaded (/etc/systemd/system/vdi-agent.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2018-12-17 10:42:30 EST; 2s ago
  Process: 26014 ExecStart=/usr/local/VDI/vdi-agent (code=exited, status=203/EXEC)
 Main PID: 26014 (code=exited, status=203/EXEC)

Dec 17 10:42:30 BPS-KVM-TEST systemd[1]: vdi-agent.service: Unit entered failed state.
Dec 17 10:42:30 BPS-KVM-TEST systemd[1]: vdi-agent.service: Failed with result 'exit-code'.

Assistance would be greatly appreciated!

**Comment by Seitanas** [comment]
Try running vdi-agent directly to see error output..

**Comment by timbogues** [comment]
Do I just type vdi-agent and hit enter or something else?

**Comment by Seitanas** [comment]
Running `/usr/local/VDI/vdi-agent` should be enough

**Comment by timbogues** [comment]
Gives me this:
sudo: /usr/local/VDI/vdi-agent: command not found

**Comment by Seitanas** [comment]
So there's your problem.

**Comment by timbogues** [comment]
Yeah, but the file is there, so I'm not sure why it won't run...

**Comment by timbogues** [comment]
Never mind. I believe it was a permissions issue. Thanks for your help!
