### ISSUE TITLE
HTML5 Console

### ISSUE THREAD

**Issue by timbogues** [Seitanas/kvm-vdi#145]
I'm trying to get the HTML5 console to work, but comes up as black blank screen no matter what. I already tried running ./run --token-plugin TokenFile --token-source /tmp/kvm-vdi 5959 with no --daemon, and get the following error:

172.16.240.181: SSL connection but '/var/www/html/kvm-vdi/websockify/self.pem' not found

Upon seeing this, I did go and change the value in run.js file in spice_html5 folder from wss to ws, but still no luck.

Any suggestions? Not sure why it is still looking for the .pem file when it should be running now in HTTP mode (not HTTPS)?

**Comment by Seitanas** [comment]
In order to run non-https websocket service, your dashboard should also be running on http.

**Comment by timbogues** [comment]
The dashboard is running on HTTP...is there something special I need to change with the dashboard? Did a basic install following all the steps and never said anything about changing something with the dashboard?

**Comment by timbogues** [comment]
Just checked my settings again, and I do not have anything pointing to HTTPS at all...

**Comment by timbogues** [comment]
And...now its working out of the blue...very strange...I'll keep monitoring and close out later on if issue does not come back...

**Comment by timbogues** [comment]
Resolving since working fine.
