### ISSUE TITLE
KVM-VDI client: No responds post login

### ISSUE THREAD

**Issue by emmanualvnebu** [Seitanas/kvm-vdi#148]
Hi,

HTML5 & virt viewer it's working fine (Centos).

However, when tried in kvm-vdi client, post login it give below screen.
![image](https://user-images.githubusercontent.com/43741760/52916518-870b5d00-3306-11e9-81f5-f0ac981006cb.png)

But when I click on that it loads for 2 seconds & back to the same screen.
VM is also not starting.

![image](https://user-images.githubusercontent.com/43741760/52916528-ae622a00-3306-11e9-8aa6-34b14f6b4956.png)

**Comment by Seitanas** [comment]
Launch client from console and look at its output (stdout/stderr)

**Comment by emmanualvnebu** [comment]
![image](https://user-images.githubusercontent.com/43741760/52967144-285de600-33cf-11e9-9e34-afc3a634896b.png)

Nothing else other than above..

**Comment by sskras** [comment]
And what is the final resolution?
