### ISSUE TITLE
How do you create a pool?

### ISSUE THREAD

**Issue by jphein** [Seitanas/kvm-vdi#15]
Is it configured in clients.xml?

```

 <!--
     <client ip="192.168.1.2">
    <protocol>vmView</protocol>
    <pool>Users</pool>
     </client>
```

**Comment by Seitanas** [comment]
This is VMware Horizon VDI pool. KVM-VDI has a failover capability to use VMware horizon, if available. 

http://pubs.vmware.com/horizonmirage-43/index.jsp?topic=%2Fcom.vmware.horizonmirage.interoperability.doc%2FGUID-5110580F-3AE9-4161-9853-97294DE72529.html

For most installments it is not used.

**Comment by jphein** [comment]
I see, is there anyway to point a client to a KVM-VDI pool? I don't want to map the clients to a specific VM.

**Comment by jphein** [comment]
I guess DHCP works pretty well for that. =]

**Comment by Seitanas** [comment]
No, currently there is no easy way to detect which of VDI VM is already used by SPICE client, so you have to hard-wire each client to its VDI VM
