### ISSUE TITLE
AD Issue

### ISSUE THREAD

**Issue by emmanualvnebu** [Seitanas/kvm-vdi#152]
Hi,

I am trying to link AD with this. However AD user is unable to login.

I have Dashboard, Hypervisor & WIN2K12 in different VMs.

If I create a client through dashboard, it works fine. But when I am trying to login with a AD user it's not.

Below is my AD config.

> #please specify your LDAP backend:
> $LDAP_backend='activedir';
> #$LDAP_backend='ldap';
> #Domain part to be added to username (only for Active Directory).
> $domain_name='vdi.local';
> #Address of ACtive Directory/LDAP server.
> $LDAP_host='192.168.0.135';
> #Username and password to bind to LDAP server (not deeded by Active Directory):
> #$LDAP_username='uid=USERNAME,ou=bind users,dc=domain,dc=tld';
> #$LDAP_password='ldappassword';
> #Base DN pattern:
> $base_dn = 'DC=vdi,DC=local';
> #For LDAP backend you should specify base DN including username:
> #$base_dn = 'uid=%username%,ou=people,dc=domain,dc=tld';
> #Specify attribute in LDAP, which will be used as group provider.
> #You should add values from this attribute do dasboard "AD group"
> #section, to allow LDAP users to login.
> $LDAP_attribute_name='Vdi';
> #$group_dn is used when you need to specify different base dn
> #to list domain groups. If commented out, $base_dn will be used.
> #(Active Directory only).
> #$group_dn='CN=Users,DC=vdi,DC=local';

**AD Group = Vdi
Domain	= vdi.local**

Below is the error logged:

_[Sun Mar 03 21:50:50.293504 2019] [php7:error] [pid 3760] [client 192.168.0.176:26946] PHP Fatal error:  Uncaught Error: Call to undefined function ldap_connect() in /var/www/html/vdi/functions/functions.php:179\nStack trace:\n#0 /var/www/html/vdi/client_pools.php(44): list_ad_groups('test', 'test@1', 'test@vdi.local', 1)\n#1 {main}\n  thrown in /var/www/html/vdi/functions/functions.php on line 179, referer: https://192.168.0.124/vdi/client_index.php_

Can you please help?

**Comment by Seitanas** [comment]
`Uncaught Error: Call to undefined function ldap_connect()`
You should install `php-ldap` libary.

**Comment by emmanualvnebu** [comment]
That worked.
