### ISSUE TITLE
Logout Button in VDI thin client?

### ISSUE THREAD

**Issue by emmanualvnebu** [Seitanas/kvm-vdi#153]
Any option to get Logout Button in VDI thin client?

**Comment by Seitanas** [comment]
You can enable `autoexit` option in thin client config:
https://github.com/Seitanas/kvm-vdi/blob/a6a40b6df72cf9bf3a0d60769a0cea6cd9beed1e/thin_clients/config#L12
this will automatically close thin client, when machine is powered off.

**Comment by emmanualvnebu** [comment]
Thanks, it worked.. Just an out of the box question, any option the client will exit when guest is logged off?

**Comment by Seitanas** [comment]
Easy enough to implement, - just override logout on guest machine to shut down it instead (easily doable on windows and Linux)
