### ISSUE TITLE
WIN 2K12 VDI boots up, but stuck at black screen

### ISSUE THREAD

**Issue by emmanualvnebu** [Seitanas/kvm-vdi#154]
Hi,

I am using thin client to boot to WIN2K12 VDI.

Most of the time when the VDI is turned on it shows the WIN logo & then get stuck on a black screen. I have to force shutdown it & start it again.

It's happening in even virtual snap also. Is there a fix to it?

**Comment by nyist1** [comment]
Are there any specific steps?

**Comment by Seitanas** [comment]
hello, this is not directly related to `kvm-vdi` but to qemu+win2012 itself.
Windows 2012 does not load Redhat QXL video driver by default.
The workaround could be to run VM with Cirrus video card, preinstall Redhat QXL drivers and change Video card afterwards.

Or create Windows 2012 install iso with preloaded QXL drivers.

**Comment by emmanualvnebu** [comment]
Hello,
OS was install in the source machine with virtio drivers in below order.

Balloon 
NetKVM
vioserial
QXL
viostor

Once up, install spice-guest for windows & did sdelete. shutdown the VM & created initial machine & from initial machines created VDIs.

This is not happening always, it's happening 7times out of 10.  Will doing windows update on source machine helps?

Also, If I am not using Open stack,  should I configure Compute nodes for vdi wrapper & install nova-compute?. I believe it's already there. I don't have it setup, I mean if I check virsh capabilities, qemu is not running from /usr/local/VDI.

Could that be the problem?

**Comment by ryand32** [comment]
Seitanas,

Any updates for using vGPU using Grid for Nvidia or AMD Radeon Pro cards
using KVM-VDI?

Ryan

**Comment by Seitanas** [comment]
Since `KVM-VDI` is heavily based on `QEMU-KVM`, there will be no `GRID` support till `QEMU-KVM` adds support for this technology :)

**Comment by emmanualvnebu** [comment]
Tried with WIN2K12 iso preloaded with qxldod driver. Still the issue persist. Any suggestion?

**Comment by Seitanas** [comment]
Perhaps you should try to install windows 2012 on plain qemu-kvm to see what happens.

**Comment by emmanualvnebu** [comment]
I think I figured it out, it was an issue with the OS version. Downloaded latest iso & that fixed it. Thanks.
