### ISSUE TITLE
SSO through thin client not working when user logging in to VDI for first time.

### ISSUE THREAD

**Issue by emmanualvnebu** [Seitanas/kvm-vdi#155]
This is regarding SSO.

Authentication done through AD server. There are 10 VDIs & 10 users.

It seems SSO through thin client works only if the user already had logged in to the machine at least once. 

When the user is logging in to the VDI for the first time, SSO seems not working, user has to manually enter the credentials. This becomes impossible when using WIN 10, 2K16 etc...

Is there any way to fix this? I mean an option to have custom pool along with AD group?

**Comment by Seitanas** [comment]
This should not happen. Even first login attempt should succeed. Perhaps `oVirtGuestService` is not running on guest machine?

**Comment by ryand32** [comment]
Seitanas

Any plan for horizon / Citrix?

Ryan
