### ISSUE TITLE
Screen hangs at populating database on Ubuntu 16.04. 

### ISSUE THREAD

**Issue by jphein** [Seitanas/kvm-vdi#17]
![screenshot from 2016-05-13 10-21-51](https://cloud.githubusercontent.com/assets/19301265/15256068/8c5c801a-18f4-11e6-91c3-94338f8e510a.png)

> [Fri May 13 10:20:42.108440 2016] [:error] [pid 9341] [client 192.168.11.1:37482] PHP Notice:  Undefined variable: query_array in /var/www/html/kvm-vdi/functions/functions.php on line 36
> [Fri May 13 10:20:42.118156 2016] [:error] [pid 9341] [client 192.168.11.1:37482] PHP Notice:  Undefined variable: query_array in /var/www/html/kvm-vdi/functions/functions.php on line 36
> [Fri May 13 10:20:42.171943 2016] [:error] [pid 9341] [client 192.168.11.1:37482] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_close() in /var/www/html/kvm-vdi/functions/functions.php:140\nStack trace:\n#0 /var/www/html/kvm-vdi/install/index.php(59): populate_db()\n#1 {main}\n  thrown in /var/www/html/kvm-vdi/functions/functions.php on line 140

If I go to the login screen:

> [Fri May 13 10:22:27.772641 2016] [:error] [pid 10397] [client 192.168.11.1:37514] PHP Notice:  Undefined index: error in /var/www/html/kvm-vdi/index.php on line 43
> [Fri May 13 10:22:29.056737 2016] [:error] [pid 9756] [client 192.168.11.1:37518] PHP Warning:  hash_equals(): Expected known_string to be a string, null given in /var/www/html/kvm-vdi/login.php on line 7, referer: http://192.168.11.1/kvm-vdi/

![screenshot from 2016-05-13 10-22-37](https://cloud.githubusercontent.com/assets/19301265/15256095/bb7f1baa-18f4-11e6-89b4-bfbb6521b4c8.png)

**Comment by Seitanas** [comment]
This looks like you are missing php-mysql plugin, or you have not restarted apache (or php-cgi, php-fpm depends, what you use) after installing it.

**Comment by Seitanas** [comment]
I have no idea, how i've managed to overlook that
