### ISSUE TITLE
Assigns "Source image" to Simple and Source machines randomly

### ISSUE THREAD

**Issue by jphein** [Seitanas/kvm-vdi#18]
![screenshot from 2016-05-13 10-52-46](https://cloud.githubusercontent.com/assets/19301265/15256951/db8acd32-18f8-11e6-9350-8349181143cf.png)

**Comment by Seitanas** [comment]
Could you please define steps you do on which random assingns occur? there were loads of commits during this day, did you update your dashboard and hypervisor executables? I cant reproduce this on 15.10. will try to do this on 16

**Comment by jphein** [comment]
Yes, everything is updated. When I log into a fresh KVM-VDI, none of my machines are assigned.

Then I start assigning them. As soon as I assign a Source or Simple machine it applies a source image string. 

It doesn't affect functionality.
