### ISSUE TITLE
Does not install in Ubuntu 15.10 wily AMD64 

### ISSUE THREAD

**Issue by jphein** [Seitanas/kvm-vdi#2]
I have followed all steps in the Readme file here: [](https://github.com/Seitanas/kvm-vdi)

The readme and the hypervisors/sudoers file have different example content.
Which one should I use?

In Ubuntu 15.10 wily many of the packages were not available, but we can install other packages:
`apt-get install mariadb-server apache2 php git libapache2-mod-php php-gettext php-ssh2`
did not work, but:
`apt-get install mariadb-server apache2 php5 git libapache2-mod-php5 php5-mbstring php-gettext php5-ssh2` seemed to work.

I could not find the php-mbstring anywhere. 
An additional package needed to be installed for mysqli:
`sudo apt-get install php5-mysql`

When I open http://localhost/vdi <-- the path of the dashboard. 

> Error while installing database
>  ~ or some such.

look into mariadb:

```
MariaDB [vdi]> show tables;
+---------------+
| Tables_in_vdi |
+---------------+
| hypervisors   |
| users         |
| vms           |
+---------------+
3 rows in set (0.01 sec)

MariaDB [vdi]> 
```

Error from apache2 error log when trying to install:

> [Tue May 10 21:30:27.962222 2016] [:error] [pid 15209] [client ::1:43628] PHP Warning:  mysqli_close() expects exactly 1 parameter, 0 given in /var/www/html/vdi/functions/functions.php on line 35
> [Tue May 10 21:30:38.707609 2016] [:error] [pid 15214] [client ::1:43638] PHP Warning:  mysqli_close() expects exactly 1 parameter, 0 given in /var/www/html/vdi/functions/functions.php on line 35
> [Tue May 10 21:30:38.707700 2016] [:error] [pid 15214] [client ::1:43638] PHP Notice:  Undefined index: error in /var/www/html/vdi/index.php on line 43
> [Tue May 10 21:30:44.413701 2016] [:error] [pid 15215] [client ::1:43640] PHP Warning:  mysqli_close() expects exactly 1 parameter, 0 given in /var/www/html/vdi/functions/functions.php on line 35

Readme says that:
Default credentials are: admin/password

These do not work for me. in the functions/config.php. there is a line 

> ###### ############Hypervisor config
> 
> $temp_folder='/data_tmp/tmp';
> $backend_pass='12345';

Is that the password? If so, what is the username? admin does not work.

**Comment by Seitanas** [comment]
Hello,
you should use content from hypervisors/sudoers (will change that in README file).
Also I've provided new sql scheme (sql/vdi.sql) you should replace it in your installment, drop all tables, and re-run install.

**Comment by jphein** [comment]
Works!!!

**Comment by jphein** [comment]
Thank you!
