### ISSUE TITLE
Merge my fork?

### ISSUE THREAD

**Issue by jphein** [Seitanas/kvm-vdi#20]
Hello,
I made changes to the LTSP script. I forked it then made changes. Can you merge them?

Also, there is an issue with the vdi script. my script deals with X, so I had to remove "startx" from the start of the commands in your vdi script <-- not sure the best way to resolve this. 

Also, have you heard of: http://www.foss-cloud.org/

**Comment by Seitanas** [comment]
Merged.
Also, i'm familiar with foss-cloud, but I do not see any positive perspectives in that. There are more robust solutions for a VDI-enabled services (like oVirt). Having said that, I see huge potential in OpenStack, so this year, after our team will finish its deployment, I will make KVM-VDI more module-alike and hopefully  we will  make this project use OpenStack VM pools.

**Comment by jphein** [comment]
Cool.

**Comment by ahmedkaballo** [comment]
Can i add ovirt host as hypervisor on KVM-VDI and then use the  machines created by ovirt ?
