### ISSUE TITLE
Please add Ubuntu 16.04 to list of Linux OS's

### ISSUE THREAD

**Issue by jphein** [Seitanas/kvm-vdi#25]
The only options are Ubuntu 13.10 and 12.04

**Comment by Seitanas** [comment]
This is a limitation, based on libvirt themplates and not on KVM-VDI, so the only thing I can suggest, - I can add `"Ubuntu 13.10 or higher"` (as it is on Debian)

**Comment by jphein** [comment]
Hahaha..cool. That would look better. =]
