### ISSUE TITLE
Progress bar is not working, and instance is stuck on

### ISSUE THREAD

**Issue by jphein** [Seitanas/kvm-vdi#26]
![screenshot from 2016-06-01 12-33-03](https://cloud.githubusercontent.com/assets/19301265/15722964/18fa64a6-27f5-11e6-9ef6-11989f0b781c.png)

**Comment by Seitanas** [comment]
May be permission problem on tmp/ folder. Could you please check if web server can write to tmp/ folder in KVM-VDI directory?

**Comment by Seitanas** [comment]
I've pushed new release in which tmp/ folder is no longer required. This should solve this problem. Please notice, that copy-file application on hypervisor side also needs to be updated.

**Comment by jphein** [comment]
Thanks! I've updated everything. My first VM still says it's running even though it isn't.

**Comment by Seitanas** [comment]
And force shutdown doesn't help?

**Comment by jphein** [comment]
no

## 

Jeffrey Pine Hein
Just plain helpful.
Technology consulting for nonprofits.
jphein.com http://www.jphein.com

## (530) 798-4099

jphein.com/blog <-- Check out my blog for daily updates on donations,
discounts, tech tips, and how to's. All geared toward people in nonprofits.

## To subscribe to my blog, use jphein.com/feed in your favorite feed reader.

jphein.com/helpdesk <-- Need support? Submit a trouble ticket at my help
desk.

I use Mailvelope http://mailvelope.com to encrypt and/or sign my
messages. If you would like to use secure email check it out. If you wish
to send me encrypted messages, my public key can be found @
jphein.com/pgp.pub.asc

**Comment by Seitanas** [comment]
what does `virsh list` on hypervisor side say?

**Comment by jphein** [comment]
virsh list

##  Id    Name                           State

## 

Jeffrey Pine Hein
Just plain helpful.
Technology consulting for nonprofits.
jphein.com http://www.jphein.com

## (530) 798-4099

jphein.com/blog <-- Check out my blog for daily updates on donations,
discounts, tech tips, and how to's. All geared toward people in nonprofits.

## To subscribe to my blog, use jphein.com/feed in your favorite feed reader.

jphein.com/helpdesk <-- Need support? Submit a trouble ticket at my help
desk.

I use Mailvelope http://mailvelope.com to encrypt and/or sign my
messages. If you would like to use secure email check it out. If you wish
to send me encrypted messages, my public key can be found @
jphein.com/pgp.pub.asc

**Comment by Seitanas** [comment]
does "boxen1" machine even exist? `virsh list --all`

**Comment by jphein** [comment]
Yes, it does.

virsh list --all

##  Id    Name                           State
-     boxen1                         shut off
-     f1                             shut off
-     f2                             shut off
-     freenas                        shut off
-     freenas-fresh                  shut off
-     golden1                        shut off
-     l1                             shut off
-     l2                             shut off
-     l3                             shut off
-     lubuntu                        shut off
-     lubuntu16.04                   shut off
-     PXE                            shut off
-     w1                             shut off
-     w2                             shut off
-     win10pro-fresh                 shut off
-     win2012r2-fresh1               shut off
-     win2k12r2                      shut off
-     windows10pro                   shut off
-     x1                             shut off
-     x2                             shut off
-     x3                             shut off
-     xenial                         shut off

## 

Jeffrey Pine Hein
Just plain helpful.
Technology consulting for nonprofits.
jphein.com http://www.jphein.com

## (530) 798-4099

jphein.com/blog <-- Check out my blog for daily updates on donations,
discounts, tech tips, and how to's. All geared toward people in nonprofits.

## To subscribe to my blog, use jphein.com/feed in your favorite feed reader.

jphein.com/helpdesk <-- Need support? Submit a trouble ticket at my help
desk.

I use Mailvelope http://mailvelope.com to encrypt and/or sign my
messages. If you would like to use secure email check it out. If you wish
to send me encrypted messages, my public key can be found @
jphein.com/pgp.pub.asc

**Comment by Seitanas** [comment]
Could you please paste screenshot of your current dashboard?

**Comment by jphein** [comment]
![screenshot from 2016-06-02 10-41-02](https://cloud.githubusercontent.com/assets/19301265/15754746/8a5f4ee0-28ae-11e6-9047-019f847e3317.png)

**Comment by Seitanas** [comment]
Does it say anything in php error log?

**Comment by jphein** [comment]
> [Thu Jun 02 07:00:03.595042 2016] [core:notice] [pid 2472] AH00094: Command line: '/usr/sbin/apache2'
> [Thu Jun 02 10:00:23.509952 2016] [:error] [pid 20781] [client 192.168.11.1:51220] PHP Notice:  Undefined index: logged in /var/www/html/kvm-vdi/functions/functions.php on line 98, referer: http://192.168.11.1/kvm-vdi/dashboard.php
> [Thu Jun 02 10:00:26.097048 2016] [:error] [pid 20780] [client 192.168.11.1:51226] PHP Notice:  Undefined index:  in /var/www/html/kvm-vdi/draw_table.php on line 73, referer: http://192.168.11.1/kvm-vdi/dashboard.php
> [Thu Jun 02 10:28:40.391738 2016] [:error] [pid 20777] [client 192.168.11.1:51528] PHP Notice:  Undefined offset: 9 in /var/www/html/kvm-vdi/vm_screen.php on line 31, referer: http://192.168.11.1/kvm-vdi/dashboard.php
> [Thu Jun 02 10:29:07.253171 2016] [:error] [pid 29476] [client 192.168.11.1:51582] PHP Notice:  Undefined offset: 9 in /var/www/html/kvm-vdi/vm_screen.php on line 31, referer: http://192.168.11.1/kvm-vdi/dashboard.php
> [Thu Jun 02 10:30:25.331920 2016] [:error] [pid 371] [client 192.168.11.1:51670] PHP Notice:  Undefined offset: 9 in /var/www/html/kvm-vdi/vm_screen.php on line 31, referer: http://192.168.11.1/kvm-vdi/dashboard.php

**Comment by Seitanas** [comment]
I will try to investigate this more thorougly, because i do not see any obvious problems.

**Comment by jphein** [comment]
ok, thanks. Only thing I can think of is to delete the database, and relabel everything.

**Comment by jphein** [comment]
NOTICE: KVM-VDI versions prior to 2016/06/01
I just read your readme. Looks like I have to update my database schema anyway.

> Older versions are no longer compatible with new release! Older versions need to be manually upgraded to a new db schema from sql/vdi.sql file
> Also you must edit you VM to change to the new KVM wrapper script:
> 
>  /usr/local/VDI/vdi-xmledit -name yourvmname

**Comment by Seitanas** [comment]
Deleting db should solve the problem, but you will have to reconfigure each vm type again.  Just try to delete line with "boxen1" vm from db 'vms' table

**Comment by jphein** [comment]
ok

**Comment by Seitanas** [comment]
Okay, the only thing that comes to my mind is that there may be duplicate entries of "boxen1" machine in database. Could you please paste me contents of your `vms` table?
 `SELECT * FROM vms;`

**Comment by Seitanas** [comment]
Closing issue due inactivity.
