### ISSUE TITLE
Blank Screen After Login

### ISSUE THREAD

**Issue by dvignali** [Seitanas/kvm-vdi#27]
Followed the instructions to install KVM-VDI. Successfully installed the database however when logging into dashboard I receive a blank white screen after clicking Login.

**Comment by Seitanas** [comment]
Blank screen usually means, that there's something wrong with php. Perhaps some modules missing.
Could you please paste your php error log?

**Comment by dvignali** [comment]
Thank you for the response. I rebuilt the server with Ubuntu 15.10 and installed all components again. Now it is working as expected.

There seems to be issues with Ubuntu 14 and php5-ssh2.
