### ISSUE TITLE
After installation of the dashboard and hypervisor the page does not list host names

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#28]
Hi, after installing the dashboard and configuring ssh keys for the VDI user, they are successfully added into the dashboard via the regular add hypervisor button.  After being added, 5 separate lines for each hypervisor are displayed showing the tty output of the host in each field saying sudo could not run remotely.  After changing sshd to not requiretty, things look better.  That should probably be added to your documentation

**Comment by Seitanas** [comment]
Hello,
this problem occurs, when you do not configure your sudoers file correctly.
Please add line from https://github.com/Seitanas/kvm-vdi/blob/master/hypervisors/sudoers
to your /etc/sudoers file

**Comment by henickr** [comment]
Ok, I understand what is happening now... thank you.. couldn't you error
handle for that?  I am seeing output that could say 'hypervisor not found
or now a new one complaining about something else but it appears that
errors are iterated through the machine listing loop and output as machine
names... maybe a sanity check although it may be very difficult to say what
isn't a hostname i guess.  It would be nice to have the common ones caught
and displayed.  Sudo file wrong, hypervisor files missing.  etc.

After this happened, a yum update was done on centos7 newest that caused
the php hash_equals function to go crazy.  I was not able to figure out
what dependancy had changed so after a bit of research a colleague modified
your code slightly to update hash_equals to use this instead.  What do you
think?

if (password_verify($password, $sql_reply[1])) {

It seems to work good now.  During testing, hash_equals was not printing
the same content as the database, the salt was off.  Apparently this is
newer/better to use.  Might want to take a look.

Thanks for your help.

**Comment by Seitanas** [comment]
Yes, you are right, I will put some logic into sudo sanity check.
As for `has_eaquals` - this is rather new php funcion, which came in php 5.6. Earlier versions has issues with this. It seems centos is still using php 5.4. Will try to investigate this as it seems, that this will cause problems for many users.
I'm planing to release a major upgrade of KVM-VDI ir very near future. Its in "devel" branch. I think, that these fixes will be added there.

**Comment by henickr** [comment]
an easy sanity check would be to see if the return line ^sudo or ^error
because it seems most problems return that when running

ssh -i /var/hyper_keys/id_rsa titanblade03.cs.lan sudo virsh -c
qmu:///system list

returns this on a host with incorrect sudo setup
sudo: sorry, you must have a tty to run sudo

and this on a host with libvirtd and/or hypervisors folder not scp properly
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such
file or directory

i love your work so far.  thank you.

**Comment by henickr** [comment]
Sorry to be a pest, another quick comment that may help someone.

SELECT vms.id,vms.name
,vms.hypervisor,vms.machine_type,vms.source_volume,vms.snapshot,vms.maintenance,vms.filecopy,vms.state,
vms_tmp.name AS sourcename  FROM vms LEFT JOIN vms AS vms_tmp ON
vms.source_volume=vms_tmp.id;

will show you what the database stores when these errors happen.  They do
not make sense in the web interface because it appears something is
splitting every second word between the name table and the state table so
the info pushed to web client is name only making the responses
unintelligible.  That is why many users cannot figure out what is going on
when there are problems...

**Comment by Seitanas** [comment]
Yes, this issue may be somewhat frustrating for users. I will release fix for it. As I've mentioned before, next release will be major one, - I've went for a pool-based VDI system with GUI based VDI client on thin client side (same as VMware horizon), also VM's will be provided with SSO capability with internal agents. This means that every user will be forced to reinstall KVM-VDI and drop their current databases. The sudo fix will be provided there also. Hope to release it next week.
Having said that, - if followed installation how-to thoroughly, you will never occur this problem :)

**Comment by henickr** [comment]
Excellent thanks for the heads up.  Our university was just about to
install this as a solution for our CS students.  I will hold it a week.

**Comment by henickr** [comment]
Ok, I also figured out why there are issues here.  I fixed all of my
hypervisor clients yet the error messages still persisted.

If you mysql -u root you can drop all tables from the database where
hypervisor = the one you were working on, things will work fine.

Past errors do not remove from the database so even if you fix the issue at
hand, the dashboard will display whatever sudo or tty error was present
previously and will look broken.  After you clear the contents of the
database table above, everything works great.

**Comment by Seitanas** [comment]
Hello,
new KVM-VDi is now released. It also fixes bugs, that are mentioned here.
