### ISSUE TITLE
After upgrade of new release on 07-18-2016 remote console does not display

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#29]
First, thank you very much for forwarding uncaught exceptions to apache error log.  Much better.

Fresh install of new code, imagick has a few issues on centos 7 using php 7 but not a big deal, need to add the image format symlinks so the screenshot displays properly.

Dropped entire vdi database and created an empty one then populated using the sql provided.

Re Added all hypervisors, worked great then created a few vms on my first blade.  Click open remote console and I get a blank window without arguments passed and the following url...
http://omitted.research.cs.dal.ca/kvm-vdi/vm_screen.php?password=

Upon closer inspection, I pull the popup out of the dashboard and view directly at...
http://omitted.research.cs.dal.ca/kvm-vdi/vm_screen.php?vm=4&hypervisor=2 directs me to some code that gives me the mysql queries you are running to connect.

I can clearly see the spice_password in the database is blank.  So it has nothing to pass on here.

Are there better instructions I should be following for this portion because there is nothing in your instructions that indicate it should do anything but work out of the box.

Oh, I found another bug in the new interface also.  When you disable any hypervisor using the enabled button in the dashboard, all subsequent entries are greyed out.  Looks like a close tag is missing in the php on the end of the 'disabled' button.

**Comment by Seitanas** [comment]
First thing that comes in mind - did you also upgrade scripts on hypervisor side (config file also needs to be upgraded)? New KVM-VDI now uses a hypervisor side agent 'vdi-agent', which needs to be started (systemd startup script is provided). I will upgrade README tomorrow and provide more specific installation steps.
As for a bug with disabling hypervisors - will look to it also.

**Comment by Seitanas** [comment]
Also, you mentioned, that http://omitted.research.cs.dal.ca/kvm-vdi/vm_screen.php?vm=4&hypervisor=2 gives you MySQL queries. Are those queries displayed? Perhaps you can send me a screenshot?

**Comment by henickr** [comment]
yes I did exactly as you updated.  I found the problem that could also cause you lots of questions.

When you check the log file on the node after updating these files, the agent cannot start because the log directory folder does not exist.  After doing mkdir /var/log/VDI; chown VDI:VDI /var/log/VDI the daemon starts.  testing again now.

**Comment by Seitanas** [comment]
That was fixed 5 hours ago :) I suspect you did clone project bit earlier than that

**Comment by henickr** [comment]
and no i dug the mysql queries out of the code.. they did not display... i was just showing you my logic how i came to my conclusion in case it helped figure out the issue.

as a suggestion, something that may be of HUGE help with future updates (since the "head node" has passwordless ssh access to the worker nodes, you could easily 'push hypervisor configs' to nodes using an admin section.... or at least a chksum verify to confirm they do not need updates.

might help.

i am updating from the fresh git branch now, thank you very much for your quick answers.

**Comment by Seitanas** [comment]
Yes, the "up to date" check is on roadmap. I will make it at some point. There are more priorities at the moment though. Like AD/LDAP integration.

**Comment by henickr** [comment]
ok, further into the debug log I seem to be having permission issues on the image file that was generated in the data directory.

Jul 19 18:07:38 titanblade02 libvirtd: 1919: error : virStorageFileGetMetadataRecurse:2998 : Cannot access storage file '/home/VDI/data_tmp/titantest02-vdi1-578e6c52127b6.qcow2' (as uid:107, gid:107): Permission denied

ll /home/VDI/ shows the folder is owned by VDI user 
drwxr-xr-x. 2 VDI VDI 4096 Jul 19 18:07 data_tmp

but the files show they are owned by root.
I did not create the .qcow2 files, kvm-vdi did that somehow.  
so it created them itself under a permission it can't read.  if that makes sense.
libvirtd is running as root.

**Comment by henickr** [comment]
and this is a completely fresh install as of about 10 minutes ago with only the config files updated and hypervisors freshly scp to the blade02 to update the scripts also.  database vdi dropped and repopulated freshly also after this install.

i am going to delete these files and allow them to be recreated.... mentioning this because it is possible it is the same scenario as last time where an old installation can cause issues?

**Comment by Seitanas** [comment]
This is perhaps the way centos accesses image files. I presume uid 107 is the libvirt user. you should try changing $libvirt_user $libvirt_group in config.php filr to user, which has uid = 107. Or just move data folder out of home directory and give it full rights.
There was no change in the way disk images were created since older KVM-VDI versions, so its very possible, that this is some kind of distribution thing which we must solve.

**Comment by Seitanas** [comment]
Regarding permission issues: you can try reconfiguring your qemu:
Edit `/etc/libvirt/qemu.conf` and uncomment the following lines:
`user = "root"`
`group = "root"`
Then restart libvirt.

**Comment by henickr** [comment]
sorry i should have replied yesterday... we are 5 hours apart it is 6 am
here.  changing the gid and uid to 107 made the error go away but it still
doesn't start... I'll be back at it in a few minutes.  I'll help write up
centos documentation for everyone also I'm doing this for a university as
well.

**Comment by Seitanas** [comment]
I think there may be problem, where qemu tries to access disk image within users home dir, which has permissions to allow only a owner to access it.
So moving disk images to some directory outside home dirs should help. Also it may help changing qemu user to root.

**Comment by henickr** [comment]
selinux is off also.

quick edit to this comment:  This was supposed to be fixed in 2015 but still occurs.
https://rhn.redhat.com/errata/RHSA-2015-0323.html
(maybe because centos release track is just THAT slow -- haven't checked)

**Comment by henickr** [comment]
ok sorry just sitting at my desk now... the error is not present anymore but i only chose /home because it had the most space and it was image related storage which i expected to need to hold images.  I can move it as a test to see what happens but i will try running libvirt as root first.  i believe there are a few other caveats to running libvirt as root on centos... i'll get back to you in a sec when i have done a few tests.... email directly at raymond.henick@dal.ca if you want to keep chitchat out of the comments, i can put useful info here so others can follow the troubleshoot

**Comment by henickr** [comment]
quick question.  clarify if i am misunderstanding please, the default image storage location for libvirt itself appears to be an area in /var/lib/libvirt/images where /data_tmp appears to be a local storage location.  Is the image pulled from the server when you issue the commands to deploy?  Just want to confirm that for any issues pertaining to image permissions, that I investigate in this central location while checking to make sure old files are not hanging around in temp locations causing problems.

**Comment by Seitanas** [comment]
`$temp_folder='/data/tmp';`is a temporary folder for storing VM screenshots when you open remote screen on your dashboard.

`$default_imagepath='/data';` is default path which will be suggested to you when you create new machine via dashboard.

`/var/lib/libvirt/images` is indeed the default storage path for libvirt. In KVM-VDI this path is used to store ISO files for new VM installation. 
Created VM disk images will be stored in `$default_imagepath` or  the path you will define when creating VM ("**Specify disk path:**" option in dashboard).
All of these directories are local on hypervisor side. So you need to have
`$default_iso_path='/var/lib/libvirt/images';` on each of hypervisor with ISO files in order to install OS.

**Comment by henickr** [comment]
ok, as an update here.  it appears that you should not try to put your data_tmp directory on /home in centos (maybe also debian).  it appears that libvirtd/qemu has problems specifically with selinux denying access to files in /home.  even in permissive mode, it seems to still cause issues somehow while run from /home but i cannot explain why without some investigation.  after moving the temporary folder to (off root) /data_tmp and then recreating the structure in the dashboard so the qcow files were recreated also, it looks to be in much better health.

**Comment by Seitanas** [comment]
Okay, closing this issue then.

**Comment by henickr** [comment]
hey sorry I'm going to open this up again rather than start a new one.. its technically the same

after changing the location of the tmp directory to /... rather than /home..., qemu is able to run the disk image so qemu itself appears to be functional -- i can see the screenshot of the bootloader.  I am still not able to get database to populate with the correct spice password to allow the button to be clicked from the interface to enter the remote console.  the url has password=<nothing> because the field in the database for spice password is empty.

**i have updated the hypervisor scripts from git on the blade server running the container and it did not help.**  i have been tailing the following files looking for information on the problem but coming up empty handed.  

/var/log/libvirt/qemu/titantest02-initial.log  (the individual container log)
/var/log/messages (conf file passes debug logging to both here and to the next one)
/var/log/VDI/libvirtd.log (debug output -- configured previously for tshoot)
/var/log/httpd/error_log (on the head/dashboard node)
all entries are of the class info or debug... nothing says any errors are present that i can see.

machine titantest02-source has been installed with centos7 minimal by creating an ssh tunnel
ssh -Y -L 5950:localhost:5900 omitted-blade02.research.cs.dal.ca
The host properly got a dhcp answer was networked, natted behind the head node... updated and then finally shut down so titantest02-initial could be created from it.  

I am connecting this way to the VMs directly because I have not attempted to configure the CA certificate to allow the LISTEN parameter to be changed in /etc/sysconfig/libvirtd which binds spice to all interfaces.  So remote connections are not possible at this time (to do later).  

Ok so a clear question.  Is there a better log I should be looking at to find problems with the 'remote console' button in the web interface?  or is there a step to populate a spice password that maybe wasn't included in instructions?

my next step is to manually add a spice password to the xml file then manually enter it into the database before clicking the button but if you could direct me to the location that populates this password typically that would help.

**Comment by Seitanas** [comment]
Hello, there are two things you must check. First of all you need to make sure, that VM is configured to start from vdi-wrapper:

`cat /etc/libvirt/qemu/yourvdivm.xml |grep emulator`
`<emulator>/usr/local/VDI/vdi-wrapper</emulator>`
If you see something like `<emulator>/usr/bin/kvm</emulator>` this means, that somehow `vdi-xmledit` has failed. 
You can fix settings by manually running `/usr/local/VDI/vdi-xmledit -name yourvmname`
(I think I will have to install KVM-VDI on centos hypervisor to test this issue)

Second, if this was not an issue, next thing I can think of is:
perhaps `password` parameter  in VDI/config does not match `$backend_pass` in `functions/config.php`?

**Comment by henickr** [comment]
yes, vdi-xmledit failed.  I remember seeing this in the log but didn't have
a point of reference for it.

[root@titanblade02 VDI]# ./vdi-xmledit -name titantest02-source

error: Failed to define domain from /tmp/titantest02-source_new.xml
error: XML error: virtio serial port 2 on controller 0 is already occupied

This may be an RHEL bug but I haven't read much on it yet to confirm.

**Comment by Seitanas** [comment]
This is not rhel bug. It seems , that virt-install adds quemu-agent channel if guest OS is "redhat-ish". I've bumped into this issue earlier today and released small update on vdi-xmledit.
(https://github.com/Seitanas/kvm-vdi/blob/master/hypervisors/vdi-xmledit)
You should upgrade it and try re-running `vdi-xmledit -name titantest02-source`

**Comment by henickr** [comment]
ok after updating the hypervisor code on titanblade02.cs.lan, vdi-xmledit works as expected and properly changed the host xml to call the wrapper.  one thing that may help to have posted here is a workflow of what happens.  i am digging in the code now to find out what is called by the wrapper to test each step along the way.  

the spice_password still is not populated in the database but i did get a message saying database has been upgraded when i pulled from git again.  that will help a lot going forward but right now i am very suspicious that something did not get ran correctly during initial setup so I am recreating the hosts right now and will update in a sec.  in doing this i want to confirm that a portion of script did not fail that is not sanity checked for posterity later.  (because it should have never failed)

to be clear here, i have been using an ssh tunnel to connect localhost to the blade on 5900, 5901 (whatever host) to do testing from that angle.  the only broken part here is the remote console portion.  the hosts themselves work fine.

**Comment by Seitanas** [comment]
The idea of populating spice_password goes like this:
If virtual machine is configured to use `<emulator>/usr/local/VDI/vdi-wrapper</emulator>`, then at the moment, when machine is started, vdi-wrapper  generates and posts random password to webservice.
You should see POST request on your webserver access.log when you start VM. Does it show up?

**Comment by Seitanas** [comment]
And yes, I will write some kind of workflow to make thing more clear, how KVM-VDI works, its just time I need for that.

**Comment by henickr** [comment]
i'll try to be as clear as i can in tshoot of my issues and hopefully anybody that comes into the same problem will be able to resolve it on their own using my notes here.

ok, so spice_password not populated.  After a reinstall of the entire package from git....
And after tailing /var/log/httpd/access_log I do NOT notice a POST coming in so I checked this...
[root@titanblade02 VDI]# grep emulator /etc/libvirt/qemu/fcs-virtuallab.xml 
    <emulator>/usr/libexec/qemu-kvm</emulator>

But.... when I run vdi-xmledit directly.... I get....
[root@titanblade02 VDI]# ./vdi-xmledit -name fcs-virtuallab
Domain fcs-virtuallab defined from /tmp/fcs-virtuallab_new.xml

This causes the proper changes to be made in the host xml file BUT... did not happen on its own on a fresh install of the git package, fresh populating of the database and freshly created source vm.

**Comment by henickr** [comment]
and although it didn't happen automatically... after running manually.... I now see the POST when starting the source image and the spice_password is now populated in the db for fcs-virtuallab.
@
10.15.205.12 - - [22/Jul/2016:16:04:50 +0000] "POST /kvm-vdi//backend.php HTTP/1.1" 200 - "-" "python-requests/2.6.0 CPython/2.7.5 Linux/3.10.0-327.22.2.el7.x86_64"

so I guess the problem is, vdi-xmlwrapper isn't being ran from a fresh install on centos.

**Comment by henickr** [comment]
except, after running manually... starting the image from the web client now produces this

root@titan:/var/www/html/kvm-vdi# [Fri Jul 22 16:11:11.326928 2016] [:error] [pid 3623] [client 10.15.205.12:36886] PHP Notice:  Undefined index: data in /var/www/html/kvm-vdi/backend.php on line 11

and this is because when trying to virsh start fcs-virtuallab from the command line, the script 
error: internal error: process exited while connecting to monitor: kvm: -machine pc-i440fx-rhel7.0.0,accel=kvm,usb=off: Unsupported machine type

mucked up that somehow.... but when checking the one that does work, it has identical syntax.

**Comment by Seitanas** [comment]
Okay, this is possibly different distribution issue. I will have to install redhat hypervisor and check this out. What release are you using?

**Comment by henickr** [comment]
[root@titanblade02 VDI]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 

[root@titanblade02 VDI]# yum upgrade -y && yum update -y
No packages marked for update
[root@titanblade02 VDI]#

**Comment by henickr** [comment]
i can give you access if you want or run something for you.  if it saves you an install.

let me know

**Comment by henickr** [comment]
[root@titanblade02 qemu]# diff old/titantest02-source.xml fcs-virtuallab.xml  
the 2 EXTRA parts that differ from a working one are this:

```
>   <resource>
>     <partition>/machine</partition>
>   </resource>

>   <seclabel type='dynamic' model='selinux' relabel='yes'/>
```

Any other differences are only related to the different virtual domain name.
Where the one that works does not have the above entries at all.

**Comment by henickr** [comment]
and for some reason, where previously it worked... now when you issue this....
/etc/libvirt/qemu/vdi-wrapper -machine help 

I get a list of supported machines that include pc-i440fx-2.0 down to 1.4 but no rhel7.0.0

**Comment by henickr** [comment]
From my research, apparently debian and redhat each use their own custom versions of libvirt.

The list having no rhel7 suggests that it is not the one that is running here.  

But after checking libvirt -v I get this.... so it is the RHEL version currently running.
2016-07-22 17:18:28.087+0000: 23998: info : libvirt version: 1.2.17, package: 13.el7_2.5 (CentOS BuildSystem http://bugs.centos.org, 2016-06-23-14:23:27, worker1.bsys.centos.org)

I have also confirmed that running the command that WAS present, previous to vdi-xmledit failing, /usr/bin/kvm -machine help..... pc-i440fx-rhel7.0.0 is also NOT present there either.

I am reading this looking for something....
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/6.4_Technical_Notes/libvirt.html

**Comment by henickr** [comment]
ok i think i have the answer but not sure if it is a good one.  I'll leave that to you.

It appears the vdi-wrapper script is pointing at /usr/bin/kvm which DOES NOT have the correct machine type.  When the script was failing, RHEL appears to default to using /usr/libexec/qemu-kvm and NOT /usr/bin/kvm..... so it was working, BECAUSE vdi-xmledit was failing...

check this out....
[root@titanblade02 qemu]# /usr/libexec/qemu-kvm -machine help
Supported machines are:
none                 empty machine
pc                   RHEL 7.0.0 PC (i440FX + PIIX, 1996) (alias of pc-i440fx-rhel7.0.0)
pc-i440fx-rhel7.0.0  RHEL 7.0.0 PC (i440FX + PIIX, 1996) (default)

**Can you make the wrapper use /usr/libexec/qemu-kvm instead of /usr/bin/kvm on RHEL systems automatically? (so everyone that installs it doesn't need to make that change manually)**

**Comment by henickr** [comment]
I changed the config file to point to the correct place and use qemu-kvm but there is another issue...    /usr/local/VDI/config:path_to_kvm=/usr/libexec/qemu-kvm

**Invalid parameter 'disable-agent-file-xfer'**

Interesting note, selinux triggering in permissive mode like we experienced earlier was supposed to be patched here but obviously still occurs. https://rhn.redhat.com/errata/RHSA-2015-0323.html

And I believe I am stuck here.  I'll poke at it a bit but not really sure how to proceed because libvirt version: 1.2.17 that is installed, is the latest version available on RHEL.  

Here is an upstream patch I found.  I can pull source and test it shortly.  It is a fairly easy addition, maybe build it and include it somewhere in the package?

```
---
 ui/spice-core.c | 12 ++++++++++++
 1 file changed, 12 insertions(+)

diff --git a/ui/spice-core.c b/ui/spice-core.c
index bcc4199..2faac93 100644
--- a/ui/spice-core.c
+++ b/ui/spice-core.c
@@ -446,6 +446,9 @@ static QemuOptsList qemu_spice_opts = {
             .name = "disable-copy-paste",
             .type = QEMU_OPT_BOOL,
         },{
+            .name = "disable-agent-file-xfer",
+            .type = QEMU_OPT_BOOL,
+        },{
             .name = "sasl",
             .type = QEMU_OPT_BOOL,
         },{
@@ -739,6 +742,15 @@ void qemu_spice_init(void)
         spice_server_set_agent_copypaste(spice_server, false);
     }

+    if (qemu_opt_get_bool(opts, "disable-agent-file-xfer", 0)) {
+#if SPICE_SERVER_VERSION >= 0x000c04
+        spice_server_set_agent_file_xfer(spice_server, false);
+#else
+        error_report("this qemu build does not support the 
\"disable-agent-file-xfer\" option");
+        exit(1);
+#endif
+    }
+
     compression = SPICE_IMAGE_COMPRESS_AUTO_GLZ;
     str = qemu_opt_get(opts, "image-compression");
     if (str) {
-- 
1.8.2.1
```

Have a good weekend!

**Comment by henickr** [comment]
the change is already present in their github repo so I am compiling from source now
https://github.com/qemu/qemu

**Comment by Seitanas** [comment]
I've updated `vdi-xmledit` to check distribution, and not use `disable-agent-file-xfer` parameter for redhat releases. For already created machines, just remove this parameter using `virsh edit yourvmname`

**Comment by henickr** [comment]
ok installed to new blade to ensure a consistent environment for testing... as opposed to using my slightly modified one from installing qemu from source....

While rebuilding fresh, I noticed a few things to assist with making the install more fluid for all...

something that could be sanity checked during creation of a new host could be ifExist /data
and create it if it does not.  rather than throwing an error which it currently does if it fails...  While reinstalling, I accidentally went to the prefix /kvm-vdi instead of /install first and got an ugly error.
If tables are missing, it should auto redirect to the install page to allow population... 

I will update this thread when everything has been installed and back to the previous status with a report of what happens without file-xfer enabled.  I have been installing fresh often to ensure everything stays clean and easily reproduced.

**Comment by henickr** [comment]
Hey I've been having a problem here, thinking it was to do with me upgrading qemu-kvm to 2.6 from source to enable file xfer option only to realize after digging through it that everything on the host is fine.  Everything is fresh as of now and the dashboard will not start any created VMs and no errors are displayed.  As a tip for anyone reading, if this happens, to troubleshoot the next step is to start manually because starting with the web interface will not tell you what is wrong in the logs.

While using /usr/libexec/qemu-kvm in the config file:

After running "virsh start fcs-virtuallab", (or deleting and recreating the vm) the debug log shows this:
Jul 26 03:54:03 titanblade02 libvirtd: 10242: error : qemuBuildMachineArgStr:7617 : unsupported configuration: vmport is not available with this QEMU binary

**You must have recently (since yesterday) added something to the code that uses vmport?**

I checked other blades that I'm sure I was using yesterday and they are all the same libvirtd version 
libvirtd (libvirt) 1.2.17

So I'm not sure how that is possible unless there is something new causing it....

Another bug I found is the virsh commands don't check to make sure they return success because when this fails, I need to delete the item out of the database because although qemu can't work, it still adds to the db yet creates no log or xml file and is not present in the vms list.  Permissions everywhere are fine.

Get back to me when you can.  

thanks.

**Comment by Seitanas** [comment]
Hello, the only thing that was added yesterday is  a fix to redhat-speciffic error, which caused guest VMs not to boot due `disable-agent-file-xfer`, so you should be able to use qemu, which came with distribution. There should be no need to compile it by yourself.
`vmport` is a vmWare IO port, which is not used with KVM-VDI solution. I presume, that perhaps libvirt has support for it, and qemu was compiled without it. This perhaps causes some miscommunication between them? I'm currently installing KVM-VD on fresh centos hypervisor and will check if there are any issues there.

**Comment by Seitanas** [comment]
Okay, I've ran full hypervisor/dashboar/vm installation on Centos 7.
I've had no problems creating new machine ("vmport" issues), I've slightly updated non-VDI vm creation part, because I've bumped into some issues, where dashboard began waiting for VM installation to finish.
I've also slightly updated dashboard installation on Centos readme.
So your issues with vmport is perhaps something local (non compiled in functions perhaps)? Try using libvirt and qemu-kvm from centos packages instead of compiling them.

**Comment by henickr** [comment]
Ok great.  Just curious because you've been so active in development and it
was possible... thanks for testing.

**Comment by henickr** [comment]
Hi, ok thanks.  I torched that blade and went to a fresh one.  Not useless work though, I will continue the compile from source option with vmport compatibility and possibly build an rpm later for others to upgrade to qemu 2.6..... I hear there are security issues with old libvirtd so I will attack that and maybe get some extra functionality out of the effort also... later.  

Would it be worth me making this rpm for the benefit of everyone? 
current release is - QEMU emulator version 1.5.3 (qemu-kvm-1.5.3-105.el7_2.4) (from 2008)

Have a look at this one.  Fresh install on a new blade with a fresh git pull returns this when creating a VM.  PHP Fatal error:  Uncaught Error: Call to undefined function mb_substr() in /var/www/html/kvm-vdi/create_vm.php:62\nStack trace:\n#0 {main}\n  thrown in /var/www/html/kvm-vdi/create_vm.php on line 62, referer: http://titan.research.cs.dal.ca/kvm-vdi/dashboard.php  returns a 500 from httpd.

This one can't be me ;)

**Comment by Seitanas** [comment]
You should install php-mbstring.
There's also an updated README on dashboard service on Centos.

**Comment by henickr** [comment]
ok that got it, sorry I didn't see that addition to the documentation.
**php-mbstring** was installed on the dashboard node to resolve this.

I had another problem where the requests module imported in the wrapper wasn't present.
This was resolved by installing **python-requests.noarch** and re running vdi-xmledit.  I will test an automated creation of all this at the end to make sure everything runs from the dashboard.

So after all that was done.  Finally, the remote console button works on centos 7 minimal.
I am assuming you used a regular centos 7 if you didn't need to find every package.

After everything in this thread, the **spice password is FINALLY populated** AND passed to the browser uri bar when you click the open remote console button.  But... the console does not connect.  Also, the manual connection through the ssh tunnel is now password protected by the password generated into the database.

httpd_error says this. 
[Tue Jul 26 15:55:55.599818 2016] [:error] [pid 7521] [client 10.15.205.13:32978] PHP Notice:  Undefined index: data in /var/www/html/kvm-vdi/backend.php on line 11

libvirtd debug log says this
2016-07-26 16:07:43.893+0000: 12259: error : virFDStreamCloseInt:311 : internal error: 2016-07-26 16:07:43.884+0000: 17667: debug : virFileClose:102 : Closed fd 27

Your centos 7 worked completely when you installed it?  
Did you click remote console and try to connect?

**Comment by henickr** [comment]
ok i think i found out why, selinux again.

Jul 26 16:14:49 titanblade03 kernel: type=1400 audit(1469549689.410:42): avc:  denied  { connectto } for  pid=18195 comm="python" path="/run/nscd/socket" scontext=system_u:system_r:svirt_t:s0:c98,c153 tcontext=system_u:system_r:nscd_t:s0 tclass=unix_stream_socket
Jul 26 16:14:49 titanblade03 kernel: type=1107 audit(1469549689.411:43): pid=12464 uid=28 auid=4294967295 ses=4294967295 subj=system_u:system_r:nscd_t:s0 msg='avc:  denied  { shmempwd } for  scontext=system_u:system_r:svirt_t:s0:c98,c153 tcontext=system_u:system_r:nscd_t:s0 tclass=nscd#012 exe="?" sauid=28 hostname=? addr=? terminal=?'
Jul 26 16:14:49 titanblade03 kernel: type=1400 audit(1469549689.411:44): avc:  denied  { read } for  pid=18195 comm="python" path="/var/db/nscd/passwd" dev="dm-0" ino=134993037 scontext=system_u:system_r:svirt_t:s0:c98,c153 tcontext=system_u:object_r:nscd_var_run_t:s0 tclass=file
Jul 26 16:14:49 titanblade03 systemd: Started Puppet agent.
Jul 26 16:14:49 titanblade03 systemd: Starting Puppet agent...
Jul 26 16:14:49 titanblade03 kernel: type=1400 audit(1469549689.458:45): avc:  denied  { execute } for  pid=18217 comm="sh" name="ldconfig" dev="dm-0" ino=20463 scontext=system_u:system_r:svirt_t:s0:c98,c153 tcontext=system_u:object_r:ldconfig_exec_t:s0 tclass=file
Jul 26 16:14:49 titanblade03 kernel: type=1400 audit(1469549689.458:46): avc:  denied  { read open } for  pid=18217 comm="sh" path="/usr/sbin/ldconfig" dev="dm-0" ino=20463 scontext=system_u:system_r:svirt_t:s0:c98,c153 tcontext=system_u:object_r:ldconfig_exec_t:s0 tclass=file
Jul 26 16:14:49 titanblade03 kernel: type=1400 audit(1469549689.459:47): avc:  denied  { execute_no_trans } for  pid=18217 comm="sh" path="/usr/sbin/ldconfig" dev="dm-0" ino=20463 scontext=system_u:system_r:svirt_t:s0:c98,c153 tcontext=system_u:object_r:ldconfig_exec_t:s0 tclass=file
Jul 26 16:14:49 titanblade03 kernel: type=1107 audit(1469549689.541:48): pid=12464 uid=28 auid=4294967295 ses=4294967295 subj=system_u:system_r:nscd_t:s0 msg='avc:  denied  { shmemhost } for  scontext=system_u:system_r:svirt_t:s0:c98,c153 tcontext=system_u:system_r:nscd_t:s0 tclass=nscd#012 exe="?" sauid=28 hostname=? addr=? terminal=?'
[Tue Jul 26 16:14:23.910675 2016] [:error] [pid 8153] [client 10.15.205.13:33092] PHP Notice:  Undefined index: data in /var/www/html/kvm-vdi/backend.php on line 11

Selinux is in permissive mode, still doing this.
Loaded policy name:             targeted
Current mode:                   permissive

**Comment by henickr** [comment]
tried a few methods.... nothing yet..... 

semanage permissive -a nscd_t 
semanage permissive -a svirt_t

even created a custom module from the errors | audit2allow -M kvm-vdi
then semodule -i kvm-vdi.pp to load the custom module created...

same result.  Not even completely sure why it is denied at all in permissive mode but the bug in libvirt that I pointed out earlier in the thread has me adding permissions anyway for good measure.

**Comment by Seitanas** [comment]
You should look at your hypervisor configuration (at the dashboard). There are 2 hypervisors addresses there. Management and SPICE (they can be the same). Spice address is passed to your thin clients (if you have your thin clients on different IP zone/VLAN). But if you want to get console from dashboard, you will get IP address from management IP zone. Check if you are able to access your hypervisor management IP from computer your are browsing dashboard.

**Comment by henickr** [comment]
I will try that shortly, there are definitely selinux issues I need to resolve despite the host being in permissive mode.

Jul 26 17:22:10 titanblade03 python: SELinux is preventing /usr/bin/env from entrypoint access on the file /usr/local/VDI/vdi-wrapper.#012#012****\*  Plugin catchall (100. confidence) suggests   **************************#012#012If you believe that env should be allowed entrypoint access on the vdi-wrapper file by default.#012Then you should report this as a bug.#012You can generate a local policy module to allow this access.#012Do#012allow this access for now by executing:#012# grep vdi-wrapper /var/log/audit/audit.log | audit2allow -M mypol#012# semodule -i mypol.pp#012

I am going to disable selinux completely, reboot and try... See what happens.

**Comment by henickr** [comment]
and awesome.  an actual, new, unresolved centos bug.
https://bugs.centos.org/view.php?id=7550

**Comment by Seitanas** [comment]
You should check  if your vm is running -`virsh list`. If it does, try telnetting to you hypervisor by the SPICE port of that vm (you can get the port by running `ps xawww|grep vmname` on your hypervisor.
If telnet won't succeed, then there's probably firewall issue on  hypervisor side.

**Comment by henickr** [comment]
Last update to this thread.  Don't leave selinux in permissive mode.  I guess a bug in libvirt (posted earlier in this thread) caused selinux to still trigger as enabled and targeted despite it being set to permissive mode.  Adding to selinux doesn't actually help.  As soon as you set it to completely disabled all of the odd problems go away.  So I am not sure if it is not really fixed as suggested by the RHN errata posted above or if the stable centos release track is just THAT slow.

For anyone reading this, set it to disabled and you won't need to know either is my advice there.. :)

Thanks for helping with this.

**Comment by henickr** [comment]
this can be closed also
