### ISSUE TITLE
When creating a source machine, there is nothing under the "Please select hypervisor" menu.

### ISSUE THREAD

**Issue by jphein** [Seitanas/kvm-vdi#3]
![screenshot from 2016-05-11 01-05-12](https://cloud.githubusercontent.com/assets/19301265/15174133/91057e7e-174f-11e6-9487-f47459848bc4.png)

Apache error log:

> [Wed May 11 01:03:00.713688 2016] [:error] [pid 15095] [client ::1:44966] PHP Warning:  mysqli_close() expects exactly 1 parameter, 0 given in /var/www/html/kvm-vdi/functions/functions.php on line 35, referer: http://localhost/kvm-vdi/dashboard.php
> [Wed May 11 01:03:00.713714 2016] [:error] [pid 15095] [client ::1:44966] PHP Notice:  Undefined variable: query_array in /var/www/html/kvm-vdi/functions/functions.php on line 36, referer: http://localhost/kvm-vdi/dashboard.php
> [Wed May 11 01:03:00.714173 2016] [:error] [pid 15095] [client ::1:44966] PHP Warning:  mysqli_close() expects exactly 1 parameter, 0 given in /var/www/html/kvm-vdi/functions/functions.php on line 35, referer: http://localhost/kvm-vdi/dashboard.php
> [Wed May 11 01:03:00.714183 2016] [:error] [pid 15095] [client ::1:44966] PHP Notice:  Undefined variable: query_array in /var/www/html/kvm-vdi/functions/functions.php on line 36, referer: http://localhost/kvm-vdi/dashboard.php
> [Wed May 11 01:03:50.176247 2016] [:error] [pid 15209] [client ::1:44972] PHP Warning:  mysqli_close() expects exactly 1 parameter, 0 given in /var/www/html/kvm-vdi/functions/functions.php on line 35, referer: http://localhost/kvm-vdi/dashboard.php
> [Wed May 11 01:03:50.176273 2016] [:error] [pid 15209] [client ::1:44972] PHP Notice:  Undefined variable: query_array in /var/www/html/kvm-vdi/functions/functions.php on line 36, referer: http://localhost/kvm-vdi/dashboard.php
> [Wed May 11 01:03:50.176485 2016] [:error] [pid 15209] [client ::1:44972] PHP Warning:  mysqli_close() expects exactly 1 parameter, 0 given in /var/www/html/kvm-vdi/functions/functions.php on line 35, referer: http://localhost/kvm-vdi/dashboard.php
> [Wed May 11 01:03:50.176493 2016] [:error] [pid 15209] [client ::1:44972] PHP Notice:  Undefined variable: query_array in /var/www/html/kvm-vdi/functions/functions.php on line 36, referer: http://localhost/kvm-vdi/dashboard.php

config:

```
<?php
/*
KVM-VDI
Tadas Ustinavičius
tadas at ring.lt

Vilnius University.
Center of Information Technology Development.


Vilnius,Lithuania.
2015-12-22
*/
###################Dashboard config##########################
#$hypervizors=array('192.168.10.1:22','192.168.10.2:22');
$hypervizors=array('127.0.0.1:22');
#Substitute local hypervisor IP address with external one if needed.
#Substituted IP adresses will be provided for SPICE remote console connections in dashboard.
#$remote_spice_substitute=array('192.168.10.1'=>'172.31.1.1','192.168.10.2'=>'172.31.1.2');
$remote_spice_substitute=array('127.0.0.1'=>'172.31.1.1');
$serviceurl='http://localhost/kvm-vdi';
$language='en_EN';
############################################################

##################vmWare Horizon config (if used)###########
$vmView_server='view.someadress.tld';
############################################################

##################Hypervisor config#########################
$temp_folder='/data_tmp/tmp';
$backend_pass='12345';
$ssh_user='vdi';
$ssh_key_path='/home/vdi/.ssh/';
$hypervisor_cmdline_path='/usr/local/VDI/';
$default_bridge='br1';
$default_imagepath='/data';
$default_iso_path='/var/lib/libvirt/images';
############################################################


####################Database config#########################
$mysql_host='localhost';
$mysql_db='vdi';
$mysql_user='vdi';
$mysql_pass='vdi';
############################################################

```

**Comment by Seitanas** [comment]
This is strange behavior. Can't reproduce the same error. Will try to test this on Ubuntu 15.

**Comment by jphein** [comment]
Now it's there.
