### ISSUE TITLE
copy from hostname-source to hostname-initial does not refresh web page

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#30]
After creating a source image and installing an OS on it (centos 7 minimal), when attempting to create the initial machine from the source disk, you select 'copy disk from source'.  The files all copy but the progress bar immediately goes to and stays at 100% indefinitely, even if you refresh the dashboard.  (chrome 51.0.2704) 

I tried to start it the first time.  Failed because it was still copying i assume.  Began looking into why the copy may have failed and eventually realized it started up fine next time.  Refreshed page 30m later with the initial machine running at the login prompt and the dashboard STILL shows the progress bar at 100%.

**Comment by Seitanas** [comment]
For debugging purposes try running copy command from hypervisor side manually:
`/usr/local/VDI/copy-file /data/source_image /data/target_image vmid`
eg:
`/usr/local/VDI/copy-file /data/fedora24_64-5790b21e3ad4a.qcow2 /data/fedora_initial-5790b70e5620c.qcow2 45`
you can get `vmid`  from database or url - just hover over your vm screen button, - you should see `vm_screen.php?vm=somenumber`

If copy command does not fail, then the only thing I can think of is non matching password in `VDI/config`  and `$backend_pass`  in  `functions/config.php`. Or incorrect `address` parameter in `VDI/config`

**Comment by henickr** [comment]
yes the copy works fine and the passwords are confirmed to be the same in both functions/config.php on the dashboard and /usr/local/VDI/config on the hypervisor being tested.  I suspect my previous issues with the xml wrapper script are the cause of this as it was not properly ran during the install and failed because of a redhat specific issue.  that has now been fixed in another thread and runs ok with expected results.

Only thing I can think of here is to redo this process completely now that it functions... which I kicked off before I left yesterday.  testing again now with a fresh config.  will post results in a sec

**Comment by Seitanas** [comment]
So, if copy function forks manually, does progress bar work also?

**Comment by henickr** [comment]
No it does not.  That is why I began a fresh reinstall because it is a bit
unexplainable... I will update again after that is done.

**Comment by Seitanas** [comment]
The idea of progress bar is somewhat similar to populating spice_password.
When `copy-file` is called, it posts progress to webservice, which stores progress into db. Then JavaScript reads progress from db and updates progress bar.
You should see POST requests in your webserver access log while `copy-file` is running.

**Comment by henickr** [comment]
this works now... much more dynamic and easy to follow status.

especially the initial creation of initial image from source image.  that would typically be the first time a user has seen that happen ever... now it doesn't really need explaining.. 

copy completed and bar went away.  call this closed.  looks good.

**Comment by Seitanas** [comment]
Closing issue then.
