### ISSUE TITLE
new windows 10 vm source machine does not boot first time

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#32]
Same as all other VDI source machines, one was created using the latest windows 10 x64 1511 iso.

This works for both the linux and ubuntu isos using the exact same procedure.

When the windows machine boots, it hangs at the windows boot disk logo and this error is in the individual container log, /var/log/libvirt/qemu/fcs-virtuallab-win10-source.log 

((null):18955): Spice-Warning **: reds.c:2016:reds_handle_ticket: Invalid password

Otherwise though, I don't see any reason it shouldn't load.  It booted from the iso ok because it seems to hang at the windows logo indefinitely so it's possible it's a libvirtd issue and nothing to do with kvm-vdi.  Thats it for errors though.  I'll try a copy of windows 8 for now.  

Try a copy of 10 on yours and see if it works at all.  What version of libvirtd does ubuntu box with?
centos is 1.2.17

**Comment by Seitanas** [comment]
For testing purposes, could you please change `qxl` driver of that VM to `cirrus`?

**Comment by henickr** [comment]
does this have anything to do with using qemu-kvm with the rhel7.0.0 machine tag?

**Comment by Seitanas** [comment]
Yes, it is a specific red-hat related problem:
https://bugzilla.redhat.com/show_bug.cgi?id=750773
I had same problem with centos hypervisor. Had no issues with Debian.

**Comment by henickr** [comment]
changing to either vga or cirrus causes it to throw this

error: XML document failed to validate against schema: Unable to validate doc against /usr/share/libvirt/schemas/domain.rng
Extra element devices in interleave
Element domain failed to validate content

Failed. Try again? [y,n,i,f,?]: 

until you change it back.  It does look like they fixed it in build 25 as it says in the comments.  
Might need to upgrade the package after all.  

I hit ignore and am trying to boot now to see what it does.

**Comment by Seitanas** [comment]
This also seem to happen on Ubuntu and sometimes on Debian (which had not occur to me):
https://bugs.launchpad.net/ubuntu/+source/seabios/+bug/958549/comments/16

As far as I do understand - its a problem, where Windows does not have qlx drivers installed and are connected via SPICE. The solution, which should help perhaps are:
- Run windows with cirrus video card, install spice-guest-tools, shutdown and change display to qxl.,
- Or, make windows install cd with qxl drivers inside. -see nlite: http://www.nliteos.com/

**Comment by Seitanas** [comment]
For `error: XML document failed to validate against schema: Unable to validate doc` error, change entire model line to:
`<model type='cirrus' vram='9216' heads='1'/>`

**Comment by henickr** [comment]
it automatically changed mine to this  
`<model type='cirrus' vram='16384' heads='1'/>`

but still appears to be hanging.... i'll leave it for a while and see.

**Comment by Seitanas** [comment]
Hmm, this sounds odd. Stupid question - did you fully shutdown machine and started it up after changes? 
I will try to install windows 10 tomorrow to see if this happens at my site (I had this problem with windows 7, - but it seems its a problem with all windows releases).

**Comment by henickr** [comment]
I believe so but I'll do it again.  It never actually booted for me to shut
it down so I wasn't sure how long to wait.

**Comment by Seitanas** [comment]
You can still force shutdown with "power down" button.

**Comment by henickr** [comment]
I had to leave the office for a bit.  I'll update when I get back.

**Comment by henickr** [comment]
ok so after a lot of research and a bit of testing, it looks like the problem is with the way qemu loads its guests.  (paravirtualization vs vt-x native) there are a few examples of minor changes working as workarounds to get around the problem, either by changing the video to 'cirrus' or changing the cpu to 'core2duo' but these appear to be just workarounds and not a solution to the actual issue although a reproducible workaround is good enough for my purposes.

I found a page with a long list of hosts/guests that have apparently been tested previously.
http://www.linux-kvm.org/page/Guest_Support_Status

That page is where I got a few ideas to test options that made others work for them.

There is more information in the qemu-devel mailing list I haven't gotten through all of yet.
http://lists.gnu.org/archive/html/qemu-devel/2012-09/msg01412.html

I am yet to get one working after many different options tried but am following your previous suggestion now to make sure the vm actually gets cleanly restarted after a change.

**Comment by Seitanas** [comment]
What exactly fails? You cannot boot your ISO into windows 10 installer – just see logo and cant get pass it?

**Comment by henickr** [comment]
yes, exactly.  while loading msdn copies of windows 7 and 10.

no errors worth mentioning in the local vm log /var/log/libvirt/qemu/win7-msdn.log

and just tested a force shutdown and startup using 'cirrus' like this.

```
    <video>
      <model type='cirrus' ram='65536' vram='65536' vgamem='16384' heads='1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
```

same result.

**Comment by Seitanas** [comment]
This issue, perhaps is related to specific quemu-km version. I have no problems getting windows10 (nor 7) to run on Debian hypervisor.
And regarding the problem, where machine does not  dismount CD after first reboot, you should just update KVM-VDI. There are many changes made there and should solve this issue.

**Comment by henickr** [comment]
Yes, the cd failing to unmount issue was resolved during an update.  That works perfectly now.

[root@titanblade05 qemu]# /usr/libexec/qemu-kvm -version
QEMU emulator version 1.5.3 (qemu-kvm-1.5.3-105.el7_2.4), Copyright (c) 2003-2008 Fabrice Bellard

My problem with versioning here is I can't seem to use any other version because this is the only one that has the machine type I am looking for pc-i440fx-rhel7.0.0

Is that machine type a requirement?  If I switch to using /usr/bin/qemu-system-x86_64 instead I get an unknown machine type message because it is missing rhel7.  Would it be possible to see how that one works using pc-i440fx-2.0 instead or is that not workable using rhel 7?

**Comment by Seitanas** [comment]
On Debian I use:
`QEMU emulator version 2.6.0 (Debian 1:2.6+dfsg-3), Copyright (c) 2003-2008 Fabrice Bellard`
from unstable and:
`QEMU emulator version 2.1.2 (Debian 1:2.1+dfsg-12+deb8u4), Copyright (c) 2003-2008 Fabrice Bellard`
from stabe distribution.
Both installs windows 7 without any issues. Tried Windows 10 on 2.6.0 though.

**Comment by henickr** [comment]
ok, so to avoid changing the qemu package from source as that is probably a difficult task, I've tried to use the other binary provided on centos systems qemu-system-x86_64.

When starting the same vm created under the previous qemu version, this message comes up 
2016-08-08 14:34:26.582+0000: 2934: error : qemuProcessWaitForMonitor:2227 : internal error: process exited while connecting to monitor: qemu-system-x86_64: -machine pc-i440fx-rhel7.0.0,accel=kvm,usb=off: Unsupported machine type
Use -machine help to list supported machines!

we know that already because of a previous encounter with the problem however I am curious if there is any other way to get around this besides changing to something that does have the supported machine type.  Is there any way that requirement can go away so this one can be tested?

The default RHEL version of this package is QEMU emulator version 2.0.0, Copyright (c) 2003-2008 Fabrice Bellard so it might work if I can get past that -machine requirement.

That said, I'm installing debian on one of the blades so I can determine which of the problems are redhat specific because as nice as it would be to have RHEL working, its been a PITA.

**Comment by Seitanas** [comment]
Just a guess, but this is perhaps machine types on virt-install and newer qemu package do not match.
Perhaps you should try using ev pakage:
`yum install qemu-kvm-common-ev.x86_64` ?

**Comment by henickr** [comment]
ok thats the ticket man.  that worked when i switched back to using /usr/libexec/qemu-kvm 
so that is also a required package on centos hypervisors... please add that to the install docs maybe with a comment saying it is necessary or it won't load a windows VM so nobody else has to experience this pain.  works for win7 iso anyway... testing 10 now.

it doesn't actually find a drive but thats a different issue.  thats the virtio drivers problem... i'll let you know what i do so that can be added to the doc also but thats different than this anyway.

update: win10 msdn iso also loads to the install screen with this package installed.

both installs stop at unable to find the drive, instead of finding the virtio drive.  but thats a separate issue.  i'll close this one in a sec after making sure this resolves everything up until that point.

**Comment by henickr** [comment]
woah, adding 2 cdrom drives to a qemu guest is a bit unstable to say the least.  kernel panic on the hypervisor box.  nice.  well don't cut and paste them into the guest xml and virsh start it anyway.  

maybe virt-manager has better luck.

i guess this can probably be closed because getting virtio/whatever other disk driver to load is a different problem.

**Comment by Seitanas** [comment]
How did you manage to add 2 cdrom drives?

**Comment by Seitanas** [comment]
Closing issue for now

**Comment by henickr** [comment]
i duplicated the device and changed the targets.

maybe i'm approaching that wrong then?  thats the most logical way I could think of to have the drivers available to load while installing a copy of windows was 2 cdrom drives.  how do you do it?

**Comment by Seitanas** [comment]
The way we are doing it, - when windows installer starts and shows, that there are no hard disks available, we just unmount windows installer ant mount virtio.iso:
![](http://i.stack.imgur.com/be6cr.png)
 Then we install virtio disk drivers and qlx drivers. We mount windows installer afterwards.

**Comment by henickr** [comment]
so my way works fine, i just can't find drivers that work yet because they aren't signed correctly.

just paste this under the other disk for the hdd image 

```
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <source file='/var/lib/libvirt/images/virtio-win.iso'/>
      <target dev='hdb' bus='ide'/>
      <readonly/>
      <address type='drive' controller='0' bus='0' target='0' unit='1'/>
    </disk>
```

note the "unit='1'" as that is what is important to allow 2 cdroms.

i did it wrong previously.  it works now.  you need to restart libvirtd after each change. 

![kvm-vdi](https://cloud.githubusercontent.com/assets/12343647/17488754/30312f2c-5d71-11e6-8b31-e92b54bbbb45.png)

**Comment by Seitanas** [comment]
For win10, I use https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.iso because it has qxl drivers (qxl-ga)

**Comment by henickr** [comment]
quick edit... on the windows 10 installer, 2 cdrom drives doesn't appear to work.  my screenshot was from the windows 7 installer.  in the windows 10 installer, it does not appear.

edit:  you must use virsh attach-disk method posted below and it works flawlessly on the win10 installer.  start it up normally with the windows iso get to the window in the screenshot and attach-disk the driver iso, select it, install it then attach-disk the installer iso again and you're golden.

**Comment by Seitanas** [comment]
For the future - you should not edit xml file directly. You should edit it with `virsh edit vmname` command. This will reload libvirt without you needing to restart it.

**Comment by henickr** [comment]
what is the command you use to mount/unmount a cd drive without editing anything?
oh just virsh edit it and change it while running?

**Comment by Seitanas** [comment]
if you specify direct path to your iso file in xml, it should mount automatically

**Comment by henickr** [comment]
so, boot windows iso and progress through installation until stopped by no disk present

switch to terminal, virsh edit domain and change the windows iso to the virtio-win.iso file

tab back to spice client and hit browse finds nothing.  am i doing this wrong?

**Comment by Seitanas** [comment]
try 
`virsh attach-disk VMNAME virtio.iso hda --type cdrom --mode readonly`

**Comment by henickr** [comment]
ok i know why because su to qemu cannot read the directory... the files are owned by qemu... anyway this is not a problem with the software... i'll get back to this when it is fixed.

**Comment by henickr** [comment]
ok so i thought it was file permissions but it wasn't.  the file loads fine and I can see the contents of it from the windows installer... so I can see the inf files and everything expected.  it just says a suitable driver is not found on that device.  its like i'm using the wrong iso but I re-downloaded via the link you provided above.... not sure... need to hit google for this one.  

normally when you have virtio-win.iso mounted as a cdrom device, you just select the root of the device when you hit browse for drivers and it finds them?  or in a specific location on that drive?

**Comment by Seitanas** [comment]
You should specify direct path to drivers, and not let installer to search for them.
If it's win10x64, then virtio storage driver would be:
`\viostor\w10\amd64`
For qxl you should use:
`\qxldod\w10\amd64`

**Comment by henickr** [comment]
yeah that is exactly the problem.  previously i tried just specifying root, and everything in between... after your comment there, i began selecting every folder i could, as specific as possible and eventually found the one i need.  so i guess the lesson here is just to be very specific.

other times i've just specified iostor for example and it has found it no problem.

edit: after installing, the nic will need to have this done also in dev manager, as well as the balloon driver and one other one.  the only device that I can't find a driver for is sound which I don't believe works over spice at the moment anyway so it doesn't really matter.

so that works anyway... let me let this install finish and i can call this one closed.

**Comment by henickr** [comment]
quick comment for anyone reading, qemu-kvm-common-ev.x86_64 is from the repo http://resources.ovirt.org/pub/yum-repo/ovirt-release40.rpm

**Comment by henickr** [comment]
sorry one more comment here to add.  after testing windows 7 and 10 it seems the drive read speed requirement is heavy for window-cies (is that a word?) everything works fine with linux but when windows comes into the mix, even with 4 procs and 2gb ram i/o is pinned to the roof most of the time using spinny disks.  i am considering having ssd arrays in the hypervisors that run windows.

**Comment by Seitanas** [comment]
Is this really IO issue? Please check - perhaps ovirt agent consumes your cpu. If so, then I've released patch for this problem today.

**Comment by henickr** [comment]
welcome back!  seems to be but i dismissed it when i checked task manager and saw disk i/o that was pinned.  i will confirm and get back when i have more info, i didn't think there was much i could do at the time.

**Comment by Seitanas** [comment]
Well, to get lower io consumption on spindle drives, you should disable windows update/indexing service. Also you should get rid of residential antivirus. Because antivirus will try to download definitions on each vm boot. Those definitions will be deleted after you shutdown VM because of snapshots (the same happens with updates).
