### ISSUE TITLE
'populate machines'

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#33]
Hi, the populate machines function works perfectly however it does not display the status when it is populating.  The code you wrote that displays the status of the push from source to initial is fantastic.  Maybe that function could be used here also?  I suggest this because populating machines is quite a long process so information of knowing its exact status would be useful and you may already have most of it written because of the previous issue.

For example.  I have a source machine and initial machine with 20 VDI machines created.
I click on the initial machine and 'populate machines'.  The process completes successfully but all 20 VDI machines stay in maintenance mode and I am unsure when to take them out.  That is why I am asking for more clarity here so I don't have to watch top until it finishes.

**Comment by Seitanas** [comment]
Hello,
VDI population is instant, so there's no need to have progress indication here. As soon as dashboard page reloads, after you push `Populate machines`, - job is done.

**Comment by henickr** [comment]
oh ok, sorry there is a lot of stuff going on inside.  The machines all stay in maintenance then after a population.  Is that intentional?

**Comment by Seitanas** [comment]
Yes, because by default you probably want to start them without letting users connect to them at first and run some sysprep scripts to rename/join AD etc.
