### ISSUE TITLE
issue displaying status while rebooting(or if failed) hypervisor

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#34]
When a hypervisor is being rebooted, (_or has failed_) the log properly shows that it cannot connect as I would expect in /var/log/httpd/error_log on the dashboard node however....

The dashboard itself does not reflect anything suggesting that it had difficulty connecting to its hypervisors.  If it cannot connect to a hypervisor, maybe a message saying unable to connect to hypervisor in the dashboard if no success on the ssh call to each.  this could cause the hypervisor in question to have the enabled flag turned off automatically maybe?

**Comment by Seitanas** [comment]
Yes, you are right. At this point it is better to put hypervisor to maintenance before rebooting it.
Will look into solving this.
