### ISSUE TITLE
spice html5 client not working

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#35]
Hi, trying to use the new html5 web sockets client but after cloning websockify and starting it 
./run --token-plugin TokenFile --token-source /tmp/kvm-vdi 5959... 

root@titan:~/henick/websockify# lsof -i:5959
COMMAND   PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
python  30666 root    3u  IPv4 2750944      0t0  TCP *:5959 (LISTEN)

then... visiting the url /kvm-vdi/client_pools.php

I am kicked to a login page to which I login with valid credentials to be allowed through only to receive the message LOGIN_FAILURE on the following page.

I haven't configured or installed anything so I assume that is the issue but the directions simply say run using that command and don't provide much else.  Should I be building websockify from source or running it in some other way than I have said here?

i am posting this because i did not expect a problem with authentication ...

Thanks.

edit: i've since done an easy_install numpy and 'python setup.py build' then install on websockify in an attempt to omit usage of the provided copy in lieu of one built by this system.  end result same.

**Comment by brianhenson** [comment]
I too have this issue

**Comment by Seitanas** [comment]
Hello, sorry for late answer - had a work trip. 
You have to create client (`Clients>add client`) in dashboard and also put it to atleast one pool (`Add clients to pool`). If user has no pools available, it will be ignored.
If you are using AD/LDAP users, you must have to create at least one group for that user add it to pool (`add AD group` `Add AD group to pool`).

**Comment by brianhenson** [comment]
worked perfectly. Can you add that to the readme file? I used it to setup everything

**Comment by Seitanas** [comment]
Sure I will.

**Comment by henickr** [comment]
ok yeah, the confusing part for me here was that the client you add is not the same login as the dashboard itself.  you add a completely different user which you login to at that page and then, providing you have a pool created with contained vms started, then the client_pools.php populates.

it does seem to 'work' in the sense that there aren't any errors.  I can connect directly to the same vm using the spice client and it displays the desktop but the browser displays a black page with no errors.  

I suspect that may be a browser issue or something so I am trying a few different methods now.

admittedly i'm at a bit of a loss as to how to troubleshoot this....

**Comment by Seitanas** [comment]
You should try running websockify in interactive mode (omit --daemon parameter). You will be able to see websockify output then. There are many issues with websockets. One of them - if dashboard is running on https, you also have to provide ssl certificate to websockify. Also you need to know, that self-signed certificates does not work with firefox browser. This is a known issue.

**Comment by henickr** [comment]
your documentation doesn't specify a --daemon parameter... it says
./run --token-plugin TokenFile --token-source /tmp/kvm-vdi 5959

but.... when I run it this way...
./run --token-plugin TokenFile --token-source /tmp/kvm-vdi 5959 --log-file=/tmp/kvm-vdi/websockets.log &

I have a log file to tail... then hit it in the browser gives me ... 
handler exception: need more than 1 value to unpack

So yeah its a websockets issue... I'll figure that out on the internet, I don't suspect I'd be lucky enough for you to know the answer to that one.

**Comment by henickr** [comment]
incorrect config file based on their issues page....
https://github.com/kanaka/websockify/issues/235

**Comment by Seitanas** [comment]
Are tokens in /tmp/kvm-vdi directory created?
Also if you need to daemonize websockify, - do not use `&`. Use `--daemon`

**Comment by henickr** [comment]
using this now instead of documentation...
./run --token-plugin TokenFile --token-source /tmp/kvm-vdi 5959 --log-file=/tmp/kvm-vdi/websockets.log --daemon

same result.  no there are no tokens generated in /tmp/kvm-vdi/, just the log i created.

**Comment by Seitanas** [comment]
This is odd. Perhaps there's anything in webserver error log?
There should be token files created in /tmp/kvm-vdi
Are you running websockify on the same server, on which dashboard service is deployed?

**Comment by henickr** [comment]
yes same server as dashboard.  i would only expect me to have an odd issue.  very typical lately...

only thing in the httpd_error log while client_pools.php is open is that it is very chatty now with repeated php errors stating undefined index 'ad_user' and 'state' for draw_html5_buttons.php ... 

otherwise nothing special.  i've considered switching this to debian but its been so much fun trying to fix centos why stop now ;)

> [Thu Aug 11 15:37:26.112319 2016] [:error] [pid 26620] [client 129.173.67.12:61521] PHP Notice:  Undefined index: ad_user in /var/www/html/kvm-vdi/draw_html5_buttons.php on line 33, referer: http://omitted.research.cs.dal.ca/kvm-vdi/client_pools.php
> [Thu Aug 11 15:37:26.117114 2016] [:error] [pid 26620] [client 129.173.67.12:61521] PHP Notice:  Undefined index: state in /var/www/html/kvm-vdi/draw_html5_buttons.php on line 54, referer: http://omitted.research.cs.dal.ca/kvm-vdi/client_pools.php

**Comment by Seitanas** [comment]
strangely enough, it does create `/tmp/kvm-vdi` folder. Have no idea, why it does not create tokens inside that folder though. selinux perhaps?

**Comment by Seitanas** [comment]
Oh, try moving log file out of /tmp/kvm-vdi folder. Also delete the one that's already inside.

**Comment by henickr** [comment]
no i created that folder because it didn't create it and i needed a log to look at....so you're probably right there somehow, perms or something but....

SELinux status:                 disabled

and its /tmp so perms issue would be confusing.

when i delete it, i get this... so i will forego the log for now because i now have a bit of an idea whats going on where before i had no clue... so don't really need it at the moment.
IOError: [Errno 2] No such file or directory: '/tmp/kvm-vdi/websockets.log'

and running this now, no it does not create anything again.
./run --token-plugin TokenFile --token-source /tmp/kvm-vdi 5959  --daemon

strace i guess.... :|
side note, should probably make a systemctl command for running this thing so it would be easier to figure this out.... i'll do that in a sec.

**Comment by Seitanas** [comment]
If you've created `/tmp/kvm-vdi` by hand, you need to change permissions of that folder for webserver to be able to write there.
Just delete that folder and let dashboard to create it by itself. Also do not put log into that folder. Logfile may be misinterpreted by websockify

**Comment by henickr** [comment]
already tried that, did nothing.... looking through strace now to find out why... this might take a while...

**Comment by Seitanas** [comment]
Doubt if strace will help you. You should debug web part. Web part creates directory and tokens. Websockify  just reads files in directory on demand.

**Comment by henickr** [comment]
maybe i'm misunderstanding that but the run command has that path directly as an argument so in an strace i must see it do something with it somewhere... nothing appears in error_log and I don't see another area to look...

**Comment by Seitanas** [comment]
That path is accessed by websockify module only, when you try to access html5 console. It does not do anything when started or in idle mode. [https://github.com/kanaka/websockify/blob/master/websockify/token_plugins.py#L46](https://github.com/kanaka/websockify/blob/master/websockify/token_plugins.py#L46)
The way it works: when you press on a pool icon on your client_pools.php site, KVM-VDI selects a VM from that pool for you, starts it, then calls `websocket.php` and creates token file in /tmp/kvm-vdi folder (also folder, if needed) with the name of that VM. It puts name, address and port of that VM inside the toke file. After that it calls html5 client and defines token, which it should access. Also a SPICE password.

**Comment by henickr** [comment]
ok great, i needed to find this 

```
if (!file_exists('/tmp/kvm-vdi/')) {
    mkdir('/tmp/kvm-vdi', 0777, true);
}
```

so yeah, odd it doesn't error to httpd_error indeed....

**Comment by Seitanas** [comment]
okay, could you try changing code a bit:
    `mkdir('/tmp/kvm-vdi');`

**Comment by henickr** [comment]
i was just thinking the same thing.... i removed the kvm-vdi component completely as a test.... and had tokens generated directly into tmp temporarily... also changed the websockets command to point directly at /tmp.... 

still no tokens...  i'll try that way now..

**Comment by henickr** [comment]
ok... friggin weird.... I commented out the if portion and forced the code to create regardless.

the error log throws this now

> [Thu Aug 11 16:36:45.210846 2016] [:error] [pid 5252] [client 129.173.67.12:61946] PHP Warning:  mkdir(): File exists in /var/www/html/kvm-vdi/websocket.php on line 21, referer: http://titan.research.cs.dal.ca/kvm-vdi/client_pools.php

It does not.

**Comment by Seitanas** [comment]
It works as intended. If directory already exists, it is impossible to create it.

**Comment by henickr** [comment]
of course.  but it doesn't :)

> root@titan:~/henick/websockify# ls /tmp
> systemd-private-a80e5c25bb9544fb9361e3c4b7dc1007-httpd.service-aO59Xa  systemd-private-a80e5c25bb9544fb9361e3c4b7dc1007-mariadb.service-S1uw6F

**Comment by Seitanas** [comment]
maybe there's `kvm-vdi` file inside /tmp?

**Comment by henickr** [comment]
nadda.  friggin weird.

**Comment by henickr** [comment]
ok it gets stranger... rm -rf /tmp/\* 
same result.

**Comment by Seitanas** [comment]
So kvm-vdi directory is still  not created?

**Comment by henickr** [comment]
nope... after doing the rm -rf i hit the browser again with a tail -f /var/log/httpd/error_log | grep -i mkdir & running so I can see it error out on the forced mkdir every time.  still nothing there.

but i can see it trying every time i refresh.

times like this make me wish i chose to be a debian eng :|

touch /tmp/test works .......

**Comment by Seitanas** [comment]
Okay, just create a simple test.php file with contents:
`<?php
mkdir('/tmp/test');
file_put_contents("/tmp/test/file","content");
?>`
and then try to access it via web browser.

**Comment by henickr** [comment]
same result.

root@titan:~/henick/websockify# ll -d /tmp
drwxrwxrwt. 7 root root 99 Aug 11 16:45 /tmp

**Comment by Seitanas** [comment]
no /tmp/test folder is created?

**Comment by henickr** [comment]
ok it created a test file in there, not a directory but it did do something.

**Comment by Seitanas** [comment]
it should have been created /tmp/test/  folder and /tmp/test/file inside of it

**Comment by henickr** [comment]
it does throw this error when it happens though

> root@titan:~/henick/websockify# [Thu Aug 11 16:52:32.102536 2016] [:error] [pid 12342] [client 129.173.67.12:62142] PHP Warning:  mkdir(): No such file or directory in /var/www/html/kvm-vdi/test.php on line 3

maybe the php version.... 7.0.9?  I can't see it being THAT drastically different...

**Comment by Seitanas** [comment]
Don't think so. Should work with 7 out of the box.
Just create /tmp/kvm-vdi directory and chmod it to 777 then try using html5 client. See if tokens are created. If this won't work, time to ticket RH I think :)

**Comment by henickr** [comment]
just tried that, no tokens created.  i'm going to pull a fresh copy from git... something crazy here.

**Comment by henickr** [comment]
also tried to su apache --shell=/bin/bash; mkdir test and it works

**Comment by henickr** [comment]
also tried to make the test file relative.  it can't create anything inside the kvm-vdi web directory either.

i have a php dev here with me testing another system.

**Comment by henickr** [comment]
oh my good god.  ok its fixed but still doesn't work.

```
You need to set PrivateTmp=false in /usr/lib/systemd/system/httpd.service
then systemctl daemon-reload; systemctl restart httpd.service
```

i still have a black screen but the tokens are generated now -- with contents.

I guess centos 7 apache has a private temp location that sometimes interferes with this that should be shut off to use.  so the tokens are there now but still black screen.

**Comment by Seitanas** [comment]
What does websockify log say?

**Comment by henickr** [comment]
says just the typical startup stuff and the token file includes the name of the (randomly?) selected available vm (I have 10 VDI systems free in the pool and it chose number 5 -- arbitrary but anyway) and also the blade.domain.tld:port it is running on in the token.  

I see in the url bar, the information has all been passed along with the password... one point of note.... vm number 5 was not started before the token was created.  now it is.... 

only things i can think of are to run websockify in verbose mode... with the log...

```
./run --token-plugin TokenFile --token-source /tmp/kvm-vdi 5959 --log-file=/tmp/kvm-vdi/websockets.log --daemon --verbose
```

the log file only contains multiple copies of the socket cleanly starting... and verbose adds nothing valuable... but the vm it chose is started... so it did do something....

and other idea to turn on browser errors in php.ini but this causes a bit more odd behavior... with errors to browser turned on, the popup does not open with the url... and with errors off like default and i click the pool, a new tab pops open with this as the target...

```
http://omitted.research.cs.dal.ca/kvm-vdi/spice_html5/?host=omitted.research.cs.dal.ca&port=5959?password=correctpasswordfromdb&vmInfoToken=nameofvm
```

in both instances, with errors on or off, whatever vm is chosen in the token is auto started.

just won't display.  so there are the ideas i had.... interesting however that the popup doesn't open with error reporting on but possibly unrelated... any other ideas?

**Comment by Seitanas** [comment]
Maybe your dashboard service is running on https?

**Comment by henickr** [comment]
nah, no https.  another interesting side note i see is that in top on blade03 (the hypervisor that contains the vm it randomly chose -- 05) I see for the last 23h vdi-wrapper running with the qemu process below it.  vdi-wrapper is supposed to go away when it loads the qemu-kvm process isn't it?

when i start it using the dashboard directly, i normally don't see a vdi-wrapper process at all because it typically finishes quickly -- unless i'm mistaken.  so interesting....

**Comment by Seitanas** [comment]
Yes, vdi-wrapper should go away. It just calls kvm with required parameters and exits.

**Comment by henickr** [comment]
so, i tried a few more things related to increasing memory and ttls/execution limits of the JVM because while using other actual hypervisors like openvz, memory is often the cause of sudden unexplainable stops... until finally I got a stack trace from websockify... its the same error though that suggests the configuration is wrong.  its likely something centos7 specific with websockify so i will work with them and get it resolved then post the result back here when i am finished.

> 129.173.x.x: new handler Process
> handler exception: need more than 1 value to unpack
> exception
> Traceback (most recent call last):
>   File "/root/henick/websockify/websockify/websocket.py", line 930, in top_new_client
>     client = self.do_handshake(startsock, address)
>   File "/root/henick/websockify/websockify/websocket.py", line 860, in do_handshake
>     self.RequestHandlerClass(retsock, address, self)
>   File "/root/henick/websockify/websockify/websocket.py", line 114, in **init**
>     SimpleHTTPRequestHandler.**init**(self, req, addr, server)
>   File "/usr/lib64/python2.7/SocketServer.py", line 649, in **init**
>     self.handle()
>   File "/root/henick/websockify/websockify/websocket.py", line 581, in handle
>     SimpleHTTPRequestHandler.handle(self)
>   File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
>     self.handle_one_request()
>   File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
>     method()
>   File "/root/henick/websockify/websockify/websocket.py", line 543, in do_GET
>     if not self.handle_websocket():
>   File "/root/henick/websockify/websockify/websocket.py", line 485, in handle_websocket
>     self.validate_connection()
>   File "/root/henick/websockify/websockify/websocketproxy.py", line 52, in validate_connection
>     host, port = self.get_target(self.server.token_plugin, self.path)
>   File "/root/henick/websockify/websockify/websocketproxy.py", line 128, in get_target
>     result_pair = target_plugin.lookup(token)
>   File "/root/henick/websockify/websockify/token_plugins.py", line 51, in lookup
>     self._load_targets()
>   File "/root/henick/websockify/websockify/token_plugins.py", line 30, in _load_targets
>     tok, target = line.split(': ')
> ValueError: need more than 1 value to unpack
> Ignoring interrupted syscall

**Comment by Seitanas** [comment]
You should try websockify from git to see if it works. Just clone it, change to its directory and use ./run command with your parameters.

**Comment by henickr** [comment]
same result.  is there anything specific about the usage i should be aware of when presenting the problem to them short of providing the error?  Anything specific that would help with the -way- the code uses the daemon?

**Comment by Seitanas** [comment]
I'm still nor very convinced, that its websockify problem. Are tokens now created in /tmp/kvm-vdi folder?

**Comment by henickr** [comment]
yes and everything expected appears in the URI but as soon as the browser window pops open to the black screen the error presented is the stack trace I posted immediately above this message with the error suggesting the configuration file is wrong.  So likely centos 7 is somehow passing the config wrong or using it in some unexpected way, i'm guessing now.

```

root@titan:~/henick/git-websockify/websockify# 129.173.x.x: new handler Process
handler exception: need more than 1 value to unpack
```

**Comment by Seitanas** [comment]
And there are no other type of files in /tmp/kvm-vdi folder (like log file or something), just tokens?

**Comment by henickr** [comment]
nope.

**Comment by henickr** [comment]
Aha!  ok, this just popped up when i clicked it this time.  not sure why not before.
error: [Errno 113] No route to host

**Comment by Seitanas** [comment]
Also check if token files contain correct data. It should be:
tokenname: server_address:port

**Comment by henickr** [comment]
yes token contents are correct.

**Comment by henickr** [comment]
this is beginning to look like some issue related to the fact i'm running on blade servers.

**Comment by Seitanas** [comment]
Have no idea, how this could be related. We are running our production on 3 blade servers.

**Comment by henickr** [comment]
no i spoke too quickly, any server would be identical to this blade considering how it works with the hypervisors being ssh accessible.  blade server makes no difference...

**Comment by Seitanas** [comment]
`ValueError: need more than 1 value to unpack` is really an error, which tells, that contents of a token file does not have `:` symbols in it. Perhaps there is one file inside /tmp/kvm-vdi that does not?

**Comment by henickr** [comment]
is there some specific type of traffic that maybe my router isn't forwarding?

**Comment by henickr** [comment]
these are internal addresses anyway i will post the contents as they are inaccessible to the world.

fcs-virtuallab-win1010: titanblade03.cs.lan:5901

**Comment by Seitanas** [comment]
Nope, this is not a network related. Plugin just scans all files inside /tmp/kvm-vdi directory, reads contents and exlpodes with `:` (note space)

**Comment by henickr** [comment]
another interesting note is.... the no route to host error did not appear until i cloned their copy from git...

**Comment by Seitanas** [comment]
You need to have your dashboard server to be able to access hypervisor  by  `titanblade03.cs.lan` address

**Comment by henickr** [comment]
yes access is fine..

```
root@titan:~/henick/git-websockify/websockify# su VDI
Aug 12 14:14:43 titan su: (to VDI) root on pts/0
VDI@titan:/root/henick/git-websockify/websockify$ ssh titanblade03.cs.lan
Last login: Thu Jul 28 15:18:45 2016
VDI@titanblade03:~$ 
```

**Comment by Seitanas** [comment]
Just tried accessing your token and it woks fine:
`./run --token-plugin TokenFile --token-source /tmp/kvm-vdi 5959`
`WARNING: no 'numpy' module, HyBi protocol will be slower`
`WebSocket server settings:`
`- Listen on :5959`
`- Flash security policy server`
`- No SSL/TLS support (no cert file)`
`- proxying from :5959 to targets generated by TokenFile`
`/?password=TDIrNM9QRmdhdzuMpgSfUXyo7i&token=fcs-virtuallab-win1010`
`192.168.0.181 - - [12/Aug/2016 17:12:19] 192.168.0.181: Plain non-SSL (ws://) WebSocket connection`
`192.168.0.181 - - [12/Aug/2016 17:12:19] 192.168.0.181: Version hybi-13, base64: 'False'`
`192.168.0.181 - - [12/Aug/2016 17:12:19] 192.168.0.181: Path: '/?password=TDIrNM9QRmdhdzuMpgSfUXyo7i&token=fcs-virtuallab-win1010'`
`192.168.0.181 - - [12/Aug/2016 17:12:19] connecting to: titanblade03.cs.lan:5901
handler exception: [Errno -2] Name or service not known`
Last line is expected, because there are no dns entries for that address.

**Comment by henickr** [comment]
I get this:

```
x.x.x.x: new handler Process
mydesktop.research.cs.dal.ca - - [12/Aug/2016 14:18:48] "GET /?password=mVcEwmJWnlL2yaqYEN2Q0mMahS&token=fcs-virtuallab-win1002 HTTP/1.1" 101 -
mydesktop.research.cs.dal.ca - - [12/Aug/2016 14:18:48] x.x.x.x: Plain non-SSL (ws://) WebSocket connection
mydesktop.research.cs.dal.ca - - [12/Aug/2016 14:18:48] x.x.x.x: Version hybi-13, base64: 'False'
mydesktop.research.cs.dal.ca - - [12/Aug/2016 14:18:48] x.x.x.x: Path: '/?password=mVcEwmJWnlL2yaqYEN2Q0mMahS&token=fcs-virtuallab-win1002'
mydesktop.research.cs.dal.ca - - [12/Aug/2016 14:18:48] connecting to: titanblade03.cs.lan:5901
handler exception: [Errno 113] No route to host
exception
Traceback (most recent call last):
  File "/root/henick/git-websockify/websockify/websockify/websocket.py", line 930, in top_new_client
    client = self.do_handshake(startsock, address)
  File "/root/henick/git-websockify/websockify/websockify/websocket.py", line 860, in do_handshake
    self.RequestHandlerClass(retsock, address, self)
  File "/root/henick/git-websockify/websockify/websockify/websocket.py", line 114, in __init__
    SimpleHTTPRequestHandler.__init__(self, req, addr, server)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/root/henick/git-websockify/websockify/websockify/websocket.py", line 581, in handle
    SimpleHTTPRequestHandler.handle(self)
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/root/henick/git-websockify/websockify/websockify/websocket.py", line 543, in do_GET
    if not self.handle_websocket():
  File "/root/henick/git-websockify/websockify/websockify/websocket.py", line 531, in handle_websocket
    self.new_websocket_client()
  File "/root/henick/git-websockify/websockify/websockify/websocketproxy.py", line 91, in new_websocket_client
    connect=True, use_ssl=self.server.ssl_target, unix_socket=self.server.unix_target)
  File "/root/henick/git-websockify/websockify/websockify/websocket.py", line 736, in socket
    sock.connect(addrs[0][4])
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 113] No route to host
Ignoring interrupted syscall
```

**Comment by Seitanas** [comment]
Okay, so token files are read correctly now. 
There is a new problem, that websockify cannot access titanblade03.cs.lan.
Are you using multiple gateways on your dashboard server?

**Comment by henickr** [comment]
nope just our main router... (that has a gateway for each of our internal subnets and a firewall that forwards to each but most traffic is allowed through 

```
default via x.x.x.x dev eno1  proto static  metric 100 
192.168.122.0/24 dev virbr0  proto kernel  scope link  src 192.168.122.1 ****
```

I do see the virtual bridge created another gateway somehow though that appears to be alive... 192.168.122.1....  I didn't make that... I vaguely remember it in the dhcp configs of either kvm-vdi or qemu as the pool that is issued to the dhcp clients... 122.0/24

it looks like it is trying to use my router as the default gateway which is typical for my environment here but instead should be using 192 to get to the address that was dhcp'd by the vm...
maybe i'm wrong..

**Comment by Seitanas** [comment]
192.168.122.1 is default gw for libvirt virtual network. It is created automatically, when you install libvirt. you can disable it - it will not affect anything.

**Comment by henickr** [comment]
ok i think a creatively placed route will fix this ... i just need time to think of what to write...

**Comment by Seitanas** [comment]
one last idea - perhaps you have somekind of firewall, that does not allow you to connect to 59xx ports from dashboard server.
try `telnet  titanblade03.cs.lan 5901`

**Comment by henickr** [comment]
yep thats it.  that is exactly why i suspected network issue earlier in the thread... because its happened before... this firewall is pretty restrictive and partially the reason i don't mind posting so much information for people to openly follow on the internet...

i'll get back to you in a sec...

**Comment by henickr** [comment]
that part was a question but the private tmp part might be more important for others to read...

this is going to take me a minute to figure out because its not always going to be port 5900 it can be maybe up to 5920 per blade .... I'll try 5900 for now and figure that nonsense out later.

**Comment by Seitanas** [comment]
Just disable firewall rules from dashboard server. I can see no security issues here. Let dashboard server to be able access everything

**Comment by henickr** [comment]
no this is not a local firewall, the dashboard server is a head node which has a research subnet address...  and the blades are internal so they traverse our router.... this is specific to our network here and information nobody really needs..

**Comment by henickr** [comment]
ok after 2 hours poking around on the router firewall i learned another lesson about centos 7's newest release.  firewalld will happily run in the background blocking things while you think iptables is in charge..... duh. ok.  nice.  ok this one was my fault :(  testing time.

it works now.... seems to be having trouble capturing keyboard input... mouse input works fine but i'm walking away for a few minutes lol

**Comment by Seitanas** [comment]
Well, I use HTML5 client from another project:
https://github.com/eyeos/spice-web-client
It has lots of optimizations and features, that are vital for KVM-VDI.
The project is somewhat passive now. Will look into keyboard issues monday - perhaps this is not client issue after all.

**Comment by henickr** [comment]
no it appears to be an eyeos issue where if you click out of the browser pane then back in it somehow loses capture... if you never click outside the window it works.... i think when i fix the resolution to come up correctly it will reduce the risk of it happening.

**Comment by Seitanas** [comment]
Nope, have no issues with keyboard. Having said that, we had issues with keyboard input on normal spice client, when hypervisor ran on Debian stable (autorepeat didn't work). After moving hypervisor to unstable everything began to work fine. Not sure, but perhaps there was some issues with old libspice.

**Comment by henickr** [comment]
oh, one issue appears to be when i tried to show it to someone in the next office that also opened up an instance by clicking on the pool... only a single token generated so we are back and forth stealing each others vm when it should be making 2 tokens for each of us... but that is a separate issue... this one can probably be closed and i'll open a new one after i poke around a bit and see if any real issues persist.

as for this particular issue.. the answer is.....

make sure centos 7 isn't using private tmp space.... and make sure firewalld is not working when you think iptables is working.

**Comment by Seitanas** [comment]
This is intended. you are hardwired with your username. so one user has only one session. it is useful, when you need to change your client computer/thin client and want to have your session follow you.
By default session is reserved for 5 minutes (can be changed in config.php).

**Comment by henickr** [comment]
ok great, good info.  yeah we used the same login

**Comment by henickr** [comment]
this thing is fantastic.

**Comment by Seitanas** [comment]
I assume everything works then? :)

**Comment by henickr** [comment]
yeah more or less.  i'd like to know how to change the resolution to scale the available browser space... their documentation suggests...

```
You can do it permanently editing run.js or through the URL using the parameters:
http://example.com/spice-web-client/index.html?host=IP_ADDRESS_OF_WEBSOCKIFY&port=TCP_PORT_OF_WEBSOCKIFY
```

but it looks like you already do that with parameters and run.js i'm looking around a bit but it definitely doesn't appear as simple as just a variable or setting.  it'd be an exercise

**Comment by henickr** [comment]
its really fast.  way better than virt-viewer on mac and windows (3.0.... 4.0 is completely broken)

**Comment by Seitanas** [comment]
Do you have spice-agent running on your guest? Because my screen always takes resolution of my window.
virt-viewer should not be slower, unless computer you are running it on has slow CPU. virt-viewer still is best solution for thin clients, since it has kiosk mode and usb redirection.

**Comment by henickr** [comment]
do you use 3.0 or do you have 4.0 working?  its most likely caused by me using an old version...

**Comment by Seitanas** [comment]
I'm using 4.0, but as I've realized, - client version has little impact on performance. It's the hypervisor side that matters. This is why we moved hypervisors to unstable distribution.

**Comment by henickr** [comment]
oh and no i don't have spice-agent running yet because i haven't quite figured out the nat on the dashboard node so the guests on the libvirt network can get internet access... they can ping the dashboard node but that is all.  so as soon as the nat is done they should work.

**Comment by Seitanas** [comment]
guests are bond to hypervisor's bridge. there's no networking done on dashboard side. you should make dhcp on hypervisor bridge side/vlan. This is the easiest way to provide VMs with network.

**Comment by Seitanas** [comment]
spice-agent (also ovirt-agent) are network independent - they will work even if no network is attached. They are using sockets between hypervisor and guest.

**Comment by henickr** [comment]
dhcp on the guests works fine to get to 192.168.122.0/24 ... i don't see external traffic ... maybe the bond is different on redhat or broken.  never turned ip_forwarding on is likely the cause.

oh i'm sure the spice-agent is independent i just can't download it on the client without internet and i have done much work to customize an iso yet ..

i think i know why the guests are slow i just realized.... the disk is full.  i ran the windows assessment tool and it says 7.85/10G is reserved for system files.  haven't dug much deeper yet.

i only got them running the way i want recently so there is quite a bit of little cleanups to do.

**Comment by henickr** [comment]
oh sorry a quick comment about the internet not working thing is that everything is fine in linux... just windows is the issue... and all of the drivers have been installed... gateway pings.. hm... forgot the linux side worked... now i'm more curious :)

**Comment by Seitanas** [comment]
This is known issue with windows guest + virtio network adapter, when dhcp server vm is on same hypervisor. You should try using newer dhcp server (this is fixed in newer isc-dhcpd), or use differnent netwrork card for dhcp or guest vm (one of them will do).

**Comment by henickr** [comment]
excellent.  you're full of good information aren't you :) ... tyvm.

ps.  do you ever sleep?  I know i work a lot but man.

**Comment by henickr** [comment]
and the full drive thing is just me not paying attention to what iso i used... to clarify... that was less of an oversight and more of a troubleshooting step at the time.  i was not able to get the hypervisor to run windows 10 because of the ev package missing on centos 7 so i wanted to use the most 'normal' iso that i could from msdn.  

i'm trying this thin client one now that i am sure it works ok... despite the fact my research says it works great except maybe it can't install office... we use o365 here anyway so i can live with that.
https://blogs.windows.com/business/2011/07/01/heres-the-skinny-windows-thin-pc-available-for-download-today/

edit: i found a direct link to an x86 version of their iso that still works
http://download.microsoft.com/download/C/D/7/CD789C98-6C1A-43D6-87E9-F7FDE3806950/ThinPC_110415_EVAL_x86fre.iso

and... an update..
https://www.microsoft.com/en-us/download/details.aspx?id=29238

edit again...
![image](https://cloud.githubusercontent.com/assets/12343647/17641238/81b15dac-60ed-11e6-99e5-ae86ce98ccd6.png)
iostor/w10/x86 loads the driver but then fails saying contact vendor for an updated driver.

too bad.  i'll look around and see if i can get it to accept another one.. i'd like to see it run.

edit again... 
used attach-disk virtio-win-latest from the repo and used iostor/w7/x86 and it seems to work.

**Comment by henickr** [comment]
seems really good... very light.. copy of win7 with all the io intensive stuff turned off already... 10 worked fine but this is a lightweight option for anyone looking for one or using old hardware or whatever the use case may be... 

quick question about customizing iso... i read if you press shift+ctrl+f3 at the create account screen it puts the system in 'audit' mode and allows you to do some customizations before running sysprep to finalize it for deployment... i wasn't able to make that happen--possibly due to keyboard not sending keys, tried onscreen-- so i took a snapshot in case i wanted to do it later... i know about ntlite and was planning on doing it that way previously... then i stumbled across this..

**Comment by henickr** [comment]
i think this is a patch to the dhcp issue 
http://pkgs.fedoraproject.org/cgit/rpms/dhcp.git/tree/dhcp-4.2.2-xen-checksum.patch?id=038d346d726e131f1ab2579fe015a72b49733a0d;id2=HEAD

context is udp packets dropped because of bad chksums... causes odd behavior with kvm and virtio
https://lists.ubuntu.com/archives/foundations-bugs/2014-August/204384.html

**Comment by Seitanas** [comment]
Yes, this is the one. Easiest way is to change network device type of DHCP server to e1000. I've went to slightly different approach on our production server - I've installed isc-dhcp server packet from unstable distribution, which already has the patch.

**Comment by henickr** [comment]
2 quick comments for anyone reading the thread later... you also need port 5959 along with 80 allowed through ... i noticed this when trying to use it from home... we have firewall rules that work differently fromInside or fromOutside so the websockets traffic had to be routed out to use the web client externally, although it worked fine in the building because inside traffic is more lax.  that's specific to me but may give others ideas as to what they need to do.

and the customizing iso thing... ctrl+shift+f3 works to get you into audit mode where you can install whatever you want then run sysprep so your users get the welcome experience if you want.  a snapshot at the enter new username screen after a fresh install is good.

**Comment by henickr** [comment]
sorry another comment for anybody reading here.... on centos 7 it doesn't look like libvirt sets up the bonded interface as expected.  after poking around the dhcp server and looking for presence of the bug we talked about previously.... nothing to indicate this was happening was found.

I set up a source nat and everything works perfectly on the windows guests as well as linux.

so a SNAT will be required on centos 7 on each hypervisor to translate traffic from the libvirt network to whatever network you have your hypervisor configured on.  i am not sure if the bond came broken but my install is a default libvirt install.

**Comment by Seitanas** [comment]
Hello, I really doubt if there's problem with bonding drivers on centos. Perhaps you are using non bridged bond interface? It should go like this: physical interfaces==>bond==>bridge=>VM.
What type of bond do you use?

**Comment by henickr** [comment]
no not drivers, and bonding works perfectly when configured... i thought you said it was automatically configured by libvirt... i didn't configure a bond at all.... maybe i misunderstood what you said.  i expected from your comments that it would work out of the box because the libvirt install did it.  it doesn't.

the reason i clarified this is because anybody who installs the software on centos will face the same problem.  either set up a nat or set up a bond.  either way, don't expect it to work unless you do it yourself.

what you end up with after installing libvirt on centos is the 192.168.122.0/24 libvirt network, what you choose to do with the traffic from there is completely up to you.  in my case, i turned on ip_forward... set up a nat on each hypervisor and everything works flawlessly.  a bond would have done the trick also... but for centos i'm assuming there should be something said to that effect in instructions.

hope that helps someone.
