### ISSUE TITLE
hypervisors code is corrupt

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#36]
Hi, the hypervisors code is corrupt in the most recent release.

Look at hypervisors/config

**Comment by Seitanas** [comment]
Hello, which part? Had no problems deploying it today.

**Comment by henickr** [comment]
i deployed it twice and it had random junk at the top and bottom of the config file.  i just did it again and it isn't there.  must have been something local.  not sure... dont care... closing this.
