### ISSUE TITLE
enhcancement request:  move to another hypervisor

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#37]
Hi, an option to move a VM to another hypervisor would be a good one.  Especially since its already written it just needs to be modified to move to another machine.  Should be minimal code.

**Comment by Seitanas** [comment]
Yes and no. It will be a problem moving VMs which are on non-shared storage. Still possible though. But it is not priority at the moment, because there is more work to do with current state of KVM-VDI.

**Comment by norwalk350** [comment]
I second henickr's request! That would be amazing to move guests from one host to another! :)

**Comment by sskras** [comment]
I guess 44a8516169e00f36f0cb8a1d034d26c043eff6cc has something to do with namely this request:)
