### ISSUE TITLE
unable to add local hypervisor to dashboard

### ISSUE THREAD

**Issue by brianhenson** [Seitanas/kvm-vdi#39]
Each time I add the local hypervisor to the dashboard it says credential error. I setup the server exactly as the readme said. The html5 client failed per the other bug report.

**Comment by henickr** [comment]
you shouldn't need credentials to add a hypervisor to the dashboard.  create a VDI user and make sure you have ssh keys set so you can connect without a password.  The configuration implies that the VDI user is able to connect without being asked for a password.  If you can ssh VDI@hypervisor (from your dashboard node) and it doesn't prompt you for anything, it will work.

Looks like the developer is on vacation so I'll answer you while he is gone the best I can.

**Comment by brianhenson** [comment]
I can ssh without a password but get Invalid hypervisor credentials. every time. Is there a log that shows whats going on? This is a debian server.

**Comment by brianhenson** [comment]
and just for clarification the hypervisor is on the same box as the web interface.

**Comment by henickr** [comment]
try turning on debug logging using this documentation 
http://wiki.libvirt.org/page/DebugLogs

you can check a few places.... 

first is the dashboard httpd_error log 
second is /var/log/messages
third is /var/log/libvirt/qemu/domainname.log for the individual container log.
and last is debug log, which also throws to messages by default if you configure it as above.

**Comment by Seitanas** [comment]
Are paths to ssh keys on `config.php` correct? Are permissions set correctly for webserver to access those keys? Note - keeping ssh keys in users home directory won't do in most of Linux distributions. It is better to move them out of homedir and make sure webserver user is capable to read them.

**Comment by brianhenson** [comment]
after a bunch of troubleshooting the permissions on the keys were set to 600 after changing that it worked. Thanks all
