### ISSUE TITLE
Nothing under the "select ISO image"

### ISSUE THREAD

**Issue by jphein** [Seitanas/kvm-vdi#4]
![screenshot from 2016-05-11 01-44-04](https://cloud.githubusercontent.com/assets/19301265/15175622/baa5e4a6-1756-11e6-8311-e301c9dd3abc.png)

iso is in the currect directory per the config.php, and is readable by everyone.

**Comment by jphein** [comment]
Can I provide already created KVM vms (.img files)?

**Comment by Seitanas** [comment]
First thing that comes in mind is that system cannot connect to hypervisor via ssh.
Please check if key based connection for your ssh user works.
Try this:
`ssh -i /path_to/id_rsa username@hypervisoraddress`
Second, check if ssh user is configured in "sudoers" file.
Third, check if web server can access ssh keys.
Basically, if your hypervisor has installed vms, they should appear in dashboard if connection over ssh works, and user can execute "sudo virsh" commands. You can use any of already created VM as source image to populate VDI machines (since, VDI machine is just a snapshot of source machine, source VM should be powered off).

**Comment by jphein** [comment]
Apache error log:

> [Wed May 11 12:38:04.647759 2016] [:error] [pid 23331] [client ::1:39568] PHP Warning:  ssh2_auth_pubkey_file(): Authentication failed 
> for vdi using public key: Unable to open public key file in /var/www/html/kvm-vdi/functions/functions.php on line 46, referer: http://l
> ocalhost/kvm-vdi/dashboard.php
> [Wed May 11 12:38:04.647787 2016] [:error] [pid 23331] [client ::1:39568] PHP Warning:  ssh2_exec(): Connection not authenticated in /v
> ar/www/html/kvm-vdi/functions/functions.php on line 50, referer: http://localhost/kvm-vdi/dashboard.php
> [Wed May 11 12:38:04.647793 2016] [:error] [pid 23331] [client ::1:39568] PHP Warning:  ssh2_fetch_stream() expects parameter 1 to be r
> esource, boolean given in /var/www/html/kvm-vdi/functions/functions.php on line 51, referer: http://localhost/kvm-vdi/dashboard.php

**Comment by jphein** [comment]
```
ssh -i ~vdi/.ssh/id_rsa vdi@localhost
Welcome to Ubuntu 15.10 (GNU/Linux 4.2.0-35-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

New release '16.04 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Last login: Wed May 11 12:36:38 2016 from ::1

$ $ 

```

**Comment by jphein** [comment]
sudoers:

```
#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults        env_reset
Defaults        mail_badpass
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root    ALL=(ALL:ALL) ALL

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d

#vdi ALL=(ALL:ALL) NOPASSWD: /usr/bin/virsh, /usr/local/VDI/copy-file, /usr/bin/qemu-img
vdi     ALL=(ALL:ALL) NOPASSWD: /usr/bin/virsh, /usr/local/VDI/copy-file, /usr/bin/qemu-img, /bin/ls, /usr/bin/virt-install, /usr/loca$
```

**Comment by jphein** [comment]
Permissions:

```
ls -lah
total 24K
drwxr----- 2 vdi www-data 4.0K May 10 20:59 .
drwxr-xr-x 6 vdi vdi      4.0K May 11 01:53 ..
-rw------- 1 vdi vdi       394 May 10 20:59 authorized_keys
-rw-r----- 1 vdi www-data 1.7K May 10 20:58 id_rsa
-rw-r--r-- 1 vdi vdi       394 May 10 20:58 id_rsa.pub
-rw-r--r-- 1 vdi vdi       222 May 10 20:59 known_hosts
```

**Comment by jphein** [comment]
It my permissions. I did not have the .ssh folder group executable. 

`chmod g+x .ssh` fixed it.

**Comment by jphein** [comment]
That was the only confusing step. I do not remember the Readme mentioning that you need to make your ssh keys readable by your web server.  Makes perfect sense, but would be nice if it was included in readme.

**Comment by jphein** [comment]
How do you delete the first phantom vms I created before dashboard had ssh access to the hypervisor?

**Comment by Seitanas** [comment]
For security reasons only VDI machines can be deleted. So if you need to delete anything other than VDI machine, change VM type by clicking on its name to "VDI machine". You will be provided by "Delete button" afterwards.

**Comment by Seitanas** [comment]
Also there was a problem deleting machines with missing images. Fix is released.
