### ISSUE TITLE
Enhancement request: add column in Virtual machines for current status

### ISSUE THREAD

**Issue by brianhenson** [Seitanas/kvm-vdi#40]
I would like to see a column on the dashboard page for current status. This would be useful for at a glance status.

**Comment by Seitanas** [comment]
Current status for what exactly? VM? If VM is running you do see green "play" button next to it. Also you can see "screen" button

**Comment by brianhenson** [comment]
more of a text label as some people are color blind it would make it easier for them to see if something is running.

**Comment by ryand32** [comment]
Brian

Like a graph like VMware?

Ryan

**Comment by Seitanas** [comment]
Good point. Will take look into it.

**Comment by brianhenson** [comment]
ryan, Where a graph would be nice, a simple text field with a started, shutdown, rebooting or error tag would be nice

**Comment by Seitanas** [comment]
I'm not sure that text tags will fit anywhere. Will try that

**Comment by henickr** [comment]
if you make the operating system 2 lines you can do Windows / Status ... just an idea... if you can't
