### ISSUE TITLE
Clamav

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#42]
Hi, just an idea for another component to the system.  An antivirus server that downloads clamav and updates itself with a wget then programmatically cycles through each qcow2 file with antivirus turned on and does this...

https://www.si458.co.uk/?p=76

**Comment by Seitanas** [comment]
Well, antivirus is not so vital in VDI VMs if they are used with virtual snapshots. Each shutdown clears all changes in that VM. You should only have clean golden image to provide those VMS.

**Comment by henickr** [comment]
Yeah I thought so too but some vms you may not want to clear if not connected to a thin client --for staff or whoever.  I hear a lot of people do it and was curious if it had any value.  Ty.

**Comment by henickr** [comment]
Or to use on your images.  We have support staff that manage the installation of software... I definitely don't want to do that going forward... So it'd be nice to know if only on initial images.

**Comment by Seitanas** [comment]
Well, we went in different approach - we obtained `Bitdefender Security for Virtualized Environments` antivirus. It offloads scanning of VDI vms to antivirus server VM. Thus you have no antivirus databases on your snapshoted VDI machines.

**Comment by henickr** [comment]
This would be the same if made as a component but I guess that would imply a shared disk space for initial images.

**Comment by Seitanas** [comment]
No its not. In order to mount VM images you have to put VM down. With Gravity zone solution - it works like ordinary antivirus, - it protects live system but offloads everything to external machine.

**Comment by henickr** [comment]
unless of course a copy was performed while it was running and that was scanned then timestamped as to 'last scan' in the database... not sure what kind of extra load that would cause with the overhead.  just an idea.  i'm looking into pricing for your av solution later today.  

not that it's necessary... probably over thinking that anyway.

**Comment by ryand32** [comment]
How about Chef integration :)
