### ISSUE TITLE
bug repopulating database

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#43]
Hi, when you delete your database and repopulate, the script tries to re add images back based on a listing of qcow2 files I assume and the hypervisors populate automatically however when this happens you lose your child/parent relationships.  Either a way an "add as child of" option or some way in the naming convention that the population function can determine this is necessary.

**Comment by Seitanas** [comment]
Hello, if you loose your matadata (drop database) you can edit relations on a dashboard, by pressing on VM name in VM list.

**Comment by henickr** [comment]
oh excellent, i didn't know that.  can you add child/parent relationships inside there as well?  they don't appear to be there in my version of the software (updated yesterday) unless you just added that..... just so you get the right machines under the collapsable thing if required.  if you lose metadata  then use the /install script... it re-adds all vms as parents

also another cool idea in the same area would be a checkbox that allows you to specify default of collapsed or expanded would be great.

**Comment by Seitanas** [comment]
The ability to specify parent VMs is rather old. You should select machine  as "VDI machine", then you will be provided list of available "Initial machines" for it. Note, that you should configure initial machines first.

As for collapse/expand - this is on the roadmap.

**Comment by henickr** [comment]
oh i see, the use volume from is the child/parent relationship.  thanks for clarifying.
