### ISSUE TITLE
request:  client pools admin access to initial machines

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#46]
Hi, I know you did this intentionally for whatever reason is yours but in client_pools.php if you made it so only certain users or admin type users could add initial image machines to specific pools then you would be able to have some granularity in your access.  an admin would have one box in the web client to add software to the guests then they could logout and push right away without ever leaving the browser.  drag and drop works with the client so it would be really useful from an admin perspective or for deploying software.

to clarify the request... the ability to have admin users add initial images to pools... maybe with restrictions that they can only be added to their own pool with no other members.  only admins could also be added to use the pool... "elevated access to control iso via web client" is a good way to phrase.

you probably did this and have some reason for it that i don't know, i expect.

**Comment by Seitanas** [comment]
Not sure, whats wrong with current solution - admin is able to install all software via dashboard service?

**Comment by henickr** [comment]
you can't add initial images to a pool.... it doesn't pop up in the list.  if you did this, it would give the ability to use the html5 client to add software quickly to the image.  shut it down, populate, conveniently.

it also could be a disaster if people didn't understand it... thats why i say for admin type users.

**Comment by Seitanas** [comment]
Well, admin users have no ability to use client software and vice versa, so you would have to use second "admin" client login for that. 
But if I've understood correctly, you want to have multiple level admins - tjhe ones, who are creating vms and controlling kvm-vdi cluster, and second type, who are just installing software into images and who are denied with operations within cluster.
Then it is really a problem. Perhaps it should be allowed to add Initial//Source images to some kind of pool and provide "admin" user to that pool. Will take a look at this. This will break some policies though. Will have to re-thik that.

**Comment by henickr** [comment]
yes i believe you understand exactly.  unless of course the existing admin could do that... is there a reason they can't use client software?  if they were sufficiently locked down so only admin could access the pool or its sounding like maybe a physical limitation because of 2 different admin accounts between 'pools' and 'dashboard'.  either way though, yeah you get the idea.

im a little hesitant to jump onboard with multiple admins thing... i was thinking a checkbox that could flag any user as an image admin (or whatever) .... giving them ability to do this...
