### ISSUE TITLE
populating pools or refresh rate maybe, not sure.  client_pools.php

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#47]
you're going to hate me tomorrow when you read this heh but i think you probably would want it better.. the refresh part at the end i mean... the other part is an actual bug..

i have a known good set of images that i deploy using the 'populate machines' function.  this works well.  the system deploys and they all start up.  when the server normalizes i can connect to them using local virt-viewer clients but in the web interface i can't connect.  strange thing here is i CAN issue a soft shutdown command while connected via virt-viewer and the interface does succeed.  i am not sure how they got in that state.  its just a database thing or something, i'm sure if i drop it all it would be fixed.  just strange how it got that way.  everything was just happy a few minutes ago opening and closing fine until a populate machines was done.

the pool says 0 available vms and the green icon light is off.  i've tried 2 different valid accounts, both are members of the group and it has 10 vms inside it that are all running and working with virt-viewer.

this issue occurs right after a deployment using the 'populate machines' function.

as for the user experience thing... when you issue a soft shutdown or any command... can you have the interface refresh and change the status of the vm to the current status... rebooting or whatever.  now it just says running and isn't exactly accurate.  it could be better.  the reason i suggest this is because without an accurate assessment of machine status you need to connect manually to watch

edit: when you delete all child vms and recreate as if new vdi machines from that initial image... the problem is fixed... sorry maybe i should have let you troubleshoot it... i'll try to reproduce. i have a small demo of this software to do tomorrow so i can try and get some money for an ssd array but when that is complete i'll test again

**Comment by Seitanas** [comment]
Hello, first thing that comes to my mind is that after you populate machines, they are all put into maintenance mode, so you should see empty pool in your web client. Machines, which are in maintenance mode are only available in dashboard (for administration purposes).

**Comment by henickr** [comment]
none were in maint mode... is there a function in the install script that loops through qcow2 files to repopulate the database in event the db gets cleared?  is it possible that function isn't populating an entry that the create from image is doing properly?  i'll try to break it again after my demo at 10:30am AST and i'll see if i can get you more info.

**Comment by henickr** [comment]
ok demo is over and went great.  i'll push the image again now and see if i can recreate the issue.

**Comment by Seitanas** [comment]
One thing, that I can think of, - perhaps `vdi-wrapper failed` to start guests somehow. It managed to announce, it to dashboard, but failed a startup. You should try to start VM via `virsh start` command and see if everything is ok.

**Comment by henickr** [comment]
i am unable to reproduce this.  i will reopen when if/when i find out WTH happened.
