### ISSUE TITLE
unusual load inside windows 7 guest while load in linux is fine on same hypervisor

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#48]
Hi, I am having a strange issue that is unrelated to your software but I am posting it here just because you seem to have encountered almost every issue I have so far so why not.  Others might have this issue also.

Inside the guest with dual core, dual thread each; the load on one core is 30ish and the other is 60ish leaving the guest to idle around 50-55% overall load.  The qemu version is ...
QEMU emulator version 2.3.0 (qemu-kvm-ev-2.3.0-31.el7.16.1), Copyright (c) 2003-2008 Fabrice Bellard

This is where my research has taken me so far but maybe you already experienced this?
https://support.microsoft.com/en-us/kb/895980

That article is dated 2014 and I'm sure my release track is behind that.  It is likely something resolved by updating qemu-kvm somehow or switching to debian unstable as you have... I'm just posting the info here in case there is a known solution I'm not aware of.

**Comment by Seitanas** [comment]
Take a look at process list. Perhaps ovirt guest agent is always taking load of a whole CPU core? If so, you need to update agent o newer version:
https://github.com/Seitanas/kvm-vdi/tree/master/guest_agent/Windows/bin/oVirtGuestService

**Comment by henickr** [comment]
i'm actually using this because it has the qxl drivers and other stuff built in but will try the ovirt one next.
http://www.spice-space.org/download/windows/spice-guest-tools/spice-guest-tools-0.100.exe

the load is coming from svchost.exe... that is how i came to the conclusion i have so far... following that.

**Comment by Seitanas** [comment]
spice-guest tools and ovirt guest agent are used for different things. Infact in KVM-VDI you will have to install both.
As for svchost.exe - have no idea. Perhaps windows update is doing some installs?

**Comment by henickr** [comment]
oh i thought ovirt was included in guest tools.  maybe thats it... i'll poke it a bit and update later... i'm going to close this anyway because it isn't really a problem with your software, i just wanted to ask in case 
thanks!

**Comment by Seitanas** [comment]
Well not having ovirt agent should not give that load on svchost.exe. Not having it will just disable sso.

**Comment by henickr** [comment]
yeah i havne't gotten to sso yet so i didn't notice that... good info i'll be approaching that monday.

i'm sure there are no windows updates because they don't actually work at all on the thin iso so i'm pretty confident that isn't the cause.  i'll update the thread when i resolve it.
