### ISSUE TITLE
issue installing guest_agent sso on windows guest

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#49]
Hi, I am having a problem installing the windows guest_guest agent 32 bit on WinTPC known good image.  When I right click 'save as' each of the components into a folder and attempt to follow the instructions, the .reg file does not work as it says it is not a binary file... when you look inside it, it has <!DOCTYPE html> and lots of other junk in there.... so... After a bit of messing around, I ended up pasting the raw github content into a .txt file then trying to run that with the same result.  

After getting the reg entries configured by manually entering them in regedit (all as DWORD values, the last one as a string) the ovirtguestservice.exe will not install... it crashes saying NTVDM CPU encountered an illegal instruction then NTVDM.exe stops responding completely.

Ideas?  Maybe I should try compiling this from source on the affected system with cygwin?

**Comment by henickr** [comment]
per your comment in chat.... try downloading the zip file using clone or direct zip download of the entire github package seems to have worked.  When I download the entire 77mb zip file and install as per the instructions, everything seems to run ok and the files that were replaced that I originally downloaded were completely different sizes.... Service is now running on startup just fine...

testing sso now...

**Comment by henickr** [comment]
so reading http://www.neblogas.lt/2016/07/18/technical-info-ovirt-agent-sso/

i expect the command
echo "{\"**name**\": \"login\", \"username\": \"someuser\", \"password\": \"somepassword\"}" | socat /var/lib/libvirt/qemu/channel/target/domain-N-machineame/com.kvm-vdi.0 -

in one window, and a socat in another would allow me to see the request sent through the socket similar to tcpdump but it isn't quite as i expect until i cancel the listening socat... so it looks like i can't connect 2 windows to the socket passively but whatever it seems to react as expected... i just wanted to see it happen...  assuming ldap not being done means it has nothing to send.

quick idea also... would you also be able to login to any website maybe with the help of a browser extension or something... since the credentials for sso already have this channel from hypervisor set up via the guest_agent... many people configuring this will be in a corporate/educational environment and webmail is the norm so it would be rather useful.  style points for sure.

**Comment by Seitanas** [comment]
You can use non-LDAP authentication. If you create client users with the same password in dashboard ant in guest OS, then you will be able to login without LDAP.

As for SSO on browsers - this is different type of authentication from that one in KVM-VDI. You should perhaps look at something like microsoft ADFS.

**Comment by henickr** [comment]
ok forget the plugin thing that was just a random idea.. would be nice if it was easily done.

so if the guest is also configured to authenticate via active directory then both will match and succeed.  ok this is going to take a minute to implement and push to all the guests.  

looks like it works ok on initial testing though.

**Comment by henickr** [comment]
still have not gotten to this... been very busy... i will provide an update soon... sorry.
