### ISSUE TITLE
Dashboard hangs at copying source to initial vm. (White screen)

### ISSUE THREAD

**Issue by jphein** [Seitanas/kvm-vdi#5]
http://localhost/kvm-vdi/copy_disk.php?vm=8

**Comment by jphein** [comment]
Just pressed the back button, lol.
Everything seems to be working

**Comment by jphein** [comment]
The .img file did not get copied to he initial vm's qcow image.

**Comment by jphein** [comment]
> grep copy /var/log/apache2/error.log
> [Wed May 11 13:40:07.784529 2016] [:error] [pid 26976] [client ::1:40368] PHP Notice:  Undefined index: hypervisor in /var/www/html/kvm-vdi/copy_disk.php on line 9, referer: http://localhost/kvm-vdi/dashboard.php
> [Wed May 11 13:45:46.970657 2016] [:error] [pid 26856] [client ::1:40440] PHP Notice:  Undefined offset: 2 in /var/www/html/kvm-vdi/copy_disk.php on line 25, referer: http://localhost/kvm-vdi/dashboard.php
> [Wed May 11 13:50:01.803094 2016] [:error] [pid 26978] [client ::1:40592] PHP Notice:  Undefined offset: 2 in /var/www/html/kvm-vdi/copy_disk.php on line 25, referer: http://localhost/kvm-vdi/dashboard.php

**Comment by jphein** [comment]
This happens when you create a new "Initial machine", and point the source to an exisitng KVM .img VM.

**Comment by Seitanas** [comment]
Ive updated README describing, how to install hypervisor. Also note dashboard installation update about permissions on tmp/ folder and config/clients.xml file.
The copy problem should now be fixed in a new realese.
