### ISSUE TITLE
issue with populating VDI machines on dashboard

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#50]
Hi, there is a strange issue after a fresh git pull today... 2 files were updated as follows...
 client_pools.php |  8 +++++++-
 logout.php       | 15 +++++++++++++--
 2 files changed, 20 insertions(+), 3 deletions(-)

Maybe I just didn't notice it previously... doesn't look related to this pull

I have a source and initial image... and 10 VDIs/blade

I issue, 'delete all child VMS' then several times have manually trashed the remanent qcow2 files hanging around in /data just for posterity.  Create 10 new VDI machines from image and somehow a random one is popping out of the child list and duplicating above... see screenshot.

![screen shot 2016-08-23 at 12 23 54 pm](https://cloud.githubusercontent.com/assets/12343647/17897975/7aebfa94-692c-11e6-83a6-ab2a2bd97926.png)

see thin7-06... is both a VDI and somehow duplicated above... I've deleted all children and the strange new one twice now and a different number showed up... it was 03 last time... 

anyway... some minor bug... haven't nailed down why.  functionally is no problem.
correction: is no problem, as long as you don't delete it.

**Comment by henickr** [comment]
small update... sorry functionally it is a small problem.  when i delete the annoying one up top that shouldn't be there.... i get this when restarting... so it is double linked to the VDI entry...

```
root@titanblade03:/data# for each in {01..10}; do virsh start fcs-virtuallab-thin7-$each; done;
Domain fcs-virtuallab-thin7-01 started
Domain fcs-virtuallab-thin7-02 started
Domain fcs-virtuallab-thin7-03 started
Domain fcs-virtuallab-thin7-04 started
Domain fcs-virtuallab-thin7-05 started
error: failed to get domain 'fcs-virtuallab-thin7-06'
error: Domain not found: no domain with matching name 'fcs-virtuallab-thin7-06'
Domain fcs-virtuallab-thin7-07 started
Domain fcs-virtuallab-thin7-08 started
Domain fcs-virtuallab-thin7-09 started
Domain fcs-virtuallab-thin7-10 started
```

**Comment by Seitanas** [comment]
Yes, it seems that it somehow was unable to create machine 06. This is strange. Will take a look at that

**Comment by henickr** [comment]
no, it created perfectly...  i deleted the strange one at the top but it deleted both, machine 06 and the one that popped out of nowhere... expand the screenshot you'll see what i mean..

it not being able to start is caused by me deleting the bad one...

to clarify... i didn't create that top entry at all in the screenshot... that came from nowhere... and deleting it takes with it a good VDI.

**Comment by Seitanas** [comment]
Okay, this explains missing machine, if you've deleted one manually. Does not explain duplication though.

**Comment by henickr** [comment]
yes exactly the issue.  have not investigated any further yet.  it was actually the duplication that caused me to delete it manually... i deleted the dupe...

edit: minor clarification here.  i didn't delete the VDI06, i deleted the phantom entry and it is somehow connected so it took with it the actual qemu domain for VDI06.  somehow due to the way it was created it is connected to the real vdi domain.  if you dont delete it, its a non issue.  Just annoying.

**Comment by henickr** [comment]
![image](https://cloud.githubusercontent.com/assets/12343647/17954348/d0bca016-6a50-11e6-85e7-aff7071169fe.png)

This is another image.... I cleared all the vms several times while doing work tonight testing how many vms i can support total on each blade after doing performance tuning to my iso.  Anyway, created 20 of them and number 12 popped out like before.  (still remains below--screenshot doesn't show)

So that might help diagnose.  Create lots of vms at once to reproduce but it is unreliable.. 

edit: after refreshing... 12 is running when none of the others are ... might be indicative of cause.

**Comment by henickr** [comment]
ok i can now reliably reproduce this bug.

just create 20 vdi vms at once... not sure if the options matter but i'm choosing windows, 7 or newer, 2,2,2 for specs... (that should use 40g of ram, i have 47 on each of the 12 blades -- so i'm ok there) you may not need them specs to reproduce this but i'm including them in case you are still unable to do so.  

i just did a fresh git pull with no updates so the current release is affected.

exact same symptom.  number 06, is running in the VDI group but also duplicated above.

![image](https://cloud.githubusercontent.com/assets/12343647/17954583/42c69076-6a52-11e6-81bc-6e4831b2cc3e.png)

i issued an 'rm -rf /data/--_everything except the initial and source images_--  before creating them and despite all being created in the same manner, the affected guest always starts itself but i am unsure if the starting is a cause or an effect of the bug.  

it does not do it when 15 vms are created (reliably)... only 20.  hope this helps.

**Comment by Seitanas** [comment]
Still can't reproduce this on my site.
I've updated `delete_vm.php` to to write debug output to your webserver error.log. Could you please update and run mass delete - perhaps there will be some info in error.log.

**Comment by henickr** [comment]
sorry for the wait.  had a busy day.  so i am about to reproduce now as done last night.
while tailing error_log on dashboard node before even reproducing, I am seeing this...

[Thu Aug 25 21:42:43.640379 2016] [:error] [pid 7323] [client 129.173.67.9:59281] PHP Notice:  Undefined offset: 0 in /var/www/html/kvm-vdi/client_hb.php on line 22, referer: http://titan.research.cs.dal.ca/kvm-vdi/spice_html5/?host=titan.research.cs.dal.ca&port=5959?password=U9WwzbBaeHn8EFCgUPOqRB8Prl&vmInfoToken=fcs-virtuallab-thin7-04

and i just did a virsh destroy on everything except the initial and source... so the vms it is complaining about, no longer exist.  04&05 
bug did not occur for the first time using same conditions as last time.
try again...
unable to reproduce....  now i'm at a loss.  

i swear i was doing this every single time last night.  nothing now.  
I even took screenshots so you wouldn't think I was crazy lol

edit: github needs a time sync henickr commented 42 seconds from now... neat.]

edit again: ok so i've done it 4 times now, same settings that caused it 100% yesterday and each time in the log the offset error above appears for 4&5 twice each time they are cleared and created but the dupe isn't happening... so i'll update if i get back to a place where i can reproduce again.

**Comment by Seitanas** [comment]
Is there any chance, that VDI VM names overlapped some other VM names while you were mass creating new VMs?

**Comment by henickr** [comment]
Nope I cleared all before each time.  The only things I didn't check were
confirm clear of the db and the fact that I ended the string name with a
nonstandard character.  I tried unsuccessfully to use the - at the end to
cause issue.

Still trying I'll update when I have one.

**Comment by Seitanas** [comment]
Aha, - non standard characters are removed silently, so this could be the thing. I will have to make some JS side test to deny user to create vmname with illegal character.

**Comment by henickr** [comment]
It actually creates fine with the "-" though.  It isn't removed at all.
Definitely a thread to follow up though.  Maybe add some type of separator
to the auto numbering generator and nobody will feel the need to do that.

Interesting anyway how the issue presents.

**Comment by Seitanas** [comment]
`-` is allowed character.
Disallowed ones are: https://github.com/Seitanas/kvm-vdi/blob/master/functions/functions.php#L188
