### ISSUE TITLE
screenshot cache image issue

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#53]
Hi, when you click screenshot, I think it mostly gives you the previous screenshot it took.  The next time you click it, it gives a new one.  For example... you create 10 new vms then start them all... every one of the console buttons will show the windows logo screenshot when you click it the first time... if you click it again, it will show the proper shot.  Its not a big deal but there is something very minor wrong with the function.

**Comment by Seitanas** [comment]
This is known issue with libvirt. It sometimes does produce the same image as one before. Will try to check this on libvirt mailing list.

**Comment by henickr** [comment]
can you just make the button iterate screenshot twice for now.  its crude but it'd work :P

**Comment by Seitanas** [comment]
Well, it would be a dirty hack that should work. But still I want to make there is no way to fix this in libvirt before fixing in KVM-VDI.

**Comment by Seitanas** [comment]
What are ibvirt and qemu versions you use?

**Comment by henickr** [comment]
root@titanblade03:~# libvirtd -V
libvirtd (libvirt) 1.2.17

root@titanblade03:~# /usr/libexec/qemu-kvm --version
QEMU emulator version 2.3.0 (qemu-kvm-ev-2.3.0-31.el7.16.1), Copyright (c) 2003-2008 Fabrice Bellard
