### ISSUE TITLE
Spice_password explanation

### ISSUE THREAD

**Issue by lazzda** [Seitanas/kvm-vdi#54]
Hi, You've done a really great job.
Could you explain the process of spice_password in kvm-vdi. I don understand how you manage it. 

Thanks

**Comment by Seitanas** [comment]
Hello,
spice_password is generated by vdi-wrapper script and passed to qemu-kvm each time VM is started.
This password is then stored in database and provided for remote-viewer and SPICE HTML5 clients.

**Comment by lazzda** [comment]
Thank you,
ok i understand. vdi-xmledit changes the emulator to use vdi-wrapper script. great
