### ISSUE TITLE
enhancement request: AD integration

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#56]
Hi, correct me if I am wrong but when you are connected to AD, you need to perform a bit different 'client' steps to get client_pools.php working properly.

Without AD, you simply 'add client' then 'add client to pool' and providing you have the rest done correctly, the pool populates with machines to issue to users.

With AD, you 'add ad group' then 'add ad group to pool' essentially following the same basic procedure but it would be easier if inside the 'add AD group' popup, there was a button to 'confirm AD connection' or a 'show available groups' or something to that effect... so you know what is happening rather than taking it on faith or checking logs.  A button with a text area or combo box that display the results or an error would be sufficient here to eliminate the ambiguity.

Is it possible to add something like that?

**Comment by henickr** [comment]
oh obviously you're aware of this already and it is probably low priority but when you add AD group, there is no sanity checking as to whether they are valid groups that get entered.... my way above would give a base from which to run sanity checks to confirm they are actual available groups being added to the pools...

also... there is no way (that i see) short of deleting directly from the database, to remove groups after they have been added.... for example, i added a test one ksdjfhsdkjfhd to see if it performed sanity checking and there is no way to get rid of it without doing it in the database.

**Comment by Seitanas** [comment]
Hello, you will see errors in your webserver error log file if there is any problems with LDAP/AD configuration, so I think this sanity check is enough.
As for listing groups - I've still not decided if it is a good idea. It will work nicely with small ADs, but will overload server if you have a big organization with loads of groups. I think I will leave this as is for now, - perhaps will find some dynamic listing solution later.
For the deletion of groups - yes you can. Simply clone last KVM-VDI. This ability was released today:
https://github.com/Seitanas/kvm-vdi/commits/master
