### ISSUE TITLE
dashboard appears empty

### ISSUE THREAD

**Issue by GeorgeWuTw** [Seitanas/kvm-vdi#57]
I installed dashboard by following README. Dashboard appears empty.
I found there is no such folder and file described below after cloning kvm-vdi.
"Change permissions on tmp/ folder and functions/clients.xml file to give webserver writeable rights."

**Comment by Seitanas** [comment]
These lines in README are no longer used. Fixed.
Please define "empty dashboard" - is it just white page?
If so, - check your webserver error log. It is possible, that you are missing some PHP modules.

**Comment by GeorgeWuTw** [comment]
I use mysql 5.7 install of mariadb and it seems better. Populating the first DB got some kind of trouble and I manually create db and default user account 'admin'. It works now, I see dashboard.
