### ISSUE TITLE
Invalid hypervisor credentials. 

### ISSUE THREAD

**Issue by Nickeloerus** [Seitanas/kvm-vdi#58]
ssh -i /var/hyper_keys/id_rsa VDI@hypervisor_address test works but in dash i get the error Invalid hypervisor credentials. 

`
VDI@KVM-Dash:/root$ ssh -i /var/hyper_keys/id_rsa VDI@10.100.0.226

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Sep 14 14:08:20 2016 from 10.100.0.216
VDI@PiCa-kvm-hyper01:~$
`

**Comment by Seitanas** [comment]
This usually happens when your web server cannot read your SSH key files. Check permissions and also webserver error log.

**Comment by Nickeloerus** [comment]
permissions on /var/hyper_keys/? what permissions are needed ?

**Comment by Nickeloerus** [comment]
set 644 on /var/hyper_keys fixed it... that i didn't tried that myself 

thank you
