### ISSUE TITLE
Question regarding VDI creation

### ISSUE THREAD

**Issue by norwalk350** [Seitanas/kvm-vdi#64]
Not really so much an issue, just a question. 

The initial machine creates itself (no problem). However, when I try to create VDI machines from initial machine, the process is very slow.

For example, I tried to populate some VDI machines with a Windows 7 32-bit initial machine. Over the period of the population, the speed is going at under 1MB/sec.

Eventually, the copy process just fails after awhile. 

Now, I was thinking it could be our disk performance (we currently have conventional 1TB drives in a RAID 10 array; we are going to upgrade to 8TB RAID 10 SSD storage). We are piloting this right now. If it works as intended, we are going to purchase an exceptionally beefy machine. 

Just wondering if there is any advice on why the QCOW2 creation for VDI machines is slow. 

Any help is much appreciated! Thanks!

**Comment by Seitanas** [comment]
This should not perform poorly like this. VDI machines are created from snapshots, so there is no big IO load. The only part where entire image is coped is when you copy initial image from source machine.
Perhaps you are creating too many VDI vms? All populated machines are started after new snapshot is created, this may overload your hypervisor resources if you overpopulate it.

**Comment by norwalk350** [comment]
Thank you for your assistance. I believe our resources are limited. However, I think we are going to proceed with upgrading our hardware.

Thank you again for all of your assistance! This project is amazing! :)
