### ISSUE TITLE
when I access HTML5 console via: http://YOUR_DASHBOARD/kvm-vdi/client it comes error  

### ISSUE THREAD

**Issue by brike** [Seitanas/kvm-vdi#68]
![image](https://cloud.githubusercontent.com/assets/7145838/19689568/65858886-9b00-11e6-939e-a050675b6696.png)
 how can i fix it...

**Comment by Seitanas** [comment]
The error is self explanatory, - something is blocking connection between your browser and websockify server.

**Comment by henickr** [comment]
Your client location needs to be able to connect to port 80 (or 443 if
HTTPS) and port 5959 or it will display a black screen.

You should be able to telnet and connect to both from the same location you
are running your client.

HTH
