### ISSUE TITLE
a question...about spice html5 client 

### ISSUE THREAD

**Issue by brike** [Seitanas/kvm-vdi#69]
when ip address is 127.0.0.1 in my token file ,it can works perfectly, but when change it to 192.168.1.102(it is the real ip address), it can not work...should i update some config file ???
my url is http://192.168.1.102/kvm-vdi/spice_html5/?host=192.168.1.102&port=5959?password=11&vmInfoToken=v5

**Comment by henickr** [comment]
Depends how libvirt is configured by the sound of it.  It might not be
listening on all interfaces.  You need to be able to make a telnet
connection from the client location to both port 5959 and 80 (or 443) in
order to connect to the spice client and then the dashboard must be able to
telnet to the hypervisor chosen on the spice port it is running on.

If those 3 conditions are met, you should connect.

**Comment by henickr** [comment]
If using RHEL edit /etc/sysconfig/libvirt LISTEN_ARGS

**Comment by henickr** [comment]
http://wiki.libvirt.org/page/Libvirt_daemon_is_not_listening_on_tcp_ports_although_configured_to

**Comment by brike** [comment]
I have tried to telnet.
my Dashboard and Hypervisor are in one machine ,ip is 192.168.1.102, i can telnet 127.0.0.1 5900,but can not telnet 192.168.1.102 5900

**Comment by henickr** [comment]
If you do netstat -tulpn dies it say it is listening on local host or
something else?

**Comment by brike** [comment]
the system i use is ubuntu 16.04

**Comment by brike** [comment]
LocalAddress shows 
0.0.0.0:5959
127.0.0.1:5900

**Comment by henickr** [comment]
So I see the problem but don't know how on Ubuntu.  The developer has his
on that so he can probably help you.  Websockify is fine... Listening on
all but libvirt is only on local host.  In RHEL follow the doc I pasted
first because for security, default installs do that.  I'm sure Ubuntu is
similar... I'll see if I can find you a doc.

**Comment by brike** [comment]
thanks very much!

**Comment by henickr** [comment]
Found it

Enable TCP in the libvirt service on the host OS.

Edit /etc/libvirt/libvirtd.conf to set:
listen_tls = 0
listen_tcp = 1
auth_tcp="none"
tcp_port = "16509"
Configure the libvirt service to listen on TCP

Edit /etc/init/libvirt-bin.conf to add the "-l" argument:
exec /usr/sbin/libvirtd -d -l
Restart libvirt service

**Comment by Seitanas** [comment]
Hello, it is not related with libvirt. I see, that your QEMU opens SPICE socket to 0.0.0.0 you should be able to connect to your vm directly.
If you are denied  to 192.168.1.102 but can telnet via localhost, then it will probably will be firewall thing. Please disable your firewall and try again.
