### ISSUE TITLE
spice_html5 issues

### ISSUE THREAD

**Issue by norwalk350** [Seitanas/kvm-vdi#70]
Hi Seitanas,

I'm starting to produce the KVM-VDI system on our virtual host. Everything is working except the spice_html5 client. We can access the VM's through the virt-viewer client. 

Here are some of the steps I have taken:

1.) First, I have checked the run.js file in /var/www/html/kvm-vdi/spice_html5 directory and saw that it was requesting SSL connections, not plaintext. 

Per instructions, I changed the protocol from 'wss' to 'ws'

![image](https://cloud.githubusercontent.com/assets/22620330/20431062/fe987b60-ad65-11e6-84a2-aa6085cfec12.png)

I plan on getting SSL working later, but for right now (to simplify things), I am going plaintext.

2.) I have checked the ufw firewall in Ubuntu. The status is inactive.
![image](https://cloud.githubusercontent.com/assets/22620330/20431106/3542ef74-ad66-11e6-9eee-5c3dcd9e3fea.png)

3.) I added iptable rules to allow incoming traffic to port 5959. 

Is there something I'm missing? I've ran packet captures and saw RST's previously. 

Any help is much appreciated! Thanks!

**Comment by Seitanas** [comment]
Hello, can you telnet to your dashboard server via port 5959?

**Comment by henickr** [comment]
External clients need access to both port 80 and 5959... THEN the dashboard
needs to be able to telnet to the vnc port of the hypervisor.  You can find
out which by reading the token in /tmp/kvmvdi but as a rule of thumb the
dashboard should be able to telnet to any listening 59xx port on any of its
hypervisors.

Hope this helps.

**Comment by norwalk350** [comment]
Yes, I can

![image](https://cloud.githubusercontent.com/assets/22620330/20431957/fd3e0956-ad6a-11e6-8038-3b9ac363a348.png)

UPDATE: Some of the computers work now (Freaky Friday, depending on timezone.....)

I think it has something to do with my browser. Could it be something with my runtime environments? (i.e. Java, Flash, etc.)

Does KVM-VDI rely on any runtimes? I guess I can close the issue, being the issue is now on my end. Any help is still much appreciated!

**Comment by Seitanas** [comment]
No, there is nor runtime requiremet for that. It is just html5 and js. But be aware, that html5 support is still bleeding edge and is not production capable, so you will probably encaunter problems at some point. It is highly recommended to use gtk client.

**Comment by norwalk350** [comment]
Thank you very much Seitanas and henickr! :)

**Comment by henickr** [comment]
Use Google chrome canary build for best results in my experience.
