### ISSUE TITLE
creating machine from source to initial issue

### ISSUE THREAD

**Issue by norwalk350** [Seitanas/kvm-vdi#71]
Hello Seitanas,

I remember a little while back I submitted an issue regarding initial machine creation (#62). 

It looks like I'm getting the same error as the previous issue. 

![image](https://cloud.githubusercontent.com/assets/22620330/20492109/823e2870-afe1-11e6-9340-73cf92aab857.png)

I checked the permissions and it looks like it creates the file with root ownership. 

![image](https://cloud.githubusercontent.com/assets/22620330/20492157/b3405556-afe1-11e6-9510-f5cd094ea583.png)

I did a chown -R libvirt-qemu;kvm as well as checking permissions in the directory that holds the qcows. Everything looks in order. 

Is there something I'm missing? As always, any help is much appreciated! Thanks! :)

**Comment by Seitanas** [comment]
Hello, by default KVM-VDI changes image owner to root. You can change this in `config.php`
Not sure if this is an issue though. Does `copy-file` command from hypervisor side work from console? perhaps you have some dependencies missing.

**Comment by norwalk350** [comment]
Figured it out. Thanks!
