### ISSUE TITLE
open console not work

### ISSUE THREAD

**Issue by potatofamily** [Seitanas/kvm-vdi#76]
new create a source vm, but when I click "Open console", no picture is display in popup window, click any button , window is hidden.

**Comment by Seitanas** [comment]
Refresh your dashboard, are machines created?

**Comment by potatofamily** [comment]
yes, create a Source machine, click "VM Actions"-> "Open console", popup a window, include three buttons, SPICE console , HTML5 console , Close. when create Source machine, mount a debian netinstall iso image, seed "Success", but no start install. I used Ubuntu 16.04.

**Comment by henickr** [comment]
If you do a virsh list --all on the hypervisor you should see the same as
the dashboard.... Can you virsh start it?

**Comment by potatofamily** [comment]
I am not install virsh, try now.

**Comment by potatofamily** [comment]
run virsh list --all, nothing to display.
dashboard and hypervisor are in same server.

**Comment by Seitanas** [comment]
Enable debug logging in your config.php file. Then try creating machine. Look into webserver error log after. There should be debug information.

**Comment by thiagocpv** [comment]
I am getting a lot of errors to create the Source. After creation, I can't access the console. Please see below:

[Wed Jun 14 21:04:36.364509 2017] [:error] [pid 18945] [client 189.4.201.172:52559] command: sudo virt-install --name='SourceVM' --disk path='/data/SourceVM-5941a4e458fba.qcow2',format=qcow2,bus=virtio,cache=none --soundhw=ac97 --vcpus='2',cores='2',sockets='1' --ram='1024' --network bridge='br0',model=virtio --os-type='linux' --os-variant='debiansqueeze' --graphics spice,listen=0.0.0.0,password=jARrkzB8e4YIa --redirdev usb,type=spicevmc --video qxl --noreboot --wait=0 --noautoconsole --cdrom '/var/lib/libvirt/images/debian-8.8.0-amd64-lxde-CD-1.iso', referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:04:36.364558 2017] [:error] [pid 18945] [client 189.4.201.172:52559] Executing: sudo qemu-img create -f qcow2 -o size='20'G '/data/SourceVM-5941a4e458fba.qcow2', referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:04:36.620980 2017] [:error] [pid 18945] [client 189.4.201.172:52559] Formatting '/data/SourceVM-5941a4e458fba.qcow2', fmt=qcow2 size=21474836480 encryption=off cluster_size=65536 lazy_refcounts=off refcount_bits=16\n, referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:04:36.621031 2017] [:error] [pid 18945] [client 189.4.201.172:52559] Executing: sudo virt-install --name='SourceVM' --disk path='/data/SourceVM-5941a4e458fba.qcow2',format=qcow2,bus=virtio,cache=none --soundhw=ac97 --vcpus='2',cores='2',sockets='1' --ram='1024' --network bridge='br0',model=virtio --os-type='linux' --os-variant='debiansqueeze' --graphics spice,listen=0.0.0.0,password=jARrkzB8e4YIa --redirdev usb,type=spicevmc --video qxl --noreboot --wait=0 --noautoconsole --cdrom '/var/lib/libvirt/images/debian-8.8.0-amd64-lxde-CD-1.iso', referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:04:37.652050 2017] [:error] [pid 18945] [client 189.4.201.172:52559] ERROR    Cannot get interface MTU on 'br0': No such device\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start SourceVM\notherwise, please restart your installation.\n, referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:04:37.692125 2017] [:error] [pid 18945] [client 189.4.201.172:52559] Executing: sudo /usr/local/VDI//vdi-xmledit -name 'SourceVM', referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:04:37.731480 2017] [:error] [pid 18945] [client 189.4.201.172:52559] Traceback (most recent call last):\n  File "/usr/local/VDI//vdi-xmledit", line 24, in <module>\n    tree = ET.parse('/etc/libvirt/qemu/' + vmname+'.xml')\n  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse\n    tree.parse(source, parser)\n  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse\n    source = open(source, "rb")\nIOError: [Errno 2] No such file or directory: '/etc/libvirt/qemu/SourceVM.xml'\n, referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:04:37.731751 2017] [:error] [pid 18945] [client 189.4.201.172:52559] Traceback (most recent call last):\n  File "/usr/local/VDI//vdi-xmledit", line 24, in <module>\n    tree = ET.parse('/etc/libvirt/qemu/' + vmname+'.xml')\n  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse\n    tree.parse(source, parser)\n  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse\n    source = open(source, "rb")\nIOError: [Errno 2] No such file or directory: '/etc/libvirt/qemu/SourceVM.xml'\n, referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:04:37.731774 2017] [:error] [pid 18945] [client 189.4.201.172:52559] \nStarting install...\n, referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:04:38.002718 2017] [:error] [pid 18945] [client 189.4.201.172:52559] Executing: sudo virsh list --all |tail -n +3|head -n -1|awk '{print $2" "$3}', referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:05:34.786902 2017] [:error] [pid 21316] [client 189.4.201.172:52560] Executing: sudo virsh domdisplay SourceVM, referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:05:34.920457 2017] [:error] [pid 21316] [client 189.4.201.172:52560] error: failed to get domain 'SourceVM'\nerror: Domain not found: no domain with matching name 'SourceVM'\n, referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:05:35.187287 2017] [:error] [pid 21316] [client 189.4.201.172:52560] Executing: sudo virsh screenshot SourceVM /tmp/SourceVM.ppmbugfix, referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:05:35.319969 2017] [:error] [pid 21316] [client 189.4.201.172:52560] error: failed to get domain 'SourceVM'\nerror: Domain not found: no domain with matching name 'SourceVM'\n, referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:05:35.320249 2017] [:error] [pid 21316] [client 189.4.201.172:52560] Executing: sudo virsh screenshot SourceVM /tmp/SourceVM.ppm, referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:05:35.388264 2017] [:error] [pid 21316] [client 189.4.201.172:52560] error: failed to get domain 'SourceVM'\nerror: Domain not found: no domain with matching name 'SourceVM'\n, referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:05:35.388519 2017] [:error] [pid 21316] [client 189.4.201.172:52560] Executing: sudo cat /tmp/SourceVM.ppm, referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:05:35.436097 2017] [:error] [pid 21316] [client 189.4.201.172:52560] cat: /tmp/SourceVM.ppm: No such file or directory\n, referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:05:35.439189 2017] [:error] [pid 21316] [client 189.4.201.172:52560] PHP Fatal error:  Uncaught ImagickException: no decode delegate for this image format `' @ error/blob.c/BlobToImage/361 in /var/www/html/kvm-vdi/screenshot.php:26\nStack trace:\n#0 /var/www/html/kvm-vdi/screenshot.php(26): Imagick->readimageblob('cat: /tmp/Sourc...')\n#1 {main}\n  thrown in /var/www/html/kvm-vdi/screenshot.php on line 26, referer: http://107.189.44.26/kvm-vdi/dashboard.php
[Wed Jun 14 21:05:38.482467 2017] [:error] [pid 20661] [client 189.4.201.172:52561] Executing: sudo virsh list --all |tail -n +3|head -n -1|awk '{print $2" "$3}', referer: http://107.189.44.26/kvm-vdi/dashboard.php?password=jARrkzB8e4YIa
