### ISSUE TITLE
Possible Security Improvement for SPICE 

### ISSUE THREAD

**Issue by norwalk350** [Seitanas/kvm-vdi#79]
Hi Seitanas,

While implementing KVM-VDI in a pre-production environment, I thought about different security measures. The one that sticks out the most, to me, is how KVM-VDI passes the authentication parameters (for SPICE). 

If anyone receives the GET parameters, they can access the virtual machine. I added a PHP session variable to the index.php in the spice_html5 directory, so that anyone who tries to access the machine (from the GET parameters), will have to login via their LDAP credentials (if they are in the allowed group). 

It's kinda odd how it works (for me). However, it strengthens the security of the machines (if a stranger somehow stumbles upon the GET parameters). 

Here is what I put in:

`<?php
    session_start();
    if(!isset($_SESSION['username']))
    {
    header('Location: /kvm-vdi/client_index.php');
    exit;
    }
    ?>
`

Just thought I would throw this out there. 

If you want, I can delete this post. Just let me know.

**Comment by Seitanas** [comment]
Hello,
after having some thoughts about it, I think this will not make big security improvement. Since if SPICE password is known to third party, one can use SPICE-HTML5 client on his local machine to connect directly to websockify server thus skipping security check at all.
