### ISSUE TITLE
Adding new hypervisor

### ISSUE THREAD

**Issue by hutger** [Seitanas/kvm-vdi#80]
Hi, 

Whenever I try to add a new hypervisor, the message "Contacting hypervisor" is shown but nothing happens. In /var/log/auth.log I got the message below: 

Jan 12 21:05:27 KVM-VDI sshd[2172]: Received disconnect from 127.0.0.1 port 58992:11: PECL/ssh2 (http://pecl.php.net/packages/ssh2) [preauth]
Jan 12 21:05:27 KVM-VDI sshd[2172]: Disconnected from 127.0.0.1 port 58992 [preauth]

Any clue?

**Comment by Seitanas** [comment]
Hello,
it seems that there is some problem authenticating to ssh server. Are rsa keys readable by web server?
Perhaps there's something in your webs erver error log file?
Also you can try enabling debug logging in config.php file: '$write_debug_log=true;' all debug info will be written to your web server error log file.

**Comment by henickr** [comment]
Most common issue here is web server cannot read ssh keys.

**Comment by hutger** [comment]
Hello, it was a permissions problem. The web server couldn't read the id_rsa file. Now it's working.

Thanks a lot guys.
