### ISSUE TITLE
KVM-VDI on Oracle Linux

### ISSUE THREAD

**Issue by Gokev79** [Seitanas/kvm-vdi#84]
I am new to GIT and have a request for a change in the code.

In the file:
kvm-vdi/hypervisors/vdi-xmledit

The line:
if 'centos' not in distribution and 'redhat' not in distribution and 'fedora' not in distribution:

changed in:
if 'centos' not in distribution and 'redhat' not in distribution and 'fedora' not in distribution and 'oracle' not in distribution:

Now you can used Oracle Linux (KVM) as hypervisor to.!

Regards

**Comment by Seitanas** [comment]
Thank you. Fixed this issue.

**Comment by Gokev79** [comment]
Wow fast! COOL!
