### ISSUE TITLE
HTML5 console not working

### ISSUE THREAD

**Issue by Gokev79** [Seitanas/kvm-vdi#85]
We get a black-screen if we open the HTML5 console.

connections al working (telnet and native spice client). So this is not het problem. 

I have set the in the config:
#Websockify server address (if using HTML5 client)
$websockets_address='172.30.0.70';
#Port of websockify server (if using HTML5 client)
$websockets_port='5959';

When I used the HTML5 console, I get the following error:
WebSocket connection to 'ws://10.11.12.100/?password=vsYhv9qmIXHLxcUaWdL7gDmoE2&token=WIN7-SM' failed: WebSocket is closed before the connection is established.

So I changed the run.js in the spice_html5 from:
                'host': getURLParameter('host') || '10.11.12.100',
                'port': getURLParameter('port') || 8000,

to:
                'host': getURLParameter('host') || '172.30.0.70',
                'port': getURLParameter('port') || 5959,

I get the error:
WebSocket connection to 'ws://172.30.0.70/?password=vsYhv9qmIXHLxcUaWdL7gDmoE2&token=WIN7-SM' failed: Error during WebSocket handshake: Unexpected response code: 200

Is I stopped the websockify and I still get this error.!

So it looks like it connect on poort 80 (http server) and not on port 5959.

Regards,

Kevin

**Comment by Seitanas** [comment]
Hello, you should not change anything in run.js. Unless you are running https, then you probably will have to change `protocol': getURLParameter('protocol') || 'ws',` to `protocol': getURLParameter('protocol') || 'wss',`.

How exactly are you trying to connect to html5 client? You should not go directly into spice_html5/ directory.
Instead you should use HTML5 client `/client_index.php`.

**Comment by Gokev79** [comment]
I now, I changed for troubleshooting.

If I go to the HTML5 console, I get the following URL:
http://172.30.0.70/kvm-vdi/spice_html5/?host=&port=?password=vsYhv9qmIXHLxcUaWdL7gDmoE2&vmInfoToken=WIN7-SM

**Comment by Seitanas** [comment]
This is strange. Are you sure, that websockets are configured in `functions/config.php`. Are there any errors in web server log file?

**Comment by Gokev79** [comment]
For testing I have changed the HTTP server to poort 81 and run websockify on poort 80. 
Now it's working.! 

So it's look like that in functions/config.php. The config items
#Websockify server address (if using HTML5 client)
$websockets_address='172.30.0.70';
#Port of websockify server (if using HTML5 client)
$websockets_port='5959';

Not are used!

**Comment by henickr** [comment]
there is likely something wrong with your firewall.  you need to make sure
port 80 and 5959 are accessible from your dashboard TO your hypervisor in
question

**Comment by Gokev79** [comment]
Nope it's no firewall problem (here is no firewall) and with telnet I can connect.

I have changed it back. Http on poort 80 and websockify on poort 5959. 

I get this error in chrome:
WebSocket connection to 'ws://172.30.0.70/?password=qLY34j6d8QUJYHb4M1xeICht23&token=WIN7-SM' failed: Error during WebSocket handshake: Unexpected response code: 200

It is connecting to the webserver en not to websockify on poort 5959.

**Comment by Gokev79** [comment]
I get also error's in apache log:
[Wed May 03 15:38:48.436229 2017] [:error] [pid 24366] [client 172.30.0.9:32225] PHP Notice:  Undefined index: client_logged in /var/www/html/kvm-vdi/functions/functions.php on line 63, referer: http://172.30.0.70/kvm-vdi/spice_html5/?host=&port=?password=qLY34j6d8QUJYHb4M1xeICht23&vmInfoToken=WIN7-SM
[Wed May 03 15:38:48.445835 2017] [:error] [pid 24366] [client 172.30.0.9:32225] PHP Notice:  Undefined variable: engine in /var/www/html/kvm-vdi/functions/functions.php on line 302, referer: http://172.30.0.70/kvm-vdi/spice_html5/?host=&port=?password=qLY34j6d8QUJYHb4M1xeICht23&vmInfoToken=WIN7-SM

**Comment by henickr** [comment]
The only thing changing the port suggests to me is that it is either
unreachable or already in use when it was started.  Before you start apache
or websockify make sure the
lsof -i output is clean.  Just guessing though.

Are your dashboard and hypervisor on the same host?  Are you able to
connect to the hypervisor vm using spicec or the spice viewer application?
Make sure there are no odd routes in the routing table.  Just ideas...

**Comment by Gokev79** [comment]
Dashboard and hypervisor are on different hosts.

Virtviewer to the spice port works on the hypervisor. 

netstat -nap show's that HTTP run on poort 80 and websockify on poort 5959
Telnet to the ports works fine.  So no route or firewall problem.

So only i see is that HTML console for te websocket connect's to poort 80 and not to poort 5959. Even is it is configured in config.php on 5959. 
and 
If i not set 'host': getURLParameter('host') || '172.30.0.70', in run.js it even connect to the wrong IP.

And another thing (thought):
If you create a new virtual machine. Field network is now empty. But had this not filled with $default_bridge from the config.php?

It's looks there is something wrong with de variables.

**Comment by Gokev79** [comment]
Mmmm I created a VDI machine, so I can connect to a VM on the client side. Not the admin.

I get a very strange page. So there is more wrong.
![test](https://cloud.githubusercontent.com/assets/28134987/25665874/2777e1c4-301f-11e7-93ff-943e8da49bef.png)

likely a fresh install will help. ;-)

**Comment by Seitanas** [comment]
`Undefined variable: engine` shows, that `$engine` is missing in config.php. This could happen, if you are using old config.php on a new KVM-VDI installation.

**Comment by Seitanas** [comment]
This patch should fix issue, described in the screenshot.

**Comment by Gokev79** [comment]
Update fixed the schreenshot. 

This (test) installation is a updated of a "old" installation (with no HTML5 problems). This is a test to, so I will start over for the dashboard. Maybe all problems are fixed than.

Thanks!

**Comment by Gokev79** [comment]
I had a few days off. Therefore, what a late response
I have updated and now it works.!!!
