### ISSUE TITLE
Installation Doubt

### ISSUE THREAD

**Issue by ghost** [Seitanas/kvm-vdi#87]
Hello!
I already have a server running KVM in production with some servers...Can I share the same KVM instance and hardware to run kvm-vdi?

My plan is install the dashboard in a separated machine and connect the dashboard with the same KVM instance that I already have. Is this possible?

Thank you.

**Comment by Seitanas** [comment]
Hello,
yes, KVM-VDI is capable of providing simple VM management for non-VDI machines, so it should work without any problems.

**Comment by ghost** [comment]
OK good! Thank you very much!
