### ISSUE TITLE
VDI --> Populate machines only populates the first one.

### ISSUE THREAD

**Issue by jphein** [Seitanas/kvm-vdi#9]
It does not populate VDI machines beyond 1. 

vdi-2 and vdi-3 do not get populated.

![screenshot from 2016-05-12 19-59-02](https://cloud.githubusercontent.com/assets/19301265/15236698/ccf46388-18b6-11e6-8002-3944397bbfe4.png)

**Comment by jphein** [comment]
Also, with a VDI machine the Power up button is always green.  Regardless of whether it is actually running. 

![screenshot from 2016-05-12 20-02-15](https://cloud.githubusercontent.com/assets/19301265/15236732/2770b050-18b7-11e6-91b1-3f738b7b65e2.png)

**Comment by Seitanas** [comment]
The first thing i see here is that you are probably populating VDI VMs from powered on "Initial machine". This will cause a corruption of a VDI disk image. VDI VM runs from a snapshot of "Initial machine" drive, so if "Initial machine" is powered on, its drive image constantly changes, and thus VDI snapshot is not consistent anymore.
I suggest you to power off Initial machine, then populate VDI VMS. They should power on in maintenance mode with virtual snapshots turned off, as soon as they are populated. Afterwards we can try debugging further

**Comment by jphein** [comment]
I have done as you have suggested.
![screenshot from 2016-05-12 22-47-50](https://cloud.githubusercontent.com/assets/19301265/15239021/49d30780-18ce-11e6-8eb8-bb75a858b198.png)

Still only the first one is created:

```
ls -lah
total 55G
drwxrwxrwx  2 vdi          www-data 4.0K May 12 22:46 .
drwxr-xr-x 10 root         root     4.0K May 12 18:55 ..
-rw-r--r--  1 root         root     4.2G May 12 19:47 golden1-573536959ad64.qcow2
-rw-r--r--  1 libvirt-qemu kvm      4.2G May 12 19:40 initial-57353dd0c1e78.qcow2
-rw-r--r--  1 libvirt-qemu kvm       18M May 12 22:47 ubuntu1-57356a3d10c35.qcow2
-rw-rw-rw-  1 root         root      33G May 11 14:00 win10-1.img
-rw-rw-rw-  1 root         root      16G May 11 15:26 win10-clone.img
-rw-rw-rw-  1 root         root      33G May 11 22:44 win10.img
```

```
virsh list
 Id    Name                           State
----------------------------------------------------
 27    ubuntu1                        running
```

The initial VM is actually off. I don't know why the button is green.

**Comment by Seitanas** [comment]
Could you please paste me more recent part of auth.log with sudo lines?
`cat /var/log/auth.log |grep sudo`

**Comment by jphein** [comment]
> May 12 22:45:58 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:45:58 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:45:58 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:45:59 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:45:59 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:45:59 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:02 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh domblklist ubuntu3
> May 12 22:46:02 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:02 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:02 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh destroy ubuntu3
> May 12 22:46:02 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:02 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:02 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh undefine ubuntu3
> May 12 22:46:02 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:02 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:02 shuriken sudo:      vdi : command not allowed ; TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/bin/rm error: failed to get domain ubuntu3error: Domain not found: no domain with matching name ubuntu3
> May 12 22:46:02 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:46:02 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:02 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:02 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:46:02 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:02 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:04 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh domblklist ubuntu2
> May 12 22:46:04 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:04 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:05 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh destroy ubuntu2
> May 12 22:46:05 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:05 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:05 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh undefine ubuntu2
> May 12 22:46:05 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:05 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:05 shuriken sudo:      vdi : command not allowed ; TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/bin/rm error: failed to get domain ubuntu2error: Domain not found: no domain with matching name ubuntu2
> May 12 22:46:05 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:46:05 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:05 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:05 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:46:05 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:05 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:08 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh domblklist ubuntu1
> May 12 22:46:08 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:08 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:08 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh destroy ubuntu1
> May 12 22:46:08 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:08 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:08 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh undefine ubuntu1
> May 12 22:46:08 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:08 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:08 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/bin/rm /opt/vms/ubuntu1-573540752b3d9.qcow2
> May 12 22:46:08 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:08 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:08 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:46:08 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:08 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:09 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:46:09 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:09 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:12 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/bin/ls /opt/iso
> May 12 22:46:12 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:12 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:37 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh domblklist initial
> May 12 22:46:37 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:37 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:37 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/qemu-img create -f qcow2 -b /opt/vms/initial-57353dd0c1e78.qcow2 /opt/vms/ubuntu1-57356a3d10c35.qcow2
> May 12 22:46:37 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:37 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:37 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virt-install --name=ubuntu1 --disk path=/opt/vms/ubuntu1-57356a3d10c35.qcow2,format=qcow2,bus=virtio,cache=none --soundhw=ac97 --vcpus=1,cores=1 --ram=2048 --network bridge=br1,model=virtio --os-type=linux --os-variant= --graphics spice,listen=0.0.0.0 --redirdev usb,type=spicevmc --video qxl --noreboot --import
> May 12 22:46:37 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:37 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:37 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/local/VDI//vdi-xmledit -name ubuntu1
> May 12 22:46:37 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:37 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:37 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:46:37 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:37 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:38 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:46:38 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:38 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:52 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh domblklist initial
> May 12 22:46:52 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:52 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:52 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh destroy ubuntu1
> May 12 22:46:52 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:52 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:52 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh domblklist ubuntu1
> May 12 22:46:52 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:52 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:52 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/qemu-img create -f qcow2 -b /opt/vms/initial-57353dd0c1e78.qcow2 /opt/vms/ubuntu1-57356a3d10c35.qcow2
> May 12 22:46:52 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:52 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:52 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh start ubuntu1
> May 12 22:46:52 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:53 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:53 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh destroy ubuntu2
> May 12 22:46:53 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:53 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:53 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh domblklist ubuntu2
> May 12 22:46:53 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:53 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:53 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/qemu-img create -f qcow2 -b /opt/vms/initial-57353dd0c1e78.qcow2 error: failed to get domain ubuntu2error: Domain not found: no domain with matching name ubuntu2
> May 12 22:46:53 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:53 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:53 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh start ubuntu2
> May 12 22:46:53 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:53 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:53 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh destroy ubuntu3
> May 12 22:46:53 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:53 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:53 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh domblklist ubuntu3
> May 12 22:46:53 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:53 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:53 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/qemu-img create -f qcow2 -b /opt/vms/initial-57353dd0c1e78.qcow2 error: failed to get domain ubuntu3error: Domain not found: no domain with matching name ubuntu3
> May 12 22:46:53 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:53 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:53 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh start ubuntu3
> May 12 22:46:53 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:53 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:54 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:46:54 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:54 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:46:54 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:46:54 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:46:54 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:50:59 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh destroy initial
> May 12 22:50:59 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:50:59 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:50:59 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:50:59 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:50:59 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:50:59 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:50:59 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:50:59 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:51:02 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh shutdown initial
> May 12 22:51:02 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:51:02 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:51:02 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:51:02 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:51:02 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:51:03 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:51:03 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:51:03 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:51:05 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh destroy initial
> May 12 22:51:05 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:51:05 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:51:05 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:51:05 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:51:05 shuriken sudo: pam_unix(sudo:session): session closed for user root
> May 12 22:51:05 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
> May 12 22:51:05 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
> May 12 22:51:05 shuriken sudo: pam_unix(sudo:session): session closed for user root
> 
> ```
> ```

**Comment by Seitanas** [comment]
I see. This problem occurs, when "inintial machine" uses non virtio storage controller. This fix should solve the problem.

**Comment by jphein** [comment]
It still says my initital machine is powered on when in fact it is not. 
![screenshot from 2016-05-12 23-21-24](https://cloud.githubusercontent.com/assets/19301265/15239557/0f9fc832-18d3-11e6-8057-0d771b2051b9.png)

```
virsh list
 Id    Name                           State
----------------------------------------------------


```

**Comment by jphein** [comment]
Still only the initial one is created.
![screenshot from 2016-05-12 23-25-25](https://cloud.githubusercontent.com/assets/19301265/15239618/927bdd72-18d3-11e6-893e-dd9d708050ee.png)

```
ls -lah
total 55G
drwxrwxrwx  2 vdi          www-data 4.0K May 12 23:24 .
drwxr-xr-x 10 root         root     4.0K May 12 18:55 ..
-rw-r--r--  1 root         root     4.2G May 12 19:47 golden1-573536959ad64.qcow2
-rw-r--r--  1 libvirt-qemu kvm      4.2G May 12 19:40 initial-57353dd0c1e78.qcow2
-rw-r--r--  1 root         root     193K May 12 23:24 ubuntu1-57357324f3d30.qcow2
-rw-rw-rw-  1 root         root      33G May 11 14:00 win10-1.img
-rw-rw-rw-  1 root         root      16G May 11 15:26 win10-clone.img
-rw-rw-rw-  1 root         root      33G May 11 22:44 win10.img
```

```
virsh list
 Id    Name                           State
----------------------------------------------------


```

**Comment by Seitanas** [comment]
What is the output of
`sudo virsh list --all |tail -n +3|head -n -1|awk '{print $2 " " $3}'`
?

**Comment by jphein** [comment]
It is using Virtio storage
![screenshot from 2016-05-12 23-28-34](https://cloud.githubusercontent.com/assets/19301265/15239676/031b9b1c-18d4-11e6-84cd-3c7e471eb28e.png)

**Comment by jphein** [comment]
```
sudo virsh list --all |tail -n +3|head -n -1|awk '{print $2 " " $3}'
golden1 shut
initial shut
PXE shut
ubuntu1 shut
win10 shut
win10-clone shut
win10-pro shut

```

**Comment by Seitanas** [comment]
Is there by any chance, that you are creating new VDI machines with the same name as existing ones?

**Comment by jphein** [comment]
Yes, but I always delete them first. I do not create any new machine with the name of one that currently exists.

**Comment by Seitanas** [comment]
This is really odd, i cant reproduce this on my system. 
What is more recent output of 
`cat /var/log/auth.log |grep sudo`
after you've updated create_vm.php ?

**Comment by jphein** [comment]
May 12 23:38:15 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh domblklist initial
May 12 23:38:15 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
May 12 23:38:15 shuriken sudo: pam_unix(sudo:session): session closed for user root
May 12 23:38:15 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/qemu-img create -f qcow2 -b /opt/vms/initial-57353dd0c1e78.qcow2 /opt/vms/moo1-57357657d75df.qcow2
May 12 23:38:15 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
May 12 23:38:15 shuriken sudo: pam_unix(sudo:session): session closed for user root
May 12 23:38:16 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virt-install --name=moo1 --disk path=/opt/vms/moo1-57357657d75df.qcow2,format=qcow2,bus=virtio,cache=none --soundhw=ac97 --vcpus=1,cores=1 --ram=2048 --network bridge=br1,model=virtio --os-type=linux --os-variant=ubuntuprecise --graphics spice,listen=0.0.0.0 --redirdev usb,type=spicevmc --video qxl --noreboot --import
May 12 23:38:16 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
May 12 23:38:16 shuriken sudo: pam_unix(sudo:session): session closed for user root
May 12 23:38:16 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/local/VDI//vdi-xmledit -name moo1
May 12 23:38:16 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
May 12 23:38:16 shuriken sudo: pam_unix(sudo:session): session closed for user root
May 12 23:38:16 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
May 12 23:38:16 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
May 12 23:38:16 shuriken sudo: pam_unix(sudo:session): session closed for user root
May 12 23:38:17 shuriken sudo:      vdi : TTY=unknown ; PWD=/home/vdi ; USER=root ; COMMAND=/usr/bin/virsh list --all
May 12 23:38:17 shuriken sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
May 12 23:38:17 shuriken sudo: pam_unix(sudo:session): session closed for user root
May 12 23:38:50 shuriken sudo:     root : TTY=pts/1 ; PWD=/opt/vms ; USER=root ; COMMAND=/usr/bin/virsh list --all
May 12 23:38:50 shuriken sudo: pam_unix(sudo:session): session opened for user root by jeffrey(uid=0)
May 12 23:38:50 shuriken sudo: pam_unix(sudo:session): session closed for user root

**Comment by jphein** [comment]
![screenshot from 2016-05-12 23-45-22](https://cloud.githubusercontent.com/assets/19301265/15240024/4a99199a-18d6-11e6-8d8a-5d2b41e5d1e7.png)

**Comment by jphein** [comment]
```
sudo virsh list --all |tail -n +3|head -n -1|awk '{print $2 " " $3}'
golden1 shut
initial shut
moo1 shut
PXE shut
win10 shut
win10-clone shut
win10-pro shut
```

**Comment by jphein** [comment]
I'm getting a strange error from Virtual Machine Manager when trying to boot my old win10.img.
![screenshot from 2016-05-12 23-57-40](https://cloud.githubusercontent.com/assets/19301265/15240299/36d75474-18d8-11e6-9780-b9d1a4551a5e.png)

```
ls -lah
total 60G
drwxrwxrwx  2 vdi          www-data 4.0K May 12 23:55 .
drwxr-xr-x 10 root         root     4.0K May 12 18:55 ..
-rw-r--r--  1 root         root     4.2G May 12 19:47 golden1-573536959ad64.qcow2
-rw-r--r--  1 libvirt-qemu kvm      4.2G May 12 19:40 initial-57353dd0c1e78.qcow2
-rw-r--r--  1 root         root     4.2G May 12 23:55 ubuntu-sysprep-573579b33b423.qcow2
-rw-rw-rw-  1 root         root      33G May 11 14:00 win10-1.img
-rw-rw-rw-  1 root         root      16G May 11 15:26 win10-clone.img
-rw-rw-rw-  1 root         root      33G May 11 22:44 win10.img
-rw-r--r--  1 root         root     193K May 12 23:49 win10-initial-573578e903bef.qcow2
```

**Comment by jphein** [comment]
It makes the first VDI machine image, and it turns it on, when you create the VDI's. However it does not make the other ones.

**Comment by Seitanas** [comment]
Okay, it seems that your libvirtd runs as non-root user. Even if this does not cause a current problem, i see, that it may cause some other problems on some systems. I will fix this now and we will try to investigate this further.

**Comment by jphein** [comment]
Great, thank you!

**Comment by jphein** [comment]
libvirt is running as root

`ps aux|grep libvirt
root      1067  0.0  0.2 1199064 46232 ?       Ssl  May11   0:19 /usr/sbin/libvirtd
libvirt+  1953  0.0  0.0  45268  2528 ?        S    May11   0:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/virtbr0.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper
libvirt+  2343  0.0  0.0  45268  2416 ?        S    May11   0:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/physvirt0.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper
root     30851  0.0  0.0   9516  2124 pts/1    S+   00:27   0:00 grep --color=auto libvirt
`

**Comment by Seitanas** [comment]
I still can't find the problem in code. I've decided to install Ubuntu 15 machine and try to reproduce this issue there.
Meanwhile, could you try to reinstall dashboard? Perhaps there are some files which were not updated? Just git clone kvm-vdi and copy all files over the old ones.

**Comment by jphein** [comment]
I've updated my entire kvm-vdi directory. I also started upgrading to Ubuntu xenial 16.04.

**Comment by jphein** [comment]
It seems to be working now. =]

**Comment by Seitanas** [comment]
Could you creating new VDI machines again and then paste PHP error log?

**Comment by Seitanas** [comment]
So problem was solved after you've upgraded to 16.04?

**Comment by jphein** [comment]
Problem is solved. I have not yet upgrade to 16.04. Still on 15.10.

**Comment by Seitanas** [comment]
So, entropy strikes again :)
Hope this won't re-appear
