### ISSUE TITLE
how could i install the hypervisor on a same server? wiki document is given but its not working for me could you give me the steps

### ISSUE THREAD

**Issue by praburaj1985** [Seitanas/kvm-vdi#90]

**Comment by nerijus** [comment]
padekitenamokukaipveikiayradokumentasnesuprantu

**Comment by henickr** [comment]
Which part don't you understand?  Or you don't understand the language?

**Comment by praburaj1985** [comment]
Am not able to view the targeted hypervisor option  
Am followed the steps in that instruction I can understand the language

**Comment by nerijus** [comment]
youareverluckymostofusdonotunderstandatall

**Comment by henickr** [comment]
Errors should be passed into webserver error log but there is a debug
option in configuration file that will crank up the verbosity.  I can help
if you describe the point where the failure happens.  Are you able to get
the dashboard to display?

**Comment by praburaj1985** [comment]
Yes i can get the dashboard view,but am cannot get the hypervisor option in that option please refer the below links.


<img width="677" alt="capture1" src="https://user-images.githubusercontent.com/22237394/27213734-6ad2f27c-5286-11e7-9914-03a3ef018140.PNG">
<img width="678" alt="capture2" src="https://user-images.githubusercontent.com/22237394/27213739-6f59fe08-5286-11e7-8927-b804580a050f.PNG">

**Comment by Seitanas** [comment]
You need to add hypervisor first via `Add hypervisor` option.

**Comment by praburaj1985** [comment]
Thanks for the quick response 
<img width="679" alt="capture3" src="https://user-images.githubusercontent.com/22237394/27214680-511dbfba-528b-11e7-9969-a9cdb9259241.PNG">

**Comment by Seitanas** [comment]
Are you sure that you can connect to 192.168.0.152 via SSH on port 56917?

**Comment by praburaj1985** [comment]
yes am changed the default port 22 also its showing the same error. there is any kvm-vdi port. how can i check the ssh default port no?

**Comment by Seitanas** [comment]
Try connecting to this address from dashboard server's console via `ssh` command. Does it connect?

**Comment by praburaj1985** [comment]
yes its connecting with 22 port

**Comment by Seitanas** [comment]
What does your webserver error log say?

**Comment by praburaj1985** [comment]
<img width="954" alt="capture4" src="https://user-images.githubusercontent.com/22237394/27217558-fc71a85c-5297-11e7-9f1d-ee8b0be10155.PNG">

**Comment by Seitanas** [comment]
There is something wrong with SSH public key validation. Please check if you've generated ssh public keys properly and if they are readable by webserver.

**Comment by praburaj1985** [comment]
am followed the document i know am done a mistake while am doing but i cant identify so kindly give me the screenshot for the ssh keys how to copy the /var/hyper_keys

**Comment by Seitanas** [comment]
Please, connect to your dashboard servers console and type:

`ssh -i /var/hyper_keys/id_rsa VDI@192.168.0.152`

What does it say?

**Comment by praburaj1985** [comment]
<img width="617" alt="capture5" src="https://user-images.githubusercontent.com/22237394/27223609-d01a6106-52ae-11e7-9c61-ffe8cbe76af5.PNG">

**Comment by Seitanas** [comment]
It should not ask for password if public key validation succeeded. Something is still wrong with public key authentication.

**Comment by henickr** [comment]
Do ssh-copy-id VDI@192.168.0.152 from the dashboard server and then try
again

**Comment by Seitanas** [comment]
This will copy pub key of current user. More correct approach would be:  
`ssh-copy-id -i /var/hyper_key/id_rsa.pub VDI@192.168.0.152`

**Comment by henickr** [comment]
sorry, thanks for correction.  I always su first so I forgot syntax

**Comment by praburaj1985** [comment]
ok. if am using the same server has a dashboard server and hypervisor server means what i want to do

**Comment by Seitanas** [comment]
1) `ssh-copy-id -i /var/hyper_key/id_rsa.pub VDI@localhost`
2) add "localhost" via `Add hypervisor` option.

**Comment by praburaj1985** [comment]
refer the below image these are the steps am followed.But am getting error

<img width="785" alt="capture6" src="https://user-images.githubusercontent.com/22237394/27226261-b9f769de-52bb-11e7-84b2-4b426c0cc365.PNG">

**Comment by Seitanas** [comment]
Replace hyper_key with hyper_keys

**Comment by praburaj1985** [comment]
yes am replaced the name now am able to login the ssh without the password but the hypervisor said error ssh bad credentials
<img width="677" alt="capture8" src="https://user-images.githubusercontent.com/22237394/27227781-87fc90a6-52c2-11e7-8615-a0faa939e2ab.PNG">
<img width="498" alt="capture7" src="https://user-images.githubusercontent.com/22237394/27227788-8b945f14-52c2-11e7-9945-79fb5e917cab.PNG">

**Comment by praburaj1985** [comment]
<img width="563" alt="capture9" src="https://user-images.githubusercontent.com/22237394/27227850-d21c1d82-52c2-11e7-9393-78528becd625.PNG">

**Comment by praburaj1985** [comment]
above already added

**Comment by henickr** [comment]
if you can ssh VDI@192.168.0.152 without being asked for a password, the
step to add to dashboard should work as long as the hyper_keys folder/file
is readable by the webserver... you can test this by doing lsof -i:80 (I
assume port 80) to find out the user it runs as... then do su apache (or
whatever user you found) --shell=/bin/bash; ls /var/hyper_keys...... test
the folder and pub file.  if you can see them the server should be ok.  if
you get no such file, check your perms.  if all is ok, add in dashboard
normally.

**Comment by praburaj1985** [comment]
Hi thanks for clearing the doubts and am appreciate your patience thanks and once again Seitanas and henickr 
1.yes am check the ssh VDI@192.168.0.152 login without password
2.while am check the webserver lsof -i:80 with this command nothing is running in this command how could i change it

**Comment by praburaj1985** [comment]
<img width="434" alt="capture10" src="https://user-images.githubusercontent.com/22237394/27230023-7934f820-52cb-11e7-9b83-8ce5b821a317.PNG">

**Comment by Seitanas** [comment]
`chown -R www-data:www-data /var/hyper_keys`

**Comment by praburaj1985** [comment]
Thanks Buddyies i got the hypervisor
<img width="679" alt="capture11" src="https://user-images.githubusercontent.com/22237394/27230718-cf6714f6-52cd-11e7-9940-f692075e0978.PNG">

**Comment by praburaj1985** [comment]
Thanks lot......

**Comment by ahmedgc01** [comment]
Hi everyone , 
please help me I'm stuck at this step hypervisor, I'm unable to connect to hypervisor without password . 
![image](https://user-images.githubusercontent.com/26581611/41859430-96dbb722-78b5-11e8-9c7b-aefa22d1b15a.png)
