### ISSUE TITLE
Am not able to create the VM 

### ISSUE THREAD

**Issue by praburaj1985** [Seitanas/kvm-vdi#91]
<img width="953" alt="capture12" src="https://user-images.githubusercontent.com/22237394/27251684-6a1c11d6-5369-11e7-8af3-45d8e959d32f.PNG">

**Comment by Seitanas** [comment]
The machine failed to create. Enable debug logging and look into web server error log.

**Comment by praburaj1985** [comment]
This is the error am getting
![image](https://user-images.githubusercontent.com/22237394/27273410-8aaa9ee8-54ec-11e7-9781-7a4671f62010.png)

**Comment by Seitanas** [comment]
These are not errors - just notices. You should get error, when creating new vm with debug log enabled.

**Comment by praburaj1985** [comment]
where is that option am not get that option in the menu
![image](https://user-images.githubusercontent.com/22237394/27273788-38daca28-54ee-11e7-99ad-f59d94b134a7.png)

**Comment by praburaj1985** [comment]
![image](https://user-images.githubusercontent.com/22237394/27277370-a41c33f0-54fb-11e7-9686-90da5b24dc9c.png)

**Comment by Seitanas** [comment]
You do not have br0 bridge interface. You need to create it first. Also your hypervisor does not support virtualisation (Intel VT-X or AMD-V)

**Comment by praburaj1985** [comment]
actually my hardware supports the VT am check with the BIOS itself its there

**Comment by praburaj1985** [comment]
![image](https://user-images.githubusercontent.com/22237394/27279660-f360dda6-5502-11e7-8a41-de9c72596362.png)

**Comment by henickr** [comment]
no not support.  you need to create the devices.  Google procedure to be
sure but I believe the commands should be like this:

brctl create br0; brctl addif eth0 br0;

or something along those lines.

**Comment by praburaj1985** [comment]
yes bridge is created now and am able to view the VDI but the html5 display showing blank

![image](https://user-images.githubusercontent.com/22237394/27281402-5bcd74ca-5509-11e7-9fdb-3b00643e9133.png)

**Comment by Seitanas** [comment]
Please read into closed issues:
https://github.com/Seitanas/kvm-vdi/issues?q=is%3Aissue+is%3Aclosed
there are many similar questions.
