### ISSUE TITLE
How to start the 5959 service in KVM-VDI

### ISSUE THREAD

**Issue by praburaj1985** [Seitanas/kvm-vdi#92]
Hi,
  Am installed the wesockyfi and am also changed ws in the run.js file but still am get the black screen while am click the html5 console there is no firewall running in that server i can get the spice console through the remore-virt but html5 only showing black screen am check all the closed issues but my scenario is different
while am run the netstat command for 5959 port is not running in my server how could i start the port service please tell me.

**Comment by Seitanas** [comment]
Did you start websockify server?

**Comment by praburaj1985** [comment]
./run --token-plugin TokenFile --token-source /tmp/kvm-vdi 5959 --daemon

this is the command to start the websockify. am right?

**Comment by Seitanas** [comment]
Yes. Try running it without `--daemon` option. You will get output to std, when trying to connect with HTML5.

**Comment by praburaj1985** [comment]
yes am did but same presist

**Comment by praburaj1985** [comment]
yes it is working because the websockify am clone the websockify again its working
