### ISSUE TITLE
hi spice_html5 shows the reverse screen how could i change it

### ISSUE THREAD

**Issue by praburaj1985** [Seitanas/kvm-vdi#93]
![image](https://user-images.githubusercontent.com/22237394/27381471-96dbdc3a-56a0-11e7-85a9-da3c5f3ce875.png)

**Comment by Seitanas** [comment]
Not related to KVM-VDI. You need to install spice-vdagent if using QXL video device.

**Comment by praburaj1985** [comment]
Spice VDagent is already installed 
![image](https://user-images.githubusercontent.com/22237394/27426911-be1e7dba-575a-11e7-8561-1136fb8c3068.png)

**Comment by henickr** [comment]
It needs to be installed on your image, not the hypervisor.  I've also had
a problem where this problem still occurred but reinstall and\or clone of
the VDI fixes the problem after restarting the vm.  Maybe it's a driver
bug, not sure.

If already installed on the guest, clone it again from your primary image
again try starting it again.

Sorry I can't be of more help.

**Comment by henickr** [comment]
for me, the problem went away after I re-cloned it.

**Comment by praburaj1985** [comment]
OK let me check
