### ISSUE TITLE
Windows installation error 

### ISSUE THREAD

**Issue by praburaj1985** [Seitanas/kvm-vdi#94]
While am installing the windows OS am getting the blue dump error even am changed the qxl to cirrus there is any qemu/kvm issue am using Ubuntu 16 there is any please suggest for suitable   hypervisor OS

**Comment by henickr** [comment]
Install qemu-system-ev package

**Comment by henickr** [comment]
I think that's what it's called... do a yum search qemu | grep ev and
you'll find it

**Comment by Seitanas** [comment]
This problem is not related to KVM-VDI. I sugest using newest windows drivers for your windows version.
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.139-1/
