### ISSUE TITLE
Am not able to manage the Qemu/KVM trough KVM-VDI 

### ISSUE THREAD

**Issue by praburaj1985** [Seitanas/kvm-vdi#97]
Am not able to start the VDI from the dashboard and getting the frequent error getting from the apache2

[Fri Jun 30 12:10:13.732160 2017] [:error] [pid 6262] [client 192.168.12.57:59371] Executing: sudo virsh list --all |tail -n +3|head -n -1|awk '{print $2" "$3}', referer: http://192.168.0.152/kvm-vdi/dashboard.php

**Comment by Seitanas** [comment]
This is not error. This is just a debug message. There should be more information in log file when you are starting VM

**Comment by praburaj1985** [comment]
Yes Thanks after long troubleshooting now its working now
