### ISSUE TITLE
how to add the VDI-agent service into the Hypervisor server

### ISSUE THREAD

**Issue by praburaj1985** [Seitanas/kvm-vdi#98]
Am copied the files from hypervisor to /usr/local/VDI in the hypervisor server but i cant start the VDI-agent service

**Comment by henickr** [comment]
why not?

**Comment by ryand32** [comment]
Seitanas,

How is the linked clones coming along for provisioning in Citrix?

Ryan

**Comment by Seitanas** [comment]
There are no plans to add support for citrix as for it is a closed source enterprise solution. KVM-VDI will continue to be developed for KVM and OpenSatck solutions.
