### ISSUE TITLE
Will install OS but won't boot afterwards

### ISSUE THREAD

**Issue by nmitchell1185** [Seitanas/kvm-vdi#99]
When creating a VM, I can boot initially to the iso and install the OS. However, after successfully installing it attempts to reboot but won't successfully boot up again. It will run, go into a pause state, then shut down. I have tried it with both Mint and Ubuntu 16 with the same results. No errors pop up in the dashboard, but below are some of the errors that populate in the web server error log. 

[Thu Aug 24 10:07:02.168633 2017] [:error] [pid 1914] [client 10.5.8.233:40305] Executing: echo "{\\"vmname\\":\\"ubuntu-source\\",\\"username\\":\\"\\",\\"password\\":\\"*****\\",\\"os_type\\":\\"linux\\"}"| socat /usr/local/VDI/kvm-vdi.sock - , referer: http://10.5.8.208/kvm-vdi/dashboard.php

[Thu Aug 24 10:07:02.959380 2017] [:error] [pid 1913] [client 10.5.8.233:40308] Executing: sudo virsh list --all |tail -n +3|head -n -1|awk '{print $2" "$3}', referer: http://10.5.8.208/kvm-vdi/dashboard.php

I am saving the VM's and ISO's on a mounted drive but have the permissions opened up so it shouldn't be a permission issue. 

Any ideas?

**Comment by Seitanas** [comment]
Try running vm manually `virsh start vmname` on hypervisor side.

**Comment by nmitchell1185** [comment]
I get the following error when I try doing that:

error: failed to get domain 'mint-source-599ef385eb85c.qcow2'
error: Domain not found: no domain with matching name 'mint-source-599ef385eb85c.qcow2'

When I do `virsh list`, it comes back with a blank list.

**Comment by Seitanas** [comment]
`mint-source-599ef385eb85c.qcow2`  is a disk image name, not vmname.
`virsh list --all` should list all available vms.

**Comment by nmitchell1185** [comment]
I get the following error when I try doing it correctly:

error: Failed to start domain mint-source
error: monitor socket did not show up: No such file or directory

I have websockify installed and running...if that is what the monitor socket is referring to.

**Comment by Seitanas** [comment]
Take a look at your vm error log (usually located at /var/log/libvirt/)

**Comment by nmitchell1185** [comment]
Here is what shows up in it:
2017-08-24 15:40:56.044+0000: starting up libvirt version: 1.3.1, package: 1ubuntu10.13 (Andreas Hasenack <andreas@canonical.com> Tue, 01 Aug 2017 10:50:20 -0300), qemu version: 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.14), hostname: kvm-vdi
LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin QEMU_AUDIO_DRV=spice /usr/bin/kvm-spice -name mint-source -S -machine pc-i440fx-xenial,accel=kvm,usb=off -m 1024 -realtime mlock=off -smp 1,sockets=1,cores=1,threads=1 -uuid 03574cb3-ff0f-4ba1-8cce-24144db57113 -no-user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/domain-mint-source/monitor.sock,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -no-hpet -no-reboot -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -boot strict=on -device ich9-usb-ehci1,id=usb,bus=pci.0,addr=0x6.0x7 -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x6 -device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x6.0x1 -device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x6.0x2 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x5 -drive file=/data/vms/mint-source-599ef385eb85c.qcow2,format=qcow2,if=none,id=drive-virtio-disk0,cache=none -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x7,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=2 -drive file=/data/images/linuxmint-18.iso,format=raw,if=none,id=drive-ide0-1-0,readonly=on -device ide-cd,bus=ide.1,unit=0,drive=drive-ide0-1-0,id=ide0-1-0,bootindex=1 -netdev tap,fd=26,id=hostnet0,vhost=on,vhostfd=28 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:88:76:f8,bus=pci.0,addr=0x3 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -chardev spicevmc,id=charchannel0,name=vdagent -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0 -spice port=5900,addr=0.0.0.0,image-compression=off,seamless-migration=on -device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vgamem_mb=16,bus=pci.0,addr=0x2 -device AC97,id=sound0,bus=pci.0,addr=0x4 -chardev spicevmc,id=charredir0,name=usbredir -device usb-redir,chardev=charredir0,id=redir0 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x8 -msg timestamp=on
char device redirected to /dev/pts/1 (label charserial0)
((null):2626): Spice-Warning **: reds.c:2189:reds_handle_read_link_done: Peer doesn't support AUTH selection
main_channel_link: add main channel client
main_channel_handle_parsed: net test: latency 45.655000 ms, bitrate 42434162 bps (40.468370 Mbps)
((null):2626): Spice-Warning **: reds.c:2189:reds_handle_read_link_done: Peer doesn't support AUTH selection
((null):2626): Spice-Warning **: reds.c:2189:reds_handle_read_link_done: Peer doesn't support AUTH selection
((null):2626): Spice-Warning **: reds.c:2189:reds_handle_read_link_done: Peer doesn't support AUTH selection

**Comment by Seitanas** [comment]
Don't see anything wrong here. Is vm shown as started via `virsh list --all` ?

**Comment by nmitchell1185** [comment]
No, it is shown as shut off.

**Comment by Seitanas** [comment]
try running vm directly:
`LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin QEMU_AUDIO_DRV=spice /usr/bin/kvm-spice -name mint-source -S -machine pc-i440fx-xenial,accel=kvm,usb=off -m 1024 -realtime mlock=off -smp 1,sockets=1,cores=1,threads=1 -uuid 03574cb3-ff0f-4ba1-8cce-24144db57113 -no-user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/domain-mint-source/monitor.sock,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -no-hpet -no-reboot -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -boot strict=on -device ich9-usb-ehci1,id=usb,bus=pci.0,addr=0x6.0x7 -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x6 -device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x6.0x1 -device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x6.0x2 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x5 -drive file=/data/vms/mint-source-599ef385eb85c.qcow2,format=qcow2,if=none,id=drive-virtio-disk0,cache=none -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x7,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=2 -drive file=/data/images/linuxmint-18.iso,format=raw,if=none,id=drive-ide0-1-0,readonly=on -device ide-cd,bus=ide.1,unit=0,drive=drive-ide0-1-0,id=ide0-1-0,bootindex=1 -netdev tap,fd=26,id=hostnet0,vhost=on,vhostfd=28 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:88:76:f8,bus=pci.0,addr=0x3 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -chardev spicevmc,id=charchannel0,name=vdagent -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0 -spice port=5900,addr=0.0.0.0,image-compression=off,seamless-migration=on -device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vgamem_mb=16,bus=pci.0,addr=0x2 -device AC97,id=sound0,bus=pci.0,addr=0x4 -chardev spicevmc,id=charredir0,name=usbredir -device usb-redir,chardev=charredir0,id=redir0 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x8 -msg timestamp=on`

**Comment by nmitchell1185** [comment]
it errors with the following error: 

2017-08-24T17:09:56.009727Z qemu-system-x86_64: -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/domain-mint-source/monitor.sock,server,nowait: Failed to bind socket to /var/lib/libvirt/qemu/domain-mint-source/monitor.sock: No such file or directory

When I navigate to qemu and list the contents it only contains channel, dump, nvram, save, and snapshot.

**Comment by Seitanas** [comment]
Is apparmor enabled?

**Comment by nmitchell1185** [comment]
No, I uninstalled it. 

This is the only thing I have running on this server so I may just wipe it and start over if you are out of ideas on what it could be.

**Comment by Seitanas** [comment]
No, apparmor should be disabled. It was just one thing to check. Try escalating permissions to /var/lib/libvirt/qemu directory.
cmod 777 `/var/lib/libvirt/qemu`

**Comment by nmitchell1185** [comment]
No change, still getting the same errors.

**Comment by Seitanas** [comment]
take a look at your ` /etc/libvirt/qemu.conf`
maybe there's `security_driver` enabled?

**Comment by nmitchell1185** [comment]
security_driver is set to selinux, but it is commented out.

**Comment by Seitanas** [comment]
I will have to investigate this on ubuntu16 then.

**Comment by nmitchell1185** [comment]
I am going to start over and see if I run into the same issues after a fresh install of everything. I will leave this open for now in the event I run into the same issue after reinstalling. 
Thanks for the help.
I am using Ubuntu 16.04 Server.

**Comment by Seitanas** [comment]
I've installed complete KVM-VDI solution on to Ubuntu 16.04.3 LTS today. I cannot reproduce the same error. Everything works just fine. So there must be local problem somewhere in your installation.

**Comment by nmitchell1185** [comment]
I reinstalled and everything is working fine now.
